### ISSUE TITLE
Classes already declared in the upper scope

### ISSUE THREAD

**Issue by wgcrouch** [babel/babel-eslint#104]
eslint 0.21.1 and babel-eslint 3.1.5 with the following eslint rc: 

    {
      "parser": "babel-eslint",
       "env": {
        "browser": true,
        "node": true
      },
      "ecmaFeatures": {
        "jsx": true
      }
    }

With this test file: 

    "use strict";

    export class Foo {

    }

I get;

    > node_modules/.bin/eslint test.js

    test.js
      3:13  error  Foo is already declared in the upper scope

**Comment by hzoo** [comment]
This looks like a duplicate of #99 - tell me if you experience the same error with just the `eslint` parser. If so the issue in eslint is eslint/eslint/issues/2545 which has been fixed in eslint master but doesn't have a new release yet.

**Comment by wgcrouch** [comment]
Using eslint master works, so this is a duplicate.  I'll close it, thanks
