### ISSUE TITLE
no-shadow: Already declared in the upper scope

### ISSUE THREAD

**Issue by vially** [babel/babel-eslint#106]
$ cat foo.js
```js
export default class Foo{}
```
$ eslint foo.js
```
foo.js
  1:21  error  Foo is already declared in the upper scope  no-shadow

✖ 1 problem (1 error, 0 warnings)
```

**Comment by hzoo** [comment]
This seems to be the same as #99? Are you using the latest eslint - 0.21.2?
ESLint issue: https://github.com/eslint/eslint/issues/2545
https://github.com/eslint/eslint/releases/tag/v0.21.2

**Comment by vially** [comment]
Yes, it seems to be the same issue. I'm closing it now as it seems to be an issue with eslint.

**Comment by hzoo** [comment]
Does the latest eslint fix it for you? Maybe try the master branch.

**Comment by vially** [comment]
Yes. The latest eslint (0.21.2) fixed the issue for me. Thanks!
