### ISSUE TITLE
default parameters as variables triggers `no-unused-vars` incorrectly

### ISSUE THREAD

**Issue by bobbyrenwick** [babel/babel-eslint#111]
```es6
"use strict";

var bar = 1;

function myFunc({foo=bar}) {}

module.exports = myFunc;
```

gives a `bar is defined but never used no-unused-vars` error.

Using eslint 0.21.2 and babel-eslint 3.1.7

**Comment by hzoo** [comment]
Does eslint give you an issue without using `babel-eslint` as the parser?

**Comment by hzoo** [comment]
@bobbyrenwick can you reproduce with the normal parser?

**Comment by hzoo** [comment]
Closing as I can reproduce with regular parser.
