### ISSUE TITLE
babel-eslint report no-undef for flow type $FixMe

### ISSUE THREAD

**Issue by tsing** [babel/babel-eslint#119]
in v3.1.11 this code below will got no-undef error:
```
export var foo: $FixMe = 1;
```

the `$FixMe` was introduced in flow 0.11 https://github.com/facebook/flow/blob/master/Changelog.md#v0110

**Comment by hzoo** [comment]
Ok looks like `$FixMe` is an alias for `any`? I don't know if we want this to go in babel as an alias for `AnyTypeAnnotation` (I guess similar to mixed)? @sebmck For now you can add to the  `.eslintrc` globals.

**Comment by sebmck** [comment]
I don’t think this nessitates a unique AST node, seems rather hack.

**Comment by hzoo** [comment]
Yeah ok, don't want too many of these one off things. Maybe eslint can add a `'flow"` environment later that gives you all these globals.

**Comment by tsing** [comment]
It seems that the `$FixMe` is removed from flow 0.12.0
