### ISSUE TITLE
JSX html attrs flagged as 'no-undef'

### ISSUE THREAD

**Issue by joemaller** [babel/babel-eslint#12]
Is it normal for every JSX tag name and attribute to be flagged as `no-undef`?

Here's a simplified case (extra boilerplate was removed):

    var EshintJSXTest = React.createClass({
      render: function() {
        return <div className="foo" />;
      }
    });

Running `aslant` from the command line gives me this:

    EshintJSXTest.jsx
       7:16  error  'div' is not defined        no-undef
       7:20  error  'className' is not defined  no-undef

Exempting `no-undef` to rules isn't really a viable workaround, I'd like the linter to inform me about those. 

I'm fairly sure babel-eslint is installed correctly, if I remove the "parser" key from `.eshintrc` I get a JS syntax error at the first JSX bracket.

**Comment by sebmck** [comment]
I'll look into it, *should* be an easy fix. I can at least get the `div` not to be logged as undefined.

**Comment by sebmck** [comment]
Should be fixed as of 1.0.11, thanks!

**Comment by joemaller** [comment]
Thanks! Sorry about the late-night autocorrect typos.
