### ISSUE TITLE
Type Annotations and Catch Blocks

### ISSUE THREAD

**Issue by pixelshaded** [babel/babel-eslint#134]
Issue on eslint related to linting angular2 (typescript)
https://github.com/eslint/eslint/issues/2446

I've been trying to use eslint for both typescript and javascript style checking. I know this parser is babel, but it has many simularities with typescript. If I have a try catch where the error in the catch has a type annotation, the parser errors with unexpected token.

```
    try {
      if (arg2.other < 2) {
        arg2.other += 2;
      }
      else {
        arg2.other -= 2;
      }
    }
    catch(error: any) {
      return;
    }
```

I thought this was valid babel code (and typescript).

**Comment by sebmck** [comment]
That's not valid Flow syntax.

**Comment by sebmck** [comment]
Closing this for the aforementioned reason. Whatever TypeScript and Flow syntax do have in common is only a coincidence.

**Comment by pixelshaded** [comment]
https://jsx.github.io/try-on-web/

Look at example 107. I thought this worked with jsx.

**Comment by sebmck** [comment]
That's the wrong JSX. That's a completely separate language that just happens to share the same name to [Facebook's JSX XML extension](https://facebook.github.io/jsx/).

**Comment by pixelshaded** [comment]
Well I totally get why I was confused now. Oy.
