### ISSUE TITLE
Unexpected no-redeclare error inside of comprehension

### ISSUE THREAD

**Issue by alexkuz** [babel/babel-eslint#138]
```
function test() {
  let items;
  return {
    a: [for (i of items) i],
    b: [for (i of items) i]
  };
}
```

the second comprehension emits `no-redeclare` error.

**Comment by hzoo** [comment]
Ah so we would need to create a new scope for each comprehension expression? RIght now it's using the same scope.

**Comment by alexkuz** [comment]
@hzoo take a look (I've added "function" scope to isolate it from parent, not sure if it's right)

**Comment by alexkuz** [comment]
Yay, it works. Thank you!
