### ISSUE TITLE
Isn't '__proto__' allowed by default?

### ISSUE THREAD

**Issue by kuu** [babel/babel-eslint#144]
Accessing '\_\_proto\_\_' causes the following error:
"error  The '\_\_proto\_\_' property is deprecated   no-proto"

I know I could disable this rule in my .eslintrc.
But I expected \_\_proto\_\_ is allowed by default because it's now standard.

Below are my settings:

```js
// package.json:
{
  "devDependencies": {
    "babel": "^5.6.14",
    "babel-eslint": "^3.1.21",
    "eslint": "^0.24.0"
  }
}

// .eslintrc:
{
  "env": {
    "node": true
  },  
  "parser": "babel-eslint",
  "rules": {
    "strict": 0,
    "quotes": [2, "single"]
  }
}
```

**Comment by sebmck** [comment]
This is not a Babel ESLint issue, nor is it an issue with ESLint. Disable that specific rule that's enabled by default.
