### ISSUE TITLE
no-unused-vars with object spread operator

### ISSUE THREAD

**Issue by JohnyDays** [babel/babel-eslint#145]
```javascript
function nonsenseExample (values) {
  return {...values}
}
```
The above example triggers a lint error: ```values is defined but never used```
My code is more complex, but this is the minimal reproducible example for the error.

this post is a followup to eslint/eslint#2929

**Comment by hzoo** [comment]
@JohnyDays This was just reported in https://github.com/babel/babel-eslint/issues/142#issuecomment-118707124 and I just pushed a fix a few minutes ago so try 3.1.22!

**Comment by JohnyDays** [comment]
Thanks! It works perfectly, sorry about the duplicate issue.
