### ISSUE TITLE
Variable in array comprehension causes `block-scoped-var`

### ISSUE THREAD

**Issue by declandewet** [babel/babel-eslint#148]
Caused in this snippet:

```js
function entries(obj) {
  return (for (key of Object.keys(obj)) [key, obj[key]])
}
```

**Comment by hzoo** [comment]
Thanks - will need to do some more escope hacks - not sure at the moment

**Comment by sunjay** [comment]
Any update on this? This problem still occurs for me.

**Comment by sebmck** [comment]
@sunjay Yeah, that's why the issue is still open. :stuck_out_tongue:

**Comment by hzoo** [comment]
Goina close since comprehensions are going to be remove in babel 6 (not on standards track)
