### ISSUE TITLE
Variable is not defined when used in JSX as a parameter

### ISSUE THREAD

**Issue by kompot** [babel/babel-eslint#15]
Given

```javascript
import React from 'react/lib/ReactWithAddons';
import App from './App';

React.initializeTouchEvents(true);
React.render(<App />, document.body);
```

leads to 
```
5:14  error  'App' is not defined  no-undef
```

**Comment by sebmck** [comment]
Can you please verify that this issue still exists on 3.0.1?

**Comment by kompot** [comment]
Not it's 
`2:7   error  App is defined but never used  no-unused-vars`
with babel-eslint 3.0.1 and eslint 0.19.0.

**Comment by sebmck** [comment]
Not sure I can do anything about this. I'd recommend using the [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) rules.

**Comment by kompot** [comment]
Thanks, worked like a charm!
