### ISSUE TITLE
Cannot find module 'object-keys'

### ISSUE THREAD

**Issue by tleunen** [babel/babel-eslint#160]
I keep getting this error on every files with the latest version of babel-eslint:
```
  0:0  error  Cannot find module 'object-keys'
```
I don't use object-keys in my project and it's working fine with eslint. So I guess it's inside babel-eslint or its dependencies?

**Comment by hzoo** [comment]
The only real dependency is babel - you're saying you got this after updating babel-eslint? The last release was a while ago so not sure how this happened.

**Comment by sebmck** [comment]
```
babel-eslint@4.0.5 /Users/sebmck/Projects/babel/eslint
├─┬ babel-core@5.8.21
│ ├─┬ is-integer@1.0.4
│ │ └─┬ is-nan@1.1.0
│ │   └─┬ define-properties@1.1.1
│ │     └── object-keys@1.0.7
```

It's likely your `npm install` just borked. Try clearing `node_modules` and installing them again.

**Comment by tleunen** [comment]
Got this after updating a few globally installed packages. Will try a clean re-install

**Comment by tleunen** [comment]
Seems like @sebmck was right. For some reason, the update of `babel-eslint` was not complete. I fully removed it and re-installed it and problem solved.
