### ISSUE TITLE
eslint 1.1.0 and no-shadow-catch rule

### ISSUE THREAD

**Issue by sublimator** [babel/babel-eslint#162]
eslint version:
`v1.1.0`

source:
```js
'use strict';

function broken() {
  try {
    throw new Error();
  } catch (e) {
    //
  }
}

module.exports = broken;
```

config:
[eslintrc](https://raw.githubusercontent.com/ripple/javascript-style-guide/3cf3cf978839d827218654a2b29462af8309319d/eslintrc)

output:
```
src/broken.js
  6:5  error  Value of 'e' may be overwritten in IE 8 and earlier  no-catch-shadow
```

See: https://github.com/eslint/eslint/issues/3322#issuecomment-129834762

**Comment by hzoo** [comment]
So this can be closed in favor of the fix in eslint https://github.com/eslint/eslint/pull/3360?

**Comment by BYK** [comment]
@hzoo - Looks like it. Sorry for the blame, looks like this has nothing to do with `babel-eslint`.

**Comment by hzoo** [comment]
Ok closing for now!
