### ISSUE TITLE
ESLint crashed: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by 2Pacalypse-** [babel/babel-eslint#172]
Minimum way to reproduce:
- Create file test.js and put this code in:
```
const cats = { persian, siamese, british, bengal }

switch (cats) {
case cats.persian: do_something(); break
}
```

- With this eslintrc file:
```
{
  "parser": "babel-eslint",
  "rules": {
    "no-duplicate-case": 2
  }
}
```

Error: ESLint crashed: Maximum call stack size exceeded

Not sure if ESLint's bug or babel-eslint's one, but it doesn't crash when I use the default parser so I assume it's babel-eslint's bug.
It only crashes when using the object keys in the case (whether you do it by object.key or by object["key"]).

**Comment by hzoo** [comment]
It should be fixed in ESLint 1.2.1
