### ISSUE TITLE
False positive "no-empty"

### ISSUE THREAD

**Issue by jeremejevs** [babel/babel-eslint#183]
[Airbnb config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) (uses `babel-eslint`) flags the `catch` line with `no-empty` for this piece of code:

![test](http://i.imgur.com/7BqIHbJ.png)

Even though [it shouldn't](https://github.com/eslint/eslint/blob/master/lib/rules/no-empty.js#L32). Not sure whose fault is this.

**Comment by hzoo** [comment]
Ok fixed in `4.1.2` - issue with different names for comments - `node.innerComments` and `node.trailingComments`.
