### ISSUE TITLE
no-extra-parens doesn't respect IIFE with async

### ISSUE THREAD

**Issue by zaggino** [babel/babel-eslint#186]
```
(async function () {

}());
```
causes `Gratuitous parentheses around expression  no-extra-parens`
but according to http://eslint.org/docs/rules/no-extra-parens this should not be the case for IIFE

eslint@1.4.3
babel-eslint@4.1.3

**Comment by hzoo** [comment]
This will also probably need to go in https://github.com/babel/eslint-plugin-babel so make an issue there

`no-extra-parens` with IIFE async functions

**Comment by hzoo** [comment]
Moved to https://github.com/babel/eslint-plugin-babel/issues/19
