### ISSUE TITLE
is this project still necessary ?

### ISSUE THREAD

**Issue by Sinewyk** [babel/babel-eslint#188]
according to eslint https://github.com/eslint/eslint#what-about-ecmascript-6-support, they fully support es6/es2015 ... is babel-eslint still necessary ?

**Comment by hzoo** [comment]
Yeah, it's still necessary if you want to lint babel with any newer transforms that babel supports - anything >es2015. If you are only using es6 then you don't need to use it but other people may be using other features that eslint by itself won't support yet - examples: decorators, async/await, etc.

Recent article by @nzakas explains it http://www.smashingmagazine.com/2015/09/eslint-the-next-generation-javascript-linter/#custom-parsers.

**Comment by Sinewyk** [comment]
Yeah, my bad, forgot that babel also transpile es7/es2016 stuff.
