### ISSUE TITLE
"is not defined" when using es7 bind operator

### ISSUE THREAD

**Issue by JeanLebrument** [babel/babel-eslint#191]
Hi,

With the above code I have an error:

```
class Application extends Component {
  state = { displaySideMenu: false };

  openMenu() {
    this.state.displaySideMenu = !this.state.displaySideMenu;
    this.forceUpdate();
  }

  render() {
    return (
      <View style={{flex: 1}}>
        <SideMenuComponent isVisible={this.state.displaySideMenu} />
        <Router firstRoute={firstRoute} headerStyle={styles.headerStyle} customAction={this::openMenu} />
      </View>
    );
  }
}
```

The error: `openMenu is not defined`

If I replace `this::openMenu` by `this.openMenu.bind(this)`, it works.

Any suggestion?

Best,
Jean

**Comment by hzoo** [comment]
Yeah will need to something about escope for that

**Comment by JeanLebrument** [comment]
Thanks for the quick answer!  :+1:

**Comment by hzoo** [comment]
Not sure what we can do but it thinks openMenu is it's own variable rather than `this.openMenu` so it makes sense it's confused

**Comment by JeanLebrument** [comment]
Is there any workaround for this case?

**Comment by hzoo** [comment]
other than disabling the rule for that line not really since it's a new syntax (same with flow, etc)

**Comment by JeanLebrument** [comment]
Ok got it! I will wait for a fix then.

**Comment by fmarsoni** [comment]
I think this::openMenu tries to bind to this a function openMenu, not the class method. So this is not a bug and the linter is right to report that openMenu is not defined.

Try ::this.openMenu

But it's not a good practice to bind inside the render method. This way every time the render method is called you will create a new bound function.

To solve this in a nice way you can use class properties with arrows functions. This way the openMenu method will be bound to this in the class constructor.

```javascript
class Application extends Component {
  state = { displaySideMenu: false };

  openMenu = () => {
    this.state.displaySideMenu = !this.state.displaySideMenu;
    this.forceUpdate();
  }

  render() {
    return (
      <View style={{flex: 1}}>
        <SideMenuComponent isVisible={this.state.displaySideMenu} />
        <Router firstRoute={firstRoute} headerStyle={styles.headerStyle} customAction={this.openMenu} />
      </View>
    );
  }
}
```

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
