### ISSUE TITLE
Syntax error not getting detected for ">=="

### ISSUE THREAD

**Issue by anshulguleria** [babel/babel-eslint#193]
`>==` is not a valid javascript syntax and it does gives error when I am not using __babel-eslint__ parser in `.eslintrc` configuration. But this error is not detected when I use __babel-eslint__ parser.

**Comment by hzoo** [comment]
That would be an issue upstream in babylon/acorn?

**Comment by anshulguleria** [comment]
Probably. How can I verify?

**Comment by hzoo** [comment]
You can try http://astexplorer.net/ with babel-eslint, acorn, babylon or babeljs.io/repl

**Comment by anshulguleria** [comment]
Yeah in http://astexplorer.net/ `>==` is considered valid operator.

**Comment by hzoo** [comment]
Will file it in the babel repo

**Comment by anshulguleria** [comment]
@hzoo Can tell the issue id in babel repo?

**Comment by hzoo** [comment]
https://phabricator.babeljs.io/T2921
