### ISSUE TITLE
Some estraverse modules are left unpatched

### ISSUE THREAD

**Issue by plievone** [babel/babel-eslint#211]
Should all estraverse modules be [monkeypatched](/babel/babel-eslint/blob/0af8736/index.js#L43-L52)? The situation changed a few days ago, when escope pumped to v3.2.1, and updated its estraverse dependency to 4.x. So when eslint is installed via npm 2, there is an extra estraverse 3.x in `eslint/node_modules/escope/node_modules/esrecurse/node_modules/estraverse` which is not found by babel-eslint patcher. Only the following are patched:
`node_modules/eslint/node_modules/estraverse/estraverse.js` (escope uses this and doesn't install own)
`node_modules/eslint/node_modules/estraverse-fb/estraverse-fb.js`

With npm 3, the modules are installed nearer to root, so all estraverses are patched.

Perhaps this is one cause to the `RangeError: Maximum call stack size exceeded` that I was having. I wondered whether it was due to escope using two instances of estraverse and failing some referential equality checks, but it may also be due to babel-eslint not finding all the modules, or some other reason that was triggered by escope v3.2.1 pump.

However, when I upgraded the babel-eslint from 4.0.10 to 4.1.5, the error disappeared. That file under esrecurse is still unpatched, but eslint works. But perhaps that file should be patched too.

**Comment by hzoo** [comment]
I think this is fixed now
