### ISSUE TITLE
babel-eslint 5.0.0-beta4 causes eslint errors

### ISSUE THREAD

**Issue by balupton** [babel/babel-eslint#218]
https://github.com/eslint/eslint/issues/4575

**Comment by hzoo** [comment]
Need to account for [setters/getters](https://github.com/babel/acorn-to-esprima/blob/744f2a986d31700d8e9f24fd5487fb71ab6ca9e0/src/toAST.js#L102-L148)

**Comment by balupton** [comment]
> Need to account for setters/getters

Thanks for the speedy reply!

Is this an instruction for me or the babel-eslint team?

**Comment by hzoo** [comment]
Sorry, yeah it's not clear - that is for me. (We need to account*)

**Comment by hzoo** [comment]
Fixed with https://github.com/babel/acorn-to-esprima/commit/651f5a9369917bb57afbb5fad1a445a88ed6c91f

**Comment by hzoo** [comment]
Published babel-eslint@5.0.0-beta6 which hopefully fixes this.
