### ISSUE TITLE
Problem with `comma-dangle: always-multiline` and flow types

### ISSUE THREAD

**Issue by plievone** [babel/babel-eslint#222]
With eslint 1.10.3 and babel-eslint 4.1.6 or 5.0.0-beta4, the comma-dangle always-multiline rule gets confused in the following case (after `val`):

``` js
function f(
  {a: val}: {
    a: TypeA;
  }
) {}
```

``` sh
$ node_modules/.bin/eslint --no-eslintrc --parser="babel-eslint" --rule="{comma-dangle: [1, always-multiline]}" file.js

  2:10  warning  Missing trailing comma  comma-dangle
```

Multiline case is inferred in eslint's comma-dangle [isMultiline](https://github.com/eslint/eslint/blob/0240af8/lib/rules/comma-dangle.js#L68-L92).

Use case is https://github.com/facebook/relay/blob/288d6a1/src/store/RelayPendingQueryTracker.js#L122

**Comment by hzoo** [comment]
Hi I commented in the PR about this.

At first I thought it was an babel-eslint issue but I think the `comma-dangle` rule may have to be rewritten (maybe through https://github.com/babel/eslint-plugin-babel). The `isMultiline` doesn't account for flow types.

![screen shot 2015-12-08 at 12 08 21 pm](https://cloud.githubusercontent.com/assets/588473/11662398/6a70a25e-9da4-11e5-9304-973488290971.png)

So it looks like a multline which causes the error (without the flow type it's fine since it starts/ends on the same line without it)

What do you think we should do here?

**Comment by plievone** [comment]
Ah ok, so that's how it works. Sorry for not seeing your response and opening issues in separate places, now I see it should have been discussed in `eslint-plugin-babel` where similar kind on issues are tracked. Seems like one needs to have a comma-dangle rule fork there, but it's a pity to maintain it and discover the rule setup for new users. You can move this discussion where you see fit, perhaps it continues at the relay issue where this was found, as people are already listening on it.

**Comment by hzoo** [comment]
Yeah there isn't a way to easily extend a rule as far as I understand so it really is a fork (and I'm not checking if its out of date or anything)

**Comment by nicolo-ribaudo** [comment]
This works with ESLint 6, babel-eslint 10:

```
Documenti/dev/test-babel-eslint is 📦 v1.0.0 via ⬢ v13.2.0 
➜ cat file.js 
function f(
  {a: val}: {
    a: TypeA;
  }
) {}

Documenti/dev/test-babel-eslint is 📦 v1.0.0 via ⬢ v13.2.0 
➜ cat package.json 
{
  "name": "test-babel-eslint",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-eslint": "^10.0.3",
    "eslint": "^6.7.0"
  }
}

Documenti/dev/test-babel-eslint is 📦 v1.0.0 via ⬢ v13.2.0 
➜ node_modules/.bin/eslint --no-eslintrc --parser="babel-eslint" --rule="{comma-dangle: [1, always-multiline]}" file.js

Documenti/dev/test-babel-eslint is 📦 v1.0.0 via ⬢ v13.2.0
```
