### ISSUE TITLE
Invalid .travis.yml configuration

### ISSUE THREAD

**Issue by honzajavorek** [babel/babel-eslint#231]
Accidentally, I recursively ran `travis lint` over all files in my project and got this output:

```
Warnings for node_modules/babel-eslint/.travis.yml:
[x] in node_js section: value io.js is not a valid version
[x] in node_js section: value 4 is not a valid version
[x] in node_js section: value 5 is not a valid version
```

**Comment by hzoo** [comment]
Is it invalid - it looks like it runs fine https://travis-ci.org/babel/babel-eslint/builds/95801616

**Comment by hzoo** [comment]
https://github.com/babel/babel-eslint/commit/038361ac193aa151db9cac6f04cf772793718717
