### ISSUE TITLE
node_modules not ignored by default on Windows

### ISSUE THREAD

**Issue by toas1** [babel/babel-eslint#234]
Hello,

I noticed my linting passes on Linux but it cannot resolve files in node_modules on windows. Seems it's not ignoring node_modules by default on windows. Not sure this is a babel-eslint issues, but since that's the parser i'm using i'm writing here.

**Comment by hzoo** [comment]
This shouldn't be a babel-eslint issue since the parser used shouldn't be affecting what files are being parsed, etc

**Comment by hzoo** [comment]
I would search the ESLint issues again, check their gitter https://gitter.im/eslint/eslint/, or make an issue there
