### ISSUE TITLE
new.target not supported?

### ISSUE THREAD

**Issue by inukshuk** [babel/babel-eslint#235]
I'm getting `no-undef` errors trying to lint ES6 `new.target` with babel-eslint (espree feature 'newTarget'). I guess this is something that must be adressed in babel-eslint?

FWIW, it can be worked around by defining 'new' and 'target' as known globabls.

**Comment by danez** [comment]
Which version of eslint and babel-eslint are you using? I was not able to reproduce this with both tools at the latest version.

I did indeed find a problem in espree, but I think this is unrelated.
eslint/espree#274

**Comment by inukshuk** [comment]
It's fine on the latest version for me as well. Thanks for the follow-up!
