### ISSUE TITLE
Parsing error: Unexpected token for arrow function with flow annotations

### ISSUE THREAD

**Issue by meleyal** [babel/babel-eslint#237]
The following code produces a `Parsing error: Unexpected token` error:
```js
export const MyComponent = (props: Props): ReactElement => {
  ...
}
```

Here's the simplest version that will reproduce the error:
```js
const add = (a: number, b: number): number => a + b;
```

Refs: https://github.com/yannickcr/eslint-plugin-react/issues/390

**Comment by DaleJefferson** [comment]
Example repo to demonstrate issue

```
git clone https://github.com/DaleJefferson/eslint-bug
cd eslint-bug
npm install
npm run lint

/ /1:35  error  Parsing error: Unexpected token
```

**Comment by hzoo** [comment]
Since this is a parsing error, it's an issue with babel/babylon itself (although babel 5). You can try the beta version of babel-eslint

**Comment by DaleJefferson** [comment]
Thanks for the quick reply,

Using babel-eslint 5.0.0-beta6 seems to fix the issue.

```
npm install --save-dev babel-eslint@5.0.0-beta6
```

**Comment by meleyal** [comment]
Yes, `babel-eslint@5.0.0-beta6` fixes the issue, thanks @DaleJefferson, @hzoo.

**Comment by SteliosVoskos** [comment]
And now you can just `npm i -D babel-eslint`  and in the `.eslintrc` file add `"parser": "babel-eslint"`
