### ISSUE TITLE
TypeError: Cannot read property 'visitClass' of undefined

### ISSUE THREAD

**Issue by dan-gamble** [babel/babel-eslint#243]
Eslint version: `1.4.1`, `1.10.3`
`babel-eslint`: `4.1.4`

The error:
```
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/usr/local/lib/node_modules/babel-eslint/index.js:201:40)
    at Object.exports.parse (/usr/local/lib/node_modules/babel-eslint/index.js:374:5)
    at parse (/usr/local/lib/node_modules/eslint/lib/eslint.js:539:27)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:663:19)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:220:27)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:257:18)
    at executeOnFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:600:23)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:624:17
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:622:18)
```

No matter what path i give eslint (`eslint *.js`, `eslint androgenix/assets/js/**/*.js`) i get this error. Not sure where to start looking to fix this. Our old projects seem to work okay but we just started this one and are receiving this error.

**Comment by Havunen** [comment]
same issue.

**Comment by chromakode** [comment]
This appears to be an incompatibility with the recently released escope 3.4.0. Downgrading to 3.3.0 resolved this issue for me.

**Comment by riffraff** [comment]
we are also seeing this as of a couple hours ago, with cli `eslint jsdir -f html -o eslint/eslint.html`

**Comment by dan-gamble** [comment]
@chromakode How do you go about downgrading a packages `escope` package?

**Comment by Havunen** [comment]
npm install --save-dev escope@3.3.0  fixes issue

**Comment by dan-gamble** [comment]
@Havunen I'm still getting the same issue when trying that, tried installing locally and globally (I run eslint off of `-g`)

**Comment by Havunen** [comment]
but thats definitely a work around as my project has no direct dependency to escope

@dan-gamble strange, I just did what @chromakode suggested and it worked for me.

**Comment by chromakode** [comment]
@dan-gamble You may still have a copy of escope 3.4.0 under `node_modules/eslint/node_modules/escope` that is being used. Check `npm ls | grep escope` to list your installed versions, and remove any if necessary.

**Comment by bluejamesbond** [comment]
+1

**Comment by stevesims** [comment]
:+1:

**Comment by stevesims** [comment]
+1

**Comment by gladwearefriends** [comment]
having same error using `babel-eslint`: `4.1.6` with `escope` at `3.3.0`

**Comment by indeyets** [comment]
Upstream issue: https://github.com/estools/escope/issues/99

**Comment by mattdell** [comment]
+1 to @Havunen

**Comment by felipenehmi** [comment]
+1

**Comment by brenopolanski** [comment]
+1

**Comment by rafaferreira** [comment]
+1

**Comment by jwilander** [comment]
+1

**Comment by lprajus2007** [comment]
Guys you can use my fork of @christophehurpeau's fix to install babel-eslint for now (if you're in need of a urgent fix just like me)

npm install git://github.com/lprajus2007/babel-eslint

**Comment by developit** [comment]
@lprajus2007 tip: `npm install lprajus2007/babel-eslint`

**Comment by jmeas** [comment]
Thanks for the fork @lprajus2007 ! I'm going to use that for now.

**Comment by jtheoof** [comment]
Thanks @lprajus2007 doing the same until this issue is fixed.

**Comment by pbeets** [comment]
@lprajus2007 works for me, thanks.

**Comment by hzoo** [comment]
I can push on a fix soon (https://github.com/babel/babel-eslint/pull/244). Sounds like I need to do it for 4.x and 5.x beta?

**Comment by developit** [comment]
@hzoo yes, this is broken for both

**Comment by jmeas** [comment]
> Sounds like I need to do it for 4.x and 5.x beta?

Yup.

**Comment by hzoo** [comment]
Published babel-eslint@5.0.0-beta9

I will move `babel-eslint@5.0.0-beta9` to the `next` tag for npm. and make a new version for babel-eslint 4.

**Comment by htomaka** [comment]
Downgrading to escope 3.3.0 worked for me. Thx

**Comment by jtheoof** [comment]
Thanks @hzoo can you put an update here when you release `4.1.7`?

**Comment by hzoo** [comment]
Ok both are published - let me know if it's good.

`npm view babel-eslint dist-tags`

`{ latest: '4.1.7', next: '5.0.0-beta9' }`

**Comment by rrdelaney** [comment]
:+1: 4.1.7 fixed the issue for me

**Comment by jtheoof** [comment]
:+1: Same here. Thanks.

**Comment by jwilander** [comment]
4.1.7 fix worked for me, thanks!

**Comment by skrobek** [comment]
Same here, 4.1.7  fixed the problem :+1:

**Comment by fkrauthan** [comment]
5.0.0-beta9 is not available via NPM

**Comment by hzoo** [comment]
@fkrauthan I moved it to be on the `next` tag.

`npm i babel-eslint` will be 4.1.7.
Use `npm install --save-dev babel-eslint@next` or `npm i babel-eslint@5.0.0-beta9`

**Comment by fkrauthan** [comment]
Yeah but I get the following error message:
```
npm ERR! No compatible version found: babel-eslint@5.0.0-beta9
npm ERR! Valid install targets:
npm ERR! 5.0.0-beta8, 5.0.0-beta7, 5.0.0-beta6, 5.0.0-beta5, 5.0.0-beta4, 5.0.0-beta3, 5.0.0-beta2, 5.0.0-beta1, 4.1.6, 4.1.5, 4.1.4, 4.1.3, 4.1.2, 4.1.1, 4.1.0, 4.0.10, 4.0.9, 4.0.8, 4.0.7, 4.0.6, 4.0.5, 4.0.4, 4.0.3, 4.0.2, 4.0.1, 4.0.0, 3.1.30, 3.1.29, 3.1.28, 3.1.27, 3.1.26, 3.1.25, 3.1.24, 3.1.23, 3.1.22, 3.1.21, 3.1.20, 3.1.19, 3.1.18, 3.1.17, 3.1.16, 3.1.15, 3.1.14, 3.1.13, 3.1.12, 3.1.11, 3.1.10, 3.1.9, 3.1.8, 3.1.7, 3.1.6, 3.1.5, 3.1.4, 3.1.3, 3.1.1, 3.1.0, 3.0.1, 3.0.0, 2.0.2, 2.0.0, 1.0.14, 1.0.13, 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0
```

**Comment by emmenko** [comment]
`4.1.7` works for me too. Thanks for the quick fix! :+1:

**Comment by hzoo** [comment]
@fkrauthan that is really weird. `babel-eslint@5.0.0-beta9` is definitely showing up for me and is there when I do `npm view babel-eslint`. If I do `npm i babel-eslint@5.0.0-beta10` (not created), I can see beta9 in the valid install targets

**Comment by fkrauthan** [comment]
Hmm maybe a caching issue and it needs a bit more time until it shows up for me?

**Comment by bdefore** [comment]
@fkrauthan it was found by me. i usually use the `min-cache=1000000` trick for speeding up installs, but in this case i had to install without it.

**Comment by fkrauthan** [comment]
@bdefore My bad. Our artifcatory server was caching npm requests. Just cleared the artifactory cache and it was able to pull beta9

**Comment by c0debreaker** [comment]
The solution given above ```npm install --save-dev escope@3.3.0``` also worked for me.

However, on my teammate's setup, it didn't work until I found grunt-eslint also had escope. Told him to uninstall grunt-eslint and reinstall. When I did a cat package.json again on his grunt-eslint, escope is gone. Our app finally worked on this machine.

What is the final solution? Definitely we don't want to go inside each node_modules and installing this kind of fix.

**Comment by hzoo** [comment]
@c0debreaker did you see my post above? https://github.com/babel/babel-eslint/issues/243#issuecomment-178203256

I pushed a new release of babel-eslint on both 4.x and 5.x so just update that and you should be good.

**Comment by klimashkin** [comment]
@hzoo Did you republished beta9? Because we have the same problem with our artifactory - cached beta9 but it's broken!
Maybe you can update to beta10? We can't use eslint because of that whole day

**Comment by fkrauthan** [comment]
@klimashkin Just log into the webinterface of your artifcatory, remove the broken package/invalidate the cache and you should be fine

**Comment by klimashkin** [comment]
@fkrauthan I got it, but it's a really bad practice and it should be done by many many consumers

**Comment by fkrauthan** [comment]
@klimashkin I never got a bad package. My problem was just that artifcatory wasn't contacting npm because of the internal cache timeout. Not much @hzoo can do against that.

**Comment by klimashkin** [comment]
@hzoo can raise version

**Comment by fkrauthan** [comment]
he did with beta9 which is fine.

**Comment by c0debreaker** [comment]
Thanks a lot @hzoo :)

**Comment by nunorafaelrocha** [comment]
4.1.7 works for me. Thanks! :+1:

**Comment by JoaoHenriquePereira** [comment]
:+1: for 4.1.7

**Comment by balaurzor** [comment]
Works on 4.1.7

**Comment by sbhaktha** [comment]
Using `babel-eslint` 4.1.7 or 4.1.8 does not work for me. But downgrading `escope` to 3.3.0 works. I am confused `eslint` 4.1.7 / 4.1.8 worked for others!

**Comment by klimashkin** [comment]
@sbhaktha Try to remove node_modules and do `npm install` again. If doesn't work, check if your company have npm proxy with cache

**Comment by balaurzor** [comment]
Did you install it globally ? Try removing it everything about it (local and global and then do an install)

**Comment by sbhaktha** [comment]
I realized I was depending on another package that take dependency on `babel-eslint` as well, so the version had to be updated there as well. Working on it! Thanks @klimashkin  and @balaurzor.

**Comment by zzz6519003** [comment]
@developit  thx! see you again!

**Comment by scarletsky** [comment]
Same issue here with `eslint 2.1.0` and `babel-eslint 5.0.0`.
I also try `babel-eslint 4.1.8`, but it do not work.

**Comment by frozenfung** [comment]
4.1.7 works for me. Thanks! :+1:

**Comment by radu-arimatrix** [comment]
```
├─┬ babel-eslint@5.0.0-beta9
│ └── acorn-to-esprima@2.0.8
└── eslint@2.4.0
```

Still have this issue:

TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/Users/rtanasescu/Repos/arilove-fe/node_modules/babel-eslint/index.js:201:40)

Can I at least set it to warn?

**Comment by balaurzor** [comment]
maybe you want to update your eslint seing that you are using 5.0 beta9 and the stable version is out

**Comment by radu-arimatrix** [comment]
Using `npm install eslint@2.x babel-eslint@next`(to get the latest versions) I get the exact same error.

```
├── babel-eslint@6.0.0-beta.6
└── eslint@2.4.0
```

```
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/Users/rtanasescu/Repos/arilove-fe/node_modules/babel-eslint/index.js:201:40)
```

**Comment by Arcanemagus** [comment]
@radu-arimatrix You need to be on `babel-eslint@^6.0.0` for support of `eslint@^2.3.0`. (Technically for `eslint@^2.0.0`, but it "sortof" worked in versions before v2.3.0)

**Comment by radu-arimatrix** [comment]
```
├── babel@6.0.0
└── eslint@2.3.0
```
```
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/Users/rtanasescu/Repos/arilove-fe/node_modules/babel-eslint/index.js:201:40)
```
No, still the same error. Thank you to who has invited me to the slack group for the React Program, I'll try to get help there :)

I'm trying to do this with Sublime, would Atom work better?

**Comment by cchamberlain** [comment]
@dan-gamble - Late to the game but I noticed your question on how to change a global packages dependency.  The one-liner is `npm explore eslint -g -- npm i escope@3.3.0` in case you need to do that again. Sort of documented here => https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp
