### ISSUE TITLE
no-used-before-define is erroneously throw when destructuring object with rest operator

### ISSUE THREAD

**Issue by johangirod** [babel/babel-eslint#249]
I think this one is legit :)
### How to reproduce
Using `babel-eslint@5.0.0-beta10`
**.eslintrc**
```json
{
    "parser": "babel-eslint",
    "env": {
        "es6": true,
    },
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true
        },
    },
    "rules": {
        "no-use-before-define": 2,
    }
}
```
**test.js**
```js
const { a, ...b } = { a: 1, b: 2, c:3 };
console.log(a, b);
```

When executing
```shell
$ eslint test.js
```
The linter raise the following error
```
test.js
   2:9   error  'a' was used before it was defined  no-use-before-define
   2:15  error  'b' was used before it was defined  no-use-before-define
```
(nothing appear when using the eslint parser)

**Comment by hzoo** [comment]
Ok probably so. Maybe it was the latest version - can you try beta9?

**Comment by johangirod** [comment]
Still not passing with beta9
The beta8 crashed with :
```
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/Users/johan/Evaneos/testdestruct/node_modules/babel-eslint/index.js:220:40)
    at Object.exports.parse (/Users/johan/Evaneos/testdestruct/node_modules/babel-eslint/index.js:362:5)
    at parse (/Users/johan/Evaneos/testdestruct/node_modules/eslint/lib/eslint.js:574:27)
    at EventEmitter.module.exports.api.verify (/Users/johan/Evaneos/testdestruct/node_modules/eslint/lib/eslint.js:701:19)
    at processText (/Users/johan/Evaneos/testdestruct/node_modules/eslint/lib/cli-engine.js:187:27)
    at processFile (/Users/johan/Evaneos/testdestruct/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/Users/johan/Evaneos/testdestruct/node_modules/eslint/lib/cli-engine.js:602:23)
    at /Users/johan/Evaneos/testdestruct/node_modules/eslint/lib/cli-engine.js:629:17
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/Users/johan/Evaneos/testdestruct/node_modules/eslint/lib/cli-engine.js:624:18)
```

**Comment by mikestopcontinues** [comment]
+1, same results

**Comment by Arcanemagus** [comment]
Looks like this is [an issue](https://circleci.com/gh/AtomLinter/linter-markdown/80) with `eslint@2.0.0` (no beta!).

**Comment by hzoo** [comment]
Ok well we haven't updated anything to eslint 2.0 yet so I'd be surprised if there weren't going to be issues as its a major version update.

**Comment by LKay** [comment]
Any guess when it might be fixed? For now I changed this rule to warning level, but would like to make it more strict as it was before.

**Comment by hzoo** [comment]
PRs are welcome in the meantime

**Comment by jmurzy** [comment]
I believe this is related to eslint/espree#116. 

In short, no-use-before-define fails to skip the ... reference because [escope](https://github.com/estools/escope) fails to identify 'object rest' as a reference.

It works as expected for array literals.

**Comment by gf3** [comment]
for those curious, the ES7 [proposal for the object spread operator is here](https://github.com/sebmarkbage/ecmascript-rest-spread)

**Comment by zyml** [comment]
Seems like acorn-to-esprima and espree are returning different node type names for the rest operator.

Running a test under that code will return the following error:
```
Error: At body.0.declarations.0.id.properties.1.type: are different ("ExperimentalRestProperty" !== "SpreadProperty"):
```

**Comment by hzoo** [comment]
Ah yeah babel is using spreadproperty/restproperty and espree decided to implement experimental syntax with that prefix.

**Comment by zyml** [comment]
Disabling visiting the properties in the ObjectPattern type node seems to work though.
https://github.com/babel/babel-eslint/blob/master/index.js#L321-L332

This causes escope to visit the property nodes as an initialized identifier (init is not defined), causing no-used-before-define rule to complain.

However this will break #95; not an issue for me. :/

**Comment by hzoo** [comment]
@mysticatea Any ideas for this? I'm assuming there's no issue for this with the regular parser now (maybe there is).

Like @zyml mentioned, the code snippet to visit was for #95.

**Comment by mysticatea** [comment]
I quick looked:

```js
const { a, ...b } = { a: 1, b: 2, c:3 };
```

The result of `escope` analysis seems to have a difference.

In `babel-eslint` case, there are 4 references in `scope.references`: `a`, `a`, `b`, `b`. 
On the other hand, in `espree` case, there are 2 references: `a`, `b` (this 2 references is for the initializer).

**Comment by mysticatea** [comment]
I guess the cause might be https://github.com/babel/babel-eslint/blob/master/index.js#L321-L332

**Comment by danez** [comment]
Although I definitively see the value of #95, it is somehow inconsistent that eslint with espree has a different behavior than eslint with babel and I'm leaning more towards removing #95 so that the behavior is the same as with espree.

**Comment by mysticatea** [comment]
As far as I remember, at around #209, `escope` came to handle `SpreadProperty` and `RestProperty` correctly.

**Comment by mysticatea** [comment]
Maybe [this line](https://github.com/babel/babel-eslint/pull/209/files#diff-168726dbe96b3ce427e7fedce31bb0bcR298) is missing?

https://github.com/babel/babel-eslint/commit/0d8953d7a23b35b4a089a81988388fe95642d9ed

Hmm....
