### ISSUE TITLE
Compatibility with babel v6

### ISSUE THREAD

**Issue by gmaclennan** [babel/babel-eslint#256]
Just to clarify, since it is not explicit in the docs, am I right that v5.x is compatible with babel v6? My interpretation from [this comment](https://github.com/babel/babel-eslint/issues/254#issue-133785345) is "yes", but putting this issue here to confirm and give others asking the same question a place to look. It would be good to update the Readme to be explicit about this (just seeing that v5.0 was only finalized 2 days ago, so understandable if docs are not updated yet).

**Comment by hzoo** [comment]
5.x was specifically made to update to babel 6. I wasn't comfortable releasing it so I kept it as a beta, but since people seem to be using it anyway I'm just setting it as 5.x since we need to do an update for eslint 2 as well

**Comment by hzoo** [comment]
Merged https://github.com/babel/babel-eslint/pull/257 atm
