### ISSUE TITLE
npm-registry description "codded"

### ISSUE THREAD

**Issue by alundiak** [babel/babel-eslint#259]
<img width="897" alt="screenshot 2016-02-19 03 06 15" src="https://cloud.githubusercontent.com/assets/2131633/13164473/d9578922-d6b5-11e5-819c-c55fd2f6dec3.png">

**Comment by kaicataldo** [comment]
Is this caused by the Travis build status badge being on the same line as the title?

**Comment by hzoo** [comment]
Totally possible - want to make a PR? :smile:

**Comment by kaicataldo** [comment]
Sure, haha. How do we test that it works on the npm site though?

**Comment by hzoo** [comment]
We just update it and see (not a big deal to test and moving it to the next line doesn't matter much)

If we don't want to do that, then we just use a different project and test it (acutally we can just use https://github.com/hzoo/hzoo-npm-publish haha)

**Comment by kaicataldo** [comment]
Let's see if that fixes it :smile:
