### ISSUE TITLE
`Missing JSDoc comment` after JSX comment

### ISSUE THREAD

**Issue by bob-v-t** [babel/babel-eslint#261]
We use eslint for our React applications and are coming across the following problem: eslint will complain about missing JSDoc comments when JSX comments are added. (`{''}`)

The problem doesn't occur when I replace the babel-eslint version with `4.1.8`.

With the following files you should be able to reproduce the problem.

**package.json** (not sure if you need all the babel packages)

``` json
{
  "name": "MyProject",
  "version": "0.1.0",
  "description": "Showcase problem with ESLint / Babel",
  "main": "src/test.js",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "~6.2.1",
    "babel-eslint": "^5.0.0",
    "babel-loader": "~6.2.0",
    "babel-preset-es2015": "~6.1.18",
    "babel-preset-react": "~6.1.18",
    "eslint": "^1.10.3",
    "eslint-loader": "~1.1.1",
    "eslint-plugin-react": "^3.15.0"
  }
}
```

**.eslintrc**

``` json
{
  "parser": "babel-eslint",
  "root": true,
  "ecmaFeatures":{
    "jsx": true
  },
  "plugins": [
    "react"
  ],
  "env": {
    "browser": true,      // browser global variables.
    "es6": true,         // enable all ECMAScript 6 features except for modul
  },
  "rules": {
    // Require valid JSDoc for all functions and classes
    "require-jsdoc": [1, {
        "require": {
            "FunctionDeclaration": true,
            "MethodDefinition": true,
            "ClassDeclaration": true
        }
    }],
    "valid-jsdoc": [1, {
      "requireReturn": false
    }],
  }
}
```

**src/test.js**:

``` js
import React from 'react';

/**
 * My class declaration
 */
class MyClass extends React.Component {
  /**
   * Renders "Amazing div"!
   * @return JSX
   */
  render() {
    return (
      <div>
        {/* This is the most amazing `div` element in the world! */}
        <div className="most amazing">
        </div>
      </div>
    );
  }
}

export default MyClass;
```

Running eslint will give me the following:

``` sh
$ node ./node_modules/eslint/bin/eslint.js src/test.js

./src/test.js
   6:1  warning  Missing JSDoc comment  require-jsdoc
  11:9  warning  Missing JSDoc comment  require-jsdoc

✖ 2 problems (0 errors, 2 warnings)
```

**Comment by nicolo-ribaudo** [comment]
babel-eslint now matches the [default ESLint parser](https://eslint.org/demo#eyJ0ZXh0IjoiaW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JztcblxuLyoqXG4gKiBNeSBjbGFzcyBkZWNsYXJhdGlvblxuICovXG5jbGFzcyBNeUNsYXNzIGV4dGVuZHMgUmVhY3QuQ29tcG9uZW50IHtcbiAgLyoqXG4gICAqIFJlbmRlcnMgXCJBbWF6aW5nIGRpdlwiIVxuICAgKiBAcmV0dXJuIEpTWFxuICAgKi9cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiAoXG4gICAgICA8ZGl2PlxuICAgICAgICB7LyogVGhpcyBpcyB0aGUgbW9zdCBhbWF6aW5nIGBkaXZgIGVsZW1lbnQgaW4gdGhlIHdvcmxkISAqL31cbiAgICAgICAgPGRpdiBjbGFzc05hbWU9XCJtb3N0IGFtYXppbmdcIj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2Rpdj5cbiAgICApO1xuICB9XG59XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7ImpzeCI6dHJ1ZX19LCJydWxlcyI6eyJyZXF1aXJlLWpzZG9jIjoyLCJ2YWxpZC1qc2RvYyI6Mn0sImVudiI6e319fQ==): 

```
Documenti/dev/test-babel-eslint is 📦 v1.0.0 via ⬢ v13.2.0 
➜ node_modules/.bin/eslint file.js

/home/nicolo/Documenti/dev/test-babel-eslint/file.js
  7:3  warning  Missing JSDoc return type  valid-jsdoc

✖ 1 problem (0 errors, 1 warning)
```
