### ISSUE TITLE
Error with eslint@2.3.0: Cannot find module 'estraverse-fb'

### ISSUE THREAD

**Issue by ryym** [babel/babel-eslint#267]
~~### [Edit by hzoo] - if you are experiencing this error, pin to ESLint 2.2.2.~~
> babel-eslint@5.x.x is for mainly for eslint 1, which is why there's a babel-eslint@6 beta for ESLint 2.

### [Edit by hzoo]: If you are using ESLint 2, use babel-eslint@6.x.x

---

Hi,

When I use babel-eslint with eslint@2.3.0, the following error is thrown. But when I use eslint@2.2.0, the error doesn't occur.

```
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
```

I created a [sample repository] to reproduce this error. To reproduce, please checkout this repository and run `npm install && npm test`.

Environment:

* babel-eslint@5.0.0
* eslint@2.3.0

[sample repository]: https://github.com/ryym/babel-eslint-issue

**Comment by unindented** [comment]
Related: https://github.com/eslint/eslint/issues/5476

**Comment by egoroof** [comment]
Have the same problem. Eslint not working :(

**Comment by hzoo** [comment]
ESLint@2.3.0 removed `estraverse-fb` and also changed how VisitorKeys are used, which babel-eslint patches to support flow, etc so we'll need to wait for an update. For now, you'll have to pin to 2.2.x

**Comment by hzoo** [comment]
Going to just error "Pin to ESLint 2.2.2" so the error is clearer, until this is fixed.

**Comment by budde377** [comment]
:+1:

**Comment by zackify** [comment]
Love it when people break stuff in a minor version.... thanks for the fix!

**Comment by thedark1337** [comment]
Apologies for the reference noise, was trying to fix a travis build error :x:

**Comment by SEAPUNK** [comment]
eslint 2.4.0 has been released just now -- I'll see if babel-eslint works on my end with the update.

**Comment by le0nik** [comment]
Pinned `babel-eslint` to `6.0.0-beta.3`, reinstalled it and `eslint` `2.4.0` and it's working fine for me.

**Comment by ryym** [comment]
> Pinned babel-eslint to 6.0.0-beta.3, reinstalled it and eslint 2.4.0 and it's working fine for me.

It's working fine for me too. But it seems the error still occurs. `6.0.0-beta.3` just catches it and do nothing, while `6.0.0-beta.5` throws the error properly with a kind message:

```
Error: babel-eslint isn't currently compatible with ESLint 2.3.x.
The recommendation is to pin to ESLint 2.2.x right now.
```

**Comment by le0nik** [comment]
@ryym yep, you are right. Didn't notice, that the error gets swallowed in `6.0.0-beta.3`.

Maybe [this](https://twitter.com/geteslint/status/708407623733813249) tweet refers to something else then.

**Comment by camjackson** [comment]
I'm also still getting the error after upgrading to eslint 2.4.0. Unfortunately comments are closed on https://github.com/eslint/eslint/issues/5476.

**Comment by ryym** [comment]
According to https://github.com/eslint/eslint/pull/5543#issuecomment-195963290, ESLint just enables babel-eslint to fix this error. So we need to wait for babel-eslint to update.

**Comment by hzoo** [comment]
Hey everyone, I was out this weekend.

@ryym and others, I would test with babel-eslint@6.0.0-beta.6.

I purposely made the 6.0 beta for compatibility with ESLint 2 (maybe I should just make it out of beta at this point since it seems that a lot of people are still using 5.0)

**Comment by rwjblue** [comment]
@hzoo - We are still using babel 5.x in the ember-cli ecosystem, does babel-eslint@6 require babel 6, or are the versions just coincidentally the same?

**Comment by hzoo** [comment]
Ref https://github.com/babel/babel-eslint/issues/254 (6.x.x for ESLint 2)

It's coincidentally the same, and it's just using babel 6 packages as dependencies rather than babel-core@5.x. It shouldn't matter what the codebase's babel version is technically since all it's doing is parsing your code (if there are issues though let us know). 

Maybe I should be clearer on this (if people aren't having any extra issues from before 2.3.0-2.4.0 with babel-eslint@6 I'll just remove the beta label).

**Comment by rwjblue** [comment]
@hzoo - Thanks for all the hard work on this! I will test in ember-cli-eslint / broccoli-lint-eslint. Will definitely let you know if we run into issues using babel-eslint@6.

**Comment by flekschas** [comment]
I can confirm that the issue is gone using babel-eslint@6.0.0-beta.6 and eslint@2.4.0.

**Comment by jeffijoe** [comment]
Yep, `npm i babel-eslint@next` did it for me.

**Comment by karanjthakkar** [comment]
@hzoo Any place where we can track when babel-eslint@6.x.x comes out of beta?

**Comment by hzoo** [comment]
@karanjthakkar How do you propose we do that - just an issue for it? It's only in been in beta since it was my initial PR for ESLint compatibility.

**Comment by tikotzky** [comment]
I think just opening a checklist issue tracking what still needs to be done to get out of beta should be enough.

Anyone who wants to stay in the loop can then subscribe to that issue.

**Comment by hzoo** [comment]
I don't think there's anything in particular (which probably shows it doesn't need to be in beta at this point I guess)

**Comment by karanjthakkar** [comment]
@hzoo Since its supporting eslint@2.x (which was the reason 6.x was created) and since there aren't any pending tasks that are blocking this change, I would say it should be taken out of beta and a stable major version be released.

**Comment by ryym** [comment]
@hzoo I confirmed babel-eslint@6.0.0-beta.6 doesn't throw the error with ESLint@2.4.0.
Since there are no pending tasks anymore, should I close this issue (or wait for babel-eslint to come out of beta) ?

**Comment by zerkms** [comment]
Guys, how about releasing a v5.0.1 with an `"eslint": "<2.3.0"` as a peer dependency? 

This at least would protect people from installing incompatible versions.

**Comment by ngerritsen** [comment]
Still have the problem with eslint 2.4.0

**Comment by hzoo** [comment]
@zerkms sounds good. Although actually we might as well release it with eslint < 2.0.0 as a peer dependency since its for 1.0

**Comment by tsm91** [comment]
Instead of installing an older eslint version you can just `npm i --save-dev estraverse-fb` and remove it once the issue fixed.

**Comment by hzoo** [comment]
@tsm91 I don't recommend installing estraverse-fb because that just masks other potential errors. You should either stick with an older eslint version or just update to the latest babel-eslint

**Comment by hzoo** [comment]
@zerkms Ok I think i'l release a patch for babel-eslint@5 to use eslint 1.

**Comment by tsm91** [comment]
@hzoo i havent noticed any, yet

**Comment by hzoo** [comment]
If it works for you then great; but I remember finding issues - although it's the nature of the tool (depends on the rules you use and the code you write)

**Comment by hzoo** [comment]
Ok went ahead and made babel-eslint@5.0.1 to have a ESLint 1 peerDependency, and I moved babel-eslint@6 out of beta for ESLint 2!

**Comment by tsm91** [comment]
with [these](https://raw.githubusercontent.com/codewareio/ng2-es-seed/master/.eslintrc#) rules it works

in my  case it broke with an older version, because of an airbnb/base arrow function related rule

**Comment by whatevernot** [comment]
FWIW, I ran into the "Cannot find module 'estraverse-fb'" issue in a project I'm working on. Change to:

devDependencies:
"babel-eslint": "^4.1.8"    --->
"babel-eslint": "^6.0.0"

did the trick for me.
