### ISSUE TITLE
Decorators are marked as unused variables

### ISSUE THREAD

**Issue by johanneslumpe** [babel/babel-eslint#275]
Using eslint 2.4.0 I'm seeing an issue with decorators where the following tells me a variable isn't used:

```js
import Radium from 'radium';

@Radium
export default class Something extends Component {
 /* ... */
}
```

My `.eslintrc`:

```
{
  "extends": "eslint-config-airbnb",
  "env": {
    "node": true,
    "browser": true,
    "mocha": true,
  },

  "globals": {
    "__PRODUCTION__": true,
    "__DEV__": true,
    "__CLIENT__": true,
    "__SERVER__": true
  },

  "plugins": [
    "promise"
  ],

  "parser": "babel-eslint",

  "rules": {
      "promise/param-names": 2,
      "promise/always-return": 2,
      "promise/always-catch": 2
  }
}
```

**Comment by johanneslumpe** [comment]
Yeah I guess this is just an issue with babel-eslint not being compatible with eslint 2.4.0. Closing as that is already a know issue.

**Comment by evenfrost** [comment]
@johanneslumpe Seems the issue is still reproducible with `babel-eslint@6.0.0-beta.6` though [some other verion-related issues](https://github.com/babel/babel-eslint/issues/267#issuecomment-196376577) are gone now. At least I'm still facing it with `eslint@2.4.0`. Mind checking it and reopen the issue if present?

**Comment by jrencz** [comment]
I'm experiencing this issue as well. ESLint 3.19.0, babel-eslint 8.0.0

**Comment by VMBindraban** [comment]
Ditto on ESlint 4.11.0 and 8.0.2.

**Comment by kyovo** [comment]
Try to install ESlint globally, it works for me with v4.14.0

`npm i -g eslint`

**Comment by Rachomir** [comment]
I am having same issue with "standard": "^10.0.3" // "babel-eslint": "^8.2.1",

**Comment by karltaylor** [comment]
+1
