### ISSUE TITLE
Skip ESlint error 'no-use-before-define' with babel-eslint version "^4.1.6" in case with two nested conditions

### ISSUE THREAD

**Issue by helen-dikareva** [babel/babel-eslint#276]
Sample project has 'lint' task.
This task fail with 'no-use-before-define' error when we DO NOT use  "parser": "babel-eslint"

When we use "babel-eslint" this error is skiped.
[sample2.zip](https://github.com/babel/babel-eslint/files/172281/sample2.zip)

**Comment by kaicataldo** [comment]
Hey there, I think it would most likely be helpful if you shared your configuration, the code causing the error, and the exact output from ESLint you're seeing. If you really want to share a full project, a lot of people like to make a GitHub repo that demonstrates the issue.

**Comment by helen-dikareva** [comment]
lint error is 
` sample2\lint.js 4:4  error  '_var' was used before it was defined  no-use-before-define`
And I've created git repo with sample https://github.com/helen-dikareva/sample-for-lint-issue/tree/master

**Comment by kaicataldo** [comment]
Thanks! So you're saying that this SHOULD be flagged when using `babel-eslint` but it's not?

**Comment by kaicataldo** [comment]
Looks like you're using an old version. Can you use the latest versions of `gulp-eslint` and `babel-eslint` see whether the issue exists or not? I'm seeing it warn locally with the latest version of `eslint` and `babel-eslint`.

**Comment by helen-dikareva** [comment]
Old version raise linting error but it should not.
In new version all is well

**Comment by kaicataldo** [comment]
Yeah, it sounds like there's some incompatibility in the older versions. Glad the new versions fixed it! Going to close this now since we found the solution :)
