### ISSUE TITLE
FunctionExpression Identifier node start/end includes type annotation

### ISSUE THREAD

**Issue by gajus** [babel/babel-eslint#277]
> ```js
> export default function (foo: string) {}
> ```
> 
> If you inspect `foo` `Identifier` node, it is:
> 
> ```
> Node {
>   type: 'Identifier',
>   start: 25,
>   end: 36,
>   loc:
>    SourceLocation {
>      start: Position { line: 1, column: 25 },
>      end: Position { line: 1, column: 36 } },
>   name: 'foo',
>   typeAnnotation:
>    Node {
>      type: 'TypeAnnotation',
>      start: 28,
>      end: 36,
>      loc: SourceLocation { start: [Object], end: [Object] },
>      typeAnnotation:
>       Node {
>         type: 'StringTypeAnnotation',
>         start: 30,
>         end: 36,
>         loc: [Object],
>         range: [Object],
>         _babelType: 'StringTypeAnnotation' },
>      range: [ 28, 36 ],
>      _babelType: 'TypeAnnotation' },
>   range: [ 25, 36 ],
>   _babelType: 'Identifier' }
> ```
> 
> Notice that the `node.end` is 36, i.e. it considers that `Identifier` is `foo: string`.
> 
> This is inconsistent with the way `ArrowFunctionExpression` is interpreted, e.g.
> 
> ```js
> export default (foo: string) => {}
> ```
> 
> Here `Identifier` node is:
> 
> ```
> Node {
>   type: 'Identifier',
>   start: 16,
>   end: 19,
>   loc:
>    SourceLocation {
>      start: Position { line: 1, column: 16 },
>      end: Position { line: 1, column: 19 } },
>   name: 'foo',
>   typeAnnotation:
>    Node {
>      type: 'TypeAnnotation',
>      start: 19,
>      end: 27,
>      loc: SourceLocation { start: [Object], end: [Object] },
>      typeAnnotation:
>       Node {
>         type: 'StringTypeAnnotation',
>         start: 21,
>         end: 27,
>         loc: [Object],
>         range: [Object],
>         _babelType: 'StringTypeAnnotation' },
>      range: [ 19, 27 ],
>      _babelType: 'TypeAnnotation' },
>   range: [ 16, 19 ],
>   _babelType: 'Identifier' }
> ```
> 
> Here `node.start` and `node.end` capture only `foo`.
> 
> Behaviour of `ArrowFunctionExpression` appears to be the correct behaviour.

Reference: https://github.com/gajus/eslint-plugin-flowtype/issues/8

**Comment by gajus** [comment]
@hzoo can this be assigned a priority?

**Comment by danez** [comment]
You are right this is inconsistent, but this should be brought up for [babylon](https://github.com/babel/babylon), as babel-eslint uses babylon as ast parser.

**Comment by danez** [comment]
There is a PR now which is going to fix that babel/babylon#57

**Comment by danez** [comment]
This is fixed with latest babylon
