### ISSUE TITLE
Flow interface incorrectly determined to be undefined

### ISSUE THREAD

**Issue by arv** [babel/babel-eslint#279]
Similar to #66 but for interfaces.

```js
// @flow
interface Foo {
  m(): number;
}

export function f(foo: Foo): Foo {
  return foo;
}
```

```
$ npm ls babel-eslint
└── babel-eslint@5.0.0
```

```
$ node_modules/.bin/eslint foo.js

.../foo.js
  2:11  error  "Foo" is not defined  no-undef
  6:24  error  "Foo" is not defined  no-undef
  6:30  error  "Foo" is not defined  no-undef

✖ 3 problems (3 errors, 0 warnings)
```

**Comment by mechanoid** [comment]
Is there any news on that?

**Comment by trevorr** [comment]
Until this is fixed, this workaround is available: https://github.com/zertosh/eslint-plugin-flow-vars

**Comment by hzoo** [comment]
https://github.com/babel/babel-eslint#known-issues - This isn't really something we can fix because there are conflicts between `no-undef` and `no-unused-vars`. We recommend ^ like in the readme
