### ISSUE TITLE
Lib cant parse self calling arrow function

### ISSUE THREAD

**Issue by deser** [babel/babel-eslint#290]
It writes something like "Cant parse ..." when encounters the next code:
() => {console.log(1);}();
Or this
let fn = actions[name] || () => Promise.resolve(null); 
// here I have 64:32  error  Parsing error: Unexpected token   . I think it expects arguments in brackets

**Comment by loganfsmyth** [comment]
It can't parse them because they're invalid :P  You'd need parens:

`(() => {console.log(1);})();`
or
`let fn = actions[name] || (() => Promise.resolve(null)); `

**Comment by deser** [comment]
I don't agree with you. 
This is function expression : 
let fn = actions[name] || () => Promise.resolve(null); 

So find 2 differences with this:
var arr = () => arguments;

This example is described on mozilla dev guides. 
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by loganfsmyth** [comment]
Chrome and Firefox both support arrow functions and will give you errors for the same constructs.

**Comment by deser** [comment]
Oh, I see. Thanks a lot! I have babel 5 on a project and it seems babel 5 transpiles those code successfully. But still I can't understand why it is invalid behavior for arrow function while for ordinary function it is valid. So compare:

1. var fn = false || function() {};  VALID  - this is function expression
2. var fn = false || () => {};  NOT VALID     - and this is function expression 

I tried the following as well:
!()=> {} vs !function() {}

Could anybody explain?

**Comment by hzoo** [comment]
`() => {}` isn't a function expression since it's an arrow function expression and like logan mentioned you need parens?. I guess you'll have to look at the spec

Either way not an issue for babel-eslint - it would be one with babylon (if it is an issue)
