### ISSUE TITLE
max number of errors to report

### ISSUE THREAD

**Issue by tconroy** [babel/babel-eslint#292]
is there a way to configure this so that a finite number of errors/warnings are reported to the console? we're applying this to an existing codebase which has 600+ violations, and all of that dumped into the console on page load makes it very difficult to see what's going on with my non-linting related code. 

is there a way to cap the number of errors reported to the console?

**Comment by hzoo** [comment]
This isn't really a particular issue for babel-eslint, more for the eslint repo itself I would think?
