### ISSUE TITLE
Unable to parse flow tuples of unions 

### ISSUE THREAD

**Issue by ayrton** [babel/babel-eslint#299]
It's currently impossible to parse [flow tuples of unions](http://flowtype.org/docs/builtins.html#literal-types) in eslint. Is this something you plan to support?

**What version of ESLint are you using?**

1.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint 4.1.6

**What did you do? Please include the actual source code causing the issue.**

```js
type Suit =
  | "Diamonds"
  | "Clubs"
  | "Hearts"
  | "Spades";

function result(suit: Suit): string {
  return 'I had: ' + suit;
}

suit('Clubs');
```

**What did you expect to happen?**

To parse the above JS

**What actually happened? Please include the actual, raw output from ESLint.**

```sh
error  Parsing error: Unexpected token
```

**Comment by hzoo** [comment]
babel-eslint uses babylon as the parser. Also this should of been added before in babylon already - I would update to the latest version like mentioned in the readme since you are using 4.x and there's a 6.x now - I think that should work.

**Comment by ayrton** [comment]
I'm working with quite a big codebase, so it will take some time to update the dependencies. Once I do I will come back and report back here!

**Comment by ayrton** [comment]
Confirmed this is in fact working now, thanks!
