### ISSUE TITLE
Update eslint to 2.10.2

### ISSUE THREAD

**Issue by maxm450** [babel/babel-eslint#314]
The new version of `eslint` fixed [this issue](https://github.com/eslint/eslint/issues/6182). An update will be nice so we only need to install `babel-eslint` and not both.

**Comment by jtheoof** [comment]
As you can see in the [package.json](https://github.com/babel/babel-eslint/blob/master/package.json#L37) The `^` indicates to use the major release as well. So all you need to do is `rm -rf node_modules/babel-eslint && npm install`.

**Comment by hzoo** [comment]
it's a devDep in this package and is only for testing. babel-eslint doesn't include eslint.
