### ISSUE TITLE
Error when linting valid async function with generator-star-spacing rule enabled

### ISSUE THREAD

**Issue by doronpr** [babel/babel-eslint#316]
Getting `TypeError: Cannot read property 'value' of undefined` error when linting valid *async function* with `generator-star-spacing` rule enabled.
See minimum reproduce repository example:
https://github.com/doronpr/min-reproduce-eslint-generator-star-spacing

The problem is that `babel-eslint` [creates](https://github.com/babel/babel-eslint/blob/000f4b841efd2b586855a08c789bc93043c1317a/babylon-to-espree/toAST.js#L210) AST with `node.generator == true` for async functions.

I believe that should be changed to `false` but I'm not sure what other implications it can have.

Note that this actually broke in eslint `2.11.0` in [this](https://github.com/doronpr/eslint/commit/9fce04e76dcbae96445e9f6868947aba07d0d662#diff-0893bcac2ba523393aaab76d47c7da39R66) commit (works in `2.10.*`)

The following internal error is thrown:
```
TypeError: Cannot read property 'value' of undefined
    at getStarToken (~/src/min/node_modules/eslint/lib/rules/generator-star-spacing.js:69:25)
    at EventEmitter.checkFunction (~/src/min/node_modules/eslint/lib/rules/generator-star-spacing.js:124:29)
```

**Comment by doronpr** [comment]
Refs: https://github.com/eslint/eslint/issues/6274

**Comment by kaicataldo** [comment]
Are you using the patched version of `generator-star-spacing` from https://github.com/babel/eslint-plugin-babel?

**Comment by lijunle** [comment]
[This workaround](https://github.com/eslint/eslint/issues/6274#issuecomment-228420692) works for me:

```yaml
parser: babel-eslint
extends: airbnb-base
rules:
  generator-star-spacing: 0
```

**Comment by hzoo** [comment]
Just FYI this is because there is a conflict between 2 of the eslint rules such that one of them will alwys be wrong. This will eventually be fixed with https://github.com/babel/babel-eslint/issues/350 when ESLint supports async/await in the default parser and the rule is fixed.

**Comment by tomkel** [comment]
[eslint 3.6.0](http://eslint.org/blog/2016/09/eslint-v3.6.0-released) supports es2017 now

**Comment by hzoo** [comment]
The logic was added to support async/await for different rules with eslint before it was supported -  https://github.com/babel/babel-eslint/issues/361
