### ISSUE TITLE
Dropping Node < 4

### ISSUE THREAD

**Issue by hzoo** [babel/babel-eslint#323]
Given eslint 3.0 will drop it, I guess we should as well as another major version?

https://github.com/eslint/eslint/issues/4483, https://github.com/eslint/eslint/pull/6401

**Comment by kaicataldo** [comment]
Does this involve any code changes on this side? Asking because the ESLint team is talking about starting to use some Node 4 features that we weren't using before.

**Comment by danez** [comment]
I think it will depend on what else changes in eslint 3. If the same version of babel-eslint will work for eslint 2.x and 3.x then we might not do immediately. On the other hand if we have to change some stuff anyway to support (only) 3.x then maybe yes.

**Comment by hzoo** [comment]
Ok we I think we can drop it now since the tests are currently failing on either eslint 2 or eslint 3

**Comment by hzoo** [comment]
Should do a major/drop for https://github.com/babel/eslint-plugin-babel too
