### ISSUE TITLE
babel-eslint error on "declare module.exports: {" flow declaration

### ISSUE THREAD

**Issue by abdes** [babel/babel-eslint#334]
Please also refer to: https://github.com/flowtype/flow-typed/issues/161

In this declaration, used for flow type checking:

https://github.com/flowtype/flow-typed/blob/master/definitions/npm/express_v4.x.x/flow_%3E%3Dv0.25.x/express_v4.x.x.js#L227

Eslint fails with Parsing error: Unexpected token on it. The declaration is correct from flow syntax point of view.

**Comment by danez** [comment]
This was forwarded to babel/babylon#70

**Comment by danharper** [comment]
This was fixed in Babylon v6.9.0 https://github.com/babel/babylon/pull/72
