### ISSUE TITLE
no-redeclare broken for class static props in 6.1.1

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel-eslint#337]
Suddenly after an npm install I got slammed with this, I'm assuming from some semver-compatible update to eslint or something related.  Woohoo.
**this issue is not reproducible (i.e. everything works) with `babel-eslint@6.0.5`**

**What version of ESLint are you using?**
2.13.1
**What parser (default, Babel-ESLint, etc.) are you using?**
6.1.1
**Please show your full configuration:**
babel config
```
{
          "cacheDirectory": true,
          "presets": [
            "es2015",
            "stage-1",
            "react"
          ],
          "plugins": [
            "transform-flow-strip-types",
            "transform-decorators-legacy"
          ]
        }
```
`.eslintrc`
```
{
  "root": true,
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended"
  ],
  "rules": {
    "comma-dangle": 0,
    "strict": 0,
    "no-unused-vars": [1, {"args": "none", "varsIgnorePattern": "React"}],
    "no-console": 1,
    "react/display-name": 0,
    "react/no-unknown-property": 0,
    "react/no-did-mount-set-state": 0,
    "react/prop-types": 0,
    "comma-spacing": 2,
    "eol-last": 2,
    "keyword-spacing": 2,
    "linebreak-style": 2,
    "no-extra-semi": 2,
    "no-trailing-spaces": 2,
    "no-unexpected-multiline": 2,
    "no-unreachable": 2,
    "semi": ["error", "never"],
    "jsx-quotes": 2,
    "react/jsx-boolean-value": [2, "never"],
    "react/jsx-equals-spacing": [2, "never"],
    "react/jsx-closing-bracket-location": 2,
    "react/jsx-curly-spacing": [2, "never"],
    "react/jsx-indent-props": 2,
    "react/jsx-key": 2,
    "react/jsx-space-before-closing": 2
  },
  "env": {
    "meteor": true,
    "browser": true,
    "node": true,
    "es6": true,
    "commonjs": true
  },
  "globals": {
    "Roles": false
  },
  "plugins": [
    "react"
  ]
}
```
**What did you do? Please include the actual source code causing the issue.**
```
import React, {Children, Component, PropTypes, isValidElement, cloneElement} from 'react'
...

class Group extends Component {
  static propTypes = {
    ...
  };
  ...
}

export default class TypicalForm extends Component {
  static propTypes = {
    ...
  };
  ...
}
```
**What did you expect to happen?**
Code should lint just fine, as it was earlier today
**What actually happened? Please include the actual, raw output from ESLint.**
```
ERROR in /Users/andy/jcore-portal/jcore-react-components/common/TypicalForm.jsx

/Users/andy/jcore-portal/jcore-react-components/common/TypicalForm.jsx
  69:10  error  'propTypes' is already defined  no-redeclare

✖ 1 problem (1 error, 0 warnings)
```

**Comment by hzoo** [comment]
I just did an update to fix a different bug https://github.com/babel/babel-eslint/pull/336, so this caused a regression with static properties

**Comment by jedwards1211** [comment]
makes sense

**Comment by jedwards1211** [comment]
I also saw this issue when doing this (assume it's really the same underlying issue):
```js
function validate() { ... }

class MyComponent {
  static validate = validate;
}
```

**Comment by hzoo** [comment]
The config you posted is the babelrc not the eslintrc

**Comment by jedwards1211** [comment]
Oh right, let me fix that...

**Comment by jedwards1211** [comment]
done

**Comment by hzoo** [comment]
I would revert to the previous version for now

https://github.com/babel/babel-eslint/issues/308

```js
function validate() { ... }

class MyComponent {
  static validate = validate;
}
```

is an issue because basically we are defining all class properties automatically. However now there is another variable with the same name so it says it's already defined.

**Comment by jedwards1211** [comment]
@hzoo I'm confused, are you saying that there will be a legitimate no-redeclare error on the `validate` code sample from now on?

**Comment by jedwards1211** [comment]
yes I switched back to 6.0.5 and everything is working fine

**Comment by vjeux** [comment]
@hzoo let me know what you end up doing on this one. We could still do `node._getKey = function() { return node.key; }` which is not pretty but works and should be safe

**Comment by hzoo** [comment]
I think what we need to do is just ignore it similar to how `b` is ignored in `var a = { b: 1 }`, although I'm not sure atm how to do that, @mysticatea maybe you know?

**Comment by mysticatea** [comment]
Yes, escope doesn't make Variable instances for properties.
l think that the rule which checks class properties should be no-dupe-class-members rule. Though the rule has not supported class properties yet.

**Comment by hzoo** [comment]
Class properties are experimental and the rule that is erroring is no-undef and no-redeclare so I think we just need a way to do the same as properties here in babel-eslint

**Comment by mysticatea** [comment]
I'm not familiar with class properties.
But it's properties. We need member expression in order to access properties. Does class properties proposal enhancement the access way of properties?

**Comment by hzoo** [comment]
Sorry, I'm just saying if there a specific api that is used to mark a node type as ignore (like in properties) we can do it for class properties too (like how we call `this.visit(node)` to mark it as used or declare a variable in scope to define it). In this case we want to pretend like it's not there in escope somehow because it's trying to pick it up in scope. It's not really specific to properties so it's more of a question of can we use the escope api to mark the ast node as ignored so the error isn't triggered?

```js
// syntax looks like 
class A {
  prop1;
  prop2 = 'asdf';
  static prop3 = 'asdf';
}
```

ref https://github.com/jeffmo/es-class-fields-and-static-properties

**Comment by mysticatea** [comment]
Ah, I got it. I'm sorry.
So maybe just `ClassProperty` method of escope's `Referencer` is lacking.
I will make a PR.

**Comment by cpunion** [comment]
And another:
```
import { loadData } from './actions'

class A {
  loadData () {
  }
}
```

**Comment by hzoo** [comment]
Check 6.1.2

**Comment by jedwards1211** [comment]
That was fast, thank you guys!
