### ISSUE TITLE
Class properties mess up no-shadow

### ISSUE THREAD

**Issue by steelbrain** [babel/babel-eslint#339]
I'm on ESLint v3.0.1 and Babel-ESLint v6.1.2

The repro code is
```js
class Something {
  something: ?string;
  doSomething() {
    // NOTE: Error after this line saying `something` is already declared in upper scope
    const something = "hello there"
    console.log(something)
    return something
  }
}
```
If we remove that `something: ?string` definition from the class, the error goes away.

I was gonna open this in ESLint but then I thought this was a Flow and therefore parser so opening here, please tell me if I need to open this issue elsewhere

**Comment by danez** [comment]
These seems to be a regression of version 6.1.2 or 6.1.1 where other bugs with class properties were fixed. #338

**Comment by hzoo** [comment]
Weird I thought it wouldn't be declaring anything like a property @mysticatea @vjeux

**Comment by vjeux** [comment]
I have no idea i'm sorry. The repro case seems legit.

**Comment by mysticatea** [comment]
I cannot reproduce this.

![shadow](https://cloud.githubusercontent.com/assets/1937871/16766361/a3fa28b2-4874-11e6-9fe1-917ed7b20559.gif)

**Comment by steelbrain** [comment]
Here's my screenshot, the versions are at the top of the post  
<img src="https://cloud.githubusercontent.com/assets/4278113/16766435/e6795770-47ee-11e6-91c9-344f8173bc03.png">

(the first error on `Something` class is about it being never used and unrelated to this bug)

**Comment by mysticatea** [comment]
To make sure:

- Are both global-installed `babel-eslint` and local-installed `babel-eslint` the latest version?
- Have you restarted your editor after `babel-eslint` was updated?

**Comment by steelbrain** [comment]
I do not have anything globally installed, I install modules locally. and Yes I have restarted both after updating.

I would like to add here that after I nuked `node_modules` folder and reinstalled everything, I no longer see this issue. Thanks everyone. (Amusingly enough the versions of ESLint and Babel-ESLint are still the same 😆 )
