### ISSUE TITLE
Add support for ecmascript-export-default-from with object-curly-spacing: "never"

### ISSUE THREAD

**Issue by mattkrick** [babel/babel-eslint#342]
The problem case: https://github.com/eslint/eslint/issues/6695#issue-165965469 (copied below)

**Please show your full configuration:**
```
"object-curly-spacing": [2, "never"]
```

**What did you do? Please include the actual source code causing the issue.**
```
export Step1 from './Step1';
```
**What did you expect to happen?**
no error

**What actually happened? Please include the actual, raw output from ESLint.**
`There should be no space after 'export'`.
Also, when using `--fix` it corrects it to:

```
exportStep1from './Step1';
```

I think this is based on the stage 1 proposal here: https://github.com/leebyron/ecmascript-export-default-from

**Comment by zaygraveyard** [comment]
Thank you.
It seems you are activating the wrong rule `object-curly-spacing` is the eslint rule and `babel/object-curly-spacing` is the eslint-plugin-babel one.
Let me know if this fixes your issue.

**Comment by mattkrick** [comment]
Yep, that solves it! I didn't even know that babel had a plugin, I just thought they did the parser 🙈 

```
"object-curly-spacing": 0,
"babel/object-curly-spacing": [2, "never"]
```
