### ISSUE TITLE
Parsing error on wrapped flow types

### ISSUE THREAD

**Issue by kylehg** [babel/babel-eslint#348]
I have the following JS

```js
setTimeout((foo: Array<string>)
           : Array<boolean> => {
  return [false]
})
```

And this .eslintrc
```json
{
  "parser": "babel-eslint",
  "rules": {
    "strict": 0
  }
}
```

With `babel-eslint@6.1.2` and `eslint@3.1.1`. This passes `flow@0.28.0` but fails eslint with the error:

```
kylehardgrave@ObvsMBP65:test-babel $ ./node_modules/.bin/eslint test.js

/Users/kylehardgrave/test-babel/test.js
  2:29  error  Parsing error: Unexpected token

✖ 1 problem (1 error, 0 warnings)
```

I saw some other issues here around flow types, but don't think any of them are quite the same.

**Comment by danez** [comment]
Does it work if you move the type on the first line?

**Comment by kylehg** [comment]
Yup, but the point is it shouldn't be a parse error, as it's perfectly valid Flow syntax

**Comment by danez** [comment]
Totally agree, just wanted to make sure.

**Comment by hzoo** [comment]
Ok sounds like this would be a babylon issue then (move to https://github.com/babel/babylon)?
