### ISSUE TITLE
Remove the ast changes for async/await when ESLint supports it

### ISSUE THREAD

**Issue by hzoo** [babel/babel-eslint#350]
https://github.com/babel/babel-eslint/blob/aff95b8a5a0853f6bd8cb9b19cd14d3c202c3dd9/babylon-to-espree/toAST.js#L209-L226

```
    if (path.isFunction()) {
      if (node.async) node.generator = true;
    }

    // await transform to yield
    if (path.isAwaitExpression()) {
      node.type = "YieldExpression";
      node.delegate = node.all;
      delete node.all;
    }
```

Would need to modify the generator star spacing rule so we can also remove it in eslint-plugin-babel

**Comment by tomkel** [comment]
eslint 3.6.0 supports es2017 now

**Comment by hzoo** [comment]
Doing this in https://github.com/babel/babel-eslint/issues/361
