### ISSUE TITLE
Configure which transforms are enabled?

### ISSUE THREAD

**Issue by glenjamin** [babel/babel-eslint#4]
Is this possible at the moment?

**Comment by sebmck** [comment]
Not necessary. Experimental and playground mode are enabled so all valid Babel syntax is linted.

**Comment by glenjamin** [comment]
Right, but what if I want to disallow or disable some transforms? Or is that not a good idea in general?

**Comment by sebmck** [comment]
I'm confused by the question since the transforms are completely irrelevant.

**Comment by glenjamin** [comment]
Well, if I disable the JSX transform for example - I'd want the lint step to tell me I'm using a transform that is disabled?

I might be over-thinking this!

**Comment by sebmck** [comment]
Ah yeah, that's true. Only problem is that ESLint doesn't pass any additional options to the parser so it's either all or nothing.

**Comment by glenjamin** [comment]
They could be treated as syntax errors perhaps? That might be a bit too fiddly though

**Comment by glenjamin** [comment]
Oh, I see what you mean - no way to tell the parser what to do.

**Comment by sebmck** [comment]
Yeah, they'd definently be handled as syntax errors but there's no way to pass on options to `babel-eslint`.

**Comment by nzakas** [comment]
FWIW, custom parsers are still passed the `ecmaFeatures` object: http://eslint.org/docs/configuring/#specifying-language-options

You could key off of that. ESLint doesn't validate the names, so anything you add there will be passed directly through.
