### ISSUE TITLE
`this` inside arrow function as property initializer trips no-invalid-this

### ISSUE THREAD

**Issue by alxndr** [babel/babel-eslint#401]
[A React release announcement from January 2015](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding) includes an example of using an arrow function 

> However, when we have the future property initializers, there is a neat trick that you can use to accomplish this [prebinding instance methods] syntactically:

``` javascript
class Counter extends React.Component {
  tick = () => {
    ...
  }
  ...
}
```

However, using `this` inside such an arrow function appears to trip the `no-invalid-this` rule:

``` shell
$ echo "class Class {\n\tfunc = (foo) => {\n\t\tthis.foo = foo;\n\t}\n}" | ./node_modules/.bin/eslint --parser babel-eslint --stdin --quiet

<text>
  3:3  error  Unexpected 'this'  no-invalid-this

✖ 1 problem (1 error, 0 warnings)
```

(Hoping this belongs here and not in the main eslint project?)

**Comment by aniddan** [comment]
Also: 
```JavaScript
class App extends Component {
   buttons = [
        {
            icon: 'close',
            action: ::this.close // << unexpected this
        }
    ]
}

**Comment by kaicataldo** [comment]
`no-invalid-this` most likely needs to be forked, altered to check this case, and added to https://github.com/babel/eslint-plugin-babel

**Comment by michaelhogg** [comment]
A similar example is given in [React on ES6+](https://babeljs.io/blog/2015/06/07/react-on-es6-plus#arrow-functions):

> by combining two ES6+ features – [arrow functions](https://babeljs.io/docs/learn-es2015/#arrows) and property initializers – opt-in binding to the component instance becomes a breeze:
>
```js
> class PostInfo extends React.Component {
>     handleOptionsButtonClick = (e) => {
>         this.setState({showOptionsModal: true});  // Unexpected 'this'
>     }
> }
```
>
> The body of ES6 arrow functions share the same lexical `this` as the code that surrounds them, which gets us the desired result because of the way that ES7 property initializers are scoped.

**Comment by duro** [comment]
@kaicataldo Has there been any update on this, or alternative approach suggested elsewhere?

**Comment by kaicataldo** [comment]
It looks like it's in eslint-plugin-babel - give that a shot!

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
