### ISSUE TITLE
`\` character inside JSX text flags no-useless-escape

### ISSUE THREAD

**Issue by jrajav** [babel/babel-eslint#414]
Not sure if this is a babel-eslint issue or not, but not sure where else to put it. If you have a `\` character inside of a JSX text node, for instance like so:

`<div>Here it is: \ </div>`

Which is valid and compiles / displays fine, eslint throws an error:

`error    Unnecessary escape character: \   no-useless-escape`

Interestingly enough, it throws the same error at the same spot when the `\` is HTML-encoded as `&#x5C;`.

**Comment by kaicataldo** [comment]
Can you see if this also happens with the default ESLint parser (which also supports JSX)? If so, this is a bug for the `no-useless-escape` rule in ESLint core

**Comment by sstern6** [comment]
@kaicataldo tested locally, this also throws an error with espree.  So looks like its an eslint rule issue.  Will look into it and maybe be able to provide a patch

**Comment by kaicataldo** [comment]
@sstern6 Not that I know of, but I could have missed it. Feel free to make an issue, and thanks for looking into this!

**Comment by sstern6** [comment]
Think i found the issue, will open the Issue on eslint and open a PR shortly.  Will link to both in here when I do to keep track!

Thanks

**Comment by kaicataldo** [comment]
Great, thanks!
