### ISSUE TITLE
for await loop triggers semi rule

### ISSUE THREAD

**Issue by darsain** [babel/babel-eslint#415]
Can't get this to not throw a `Missing semicolon (semi)` error on line `2` (`for await` line):

``` js
async function * foo(generator) {
    for await (const value of generator) {
        yield await value;
    }
}
```

Can't find any info on this. Is it not supported yet? It's a stage-3 candidate proposal, same as async generators, which are parsed properly.

My config:

``` js
{
    "env": {
        "es6": true,
        "node": true
    },
    "parser": "babel-eslint",
    "extends": "eslint:recommended",
    "rules": {
        "semi": ["error", "always"]
    }
}
```

**Comment by kaicataldo** [comment]
Can you provide the actual output from ESLint?

**Comment by loganfsmyth** [comment]
@taion mentioned this on Slack earlier and linked to https://github.com/eslint/eslint/blob/master/lib/rules/semi.js#L190 as the likely cause since this is represented by a new `ForAwaitStatement`.

**Comment by taion** [comment]
See also https://github.com/eslint/eslint/pull/7417. I guess I'll PR it to eslint-plugin-babel if that PR is rejected.

**Comment by kaicataldo** [comment]
Ah, got it. Thanks for the info! @taion sounds like a plan.

**Comment by darsain** [comment]
@taion so the eslint PR got rejected. Could you please redirect it to eslint-plugin-babel? :)

**Comment by cjwatson** [comment]
This was [added](https://github.com/babel/eslint-plugin-babel/pull/126) to eslint-plugin-babel a while back; it's in 4.1.2 and newer.

**Comment by kaicataldo** [comment]
Fantastic! Thanks for the update.
