### ISSUE TITLE
Rule to disallow ES2015 for-of loop

### ISSUE THREAD

**Issue by torarnek** [babel/babel-eslint#417]
It would have been great to have a rule to disallow [for-of-loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of), because [ES2015 for-of transform](http://babeljs.io/docs/plugins/transform-es2015-for-of/) require Symbol.iterator polyfill.

**Comment by hzoo** [comment]
babel-eslint doesn't provide rules since it's just another parser.

You should be able to just rule http://eslint.org/docs/rules/no-restricted-syntax with `ForOfStatement`

**Comment by torarnek** [comment]
I just realised I posted this on the wrong project. Anyways, thank you very much for telling me how to get this feature. I really appreciated your help! :)
