### ISSUE TITLE
Create a CHANGELOG.md file

### ISSUE THREAD

**Issue by basicdays** [babel/babel-eslint#427]
Create a new CHANGELOG.md file to track release notes going forward. This should be structured similarly to Babel's change log.

An example: https://github.com/babel/babel/blob/master/CHANGELOG.md

**Comment by kaicataldo** [comment]
Would definitely be nice to have, though changes are much smaller in scope for this project. For now, feel free to check https://github.com/babel/babel-eslint/releases!

**Comment by b0o** [comment]
Any update on this? Since v9.0.0 was just released, I'm assuming there were some breaking change(s), but can't find a changelog to confirm.

**Comment by existentialism** [comment]
@b0o we'll get a changelog up asap, but FWIW, 9.0.0 was released alongside babel 7.0.0 :)

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
