### ISSUE TITLE
Parsing error since 7.1.1

### ISSUE THREAD

**Issue by JamieDixon** [babel/babel-eslint#428]
Hi there, since upgrading from 7.1.0 to 7.1.1 we've been encountering the following parsing error:

<img width="575" alt="screen shot 2016-12-09 at 19 13 10" src="https://cloud.githubusercontent.com/assets/1519443/21061299/943fe1ec-be43-11e6-9f82-c57a4fb4bd72.png">

from the following function:

```
const getTicksToDisplay = (componentWidth) => {
	const truthMap = {
		[true]: MIN_TICKS_ON_SCREEN,
		[componentWidth > VIEW_LARGE]: MAX_TICKS_XLARGE,
		[componentWidth > VIEW_DESKTOP && componentWidth <= VIEW_LARGE]: MAX_TICKS_LARGE,
		[componentWidth > VIEW_TABLET && componentWidth <= VIEW_DESKTOP]: MAX_TICKS_DESKTOP,
		[componentWidth > VIEW_MOBILE && componentWidth <= VIEW_TABLET]: MAX_TICKS_TABLET,
		[componentWidth <= VIEW_MOBILE]: MAX_TICKS_MOBILE
	};

	return truthMap[true];
};
```

I've tested switching between 7.1.0 and 7.1.1 and it goes from working in 7.1.0 to breaking in 7.1.1. 

Are you able to help with this please? Thanks :)

**Comment by kaicataldo** [comment]
Looks like this is actually a Babylon error. Acorn, Esprima, and Espree parse this without throwing.

**Comment by JamieDixon** [comment]
This has now been raised as an issue with babylon here https://github.com/babel/babylon/issues/264

Thanks for responding @kaicataldo

**Comment by hzoo** [comment]
This was fixed in https://github.com/babel/babylon/pull/266
