### ISSUE TITLE
Support for new flow import type syntax

### ISSUE THREAD

**Issue by jpolo** [babel/babel-eslint#437]
Flow can now import type interposed with regular js import like : 
```javascript
import {
  MyClass,
  type MyType,
} from 'mymodule';
```
At the moment the parser seems to return parse error. It would be good to support this syntax

**Comment by danez** [comment]
This is already supported as of babylon 6.15 and commit https://github.com/babel/babylon/commit/9ea4e9dead015ebf710b58fdefd2b3bc0e50c1ca

Make sure that all your dependencies are up2date.

**Comment by loganfsmyth** [comment]
Looks like your example is missing a comma?

**Comment by jpolo** [comment]
The comma was missing in the example but not in real life ;-), I edited the original post. It seems the bug was caused by the use of two babylon versions differents in the project.

I just fixed with a  ``` yarn upgrade ``` .
