### ISSUE TITLE
New https://github.com/eslint/eslint-scope project

### ISSUE THREAD

**Issue by JamesHenry** [babel/babel-eslint#438]
Hey @hzoo et al 😄 

I just wanted to make sure you are aware that we have officially forked escope at https://github.com/eslint/eslint-scope

There were a couple of reasons for this, but most recently it was not possible to work with the maintainers of escope to accept PRs relating to extensions to ESTree (e.g. for features relating to typeAnnoations)

We will be working to replace escope with eslint-scope in ESLint as part of the next major release (v4).

@nzakas was keen that you guys were aware of that in plenty of time, as I know you currently have to do some funky stuff around scopes in this project.

Please let us know if you have any questions!

**Comment by zertosh** [comment]
@JamesHenry, I'm actively working on rewriting this package so that flow types are perfectly scoped. Not only so that eslint can make better use of the scope info, but also to power other fb tooling that needs type data (e.g.: code generators that need to resolve types). Would you accept a series of PRs in `eslint-scope` that add type annotation support?

**Comment by soda0289** [comment]
@zertosh I have been working on adding type annotation and decorator support to eslint-scope, since typescript would benefit from this as well. If we added type parameter support as well would that cover everything for flow?

**Comment by hzoo** [comment]
@vitorbal updated to eslint-scope in https://github.com/babel/babel-eslint/pull/461 but we should at least update the devDep to check that tests all still pass https://github.com/babel/babel-eslint/blob/1aedb95ef40c5d51223831dfd8be65efbdc27e09/package.json#L40

**Comment by hzoo** [comment]
I think we can close now since we use this as a dep
https://github.com/babel/babel-eslint/blob/bf27f6021e3a3661589bfa1e314f45876edeb20b/package.json#L18
