### ISSUE TITLE
Use Babylon ESTree plugin

### ISSUE THREAD

**Issue by hzoo** [babel/babel-eslint#440]
to remove a lot of the ast hacks that are already done via the plugin.

https://github.com/babel/babylon#output

basically everything in https://github.com/babel/babel-eslint/blob/master/babylon-to-espree/toAST.js

This will make this project a lot simpler and my soul ☺️

**Comment by alxpy** [comment]
Could I work on it?

**Comment by kaicataldo** [comment]
I'd like to work on this!

**Comment by kaicataldo** [comment]
Haven't had the time, unfortunately - if anyone else is interested, please feel free!

**Comment by StGeass** [comment]
Well, then i'd like to take it
