### ISSUE TITLE
no-unused-vars says import type is unused if the type used, used as a default generic in flow

### ISSUE THREAD

**Issue by oriSomething** [babel/babel-eslint#442]
I'm not sure if the correct place of this issue is here or in `eslint-plugin-flowtype`

### The problem:

```js
import type { SomeType } from "./somewhere";

export class SomeClass<T: SomeType> {}

```

ESlint will tell `SomeType` is unused.

### Versions:
- `babel-eslint = 7.1.1`
- `eslint = 3.17.1`
- `eslint-plugin-flowtype = 2.30.3`

If it's something which isn't supposed to be complicated to fix, I can try to submit a PR. Thanks!

**Comment by zertosh** [comment]
Fixed by #449. Though declarations are still broken. Working on that.
