### ISSUE TITLE
How do I parse async/await?

### ISSUE THREAD

**Issue by CrabDude** [babel/babel-eslint#45]
I can't seem to get this to properly parse async/await. I'm getting the following error:
```
'async' is not defined
```

Here's my `.eslintrc`:
```json
{
  "env": {
    "node": true,
  },
  "parser": "babel-eslint"
}
```

Here's the code that fails:
```javascript
async function foo() {}
```

FWIW, there's a `.babelrc` in the same directory:
```json
{
  "experimental": true
}
```

**Comment by CrabDude** [comment]
Hmmm... looks like ATM this may be an issue with how I've configured the SublimeLinter-contrib-eslint since running `eslint foo.js` from the command line succeeds... Will follow-up.

**Comment by CrabDude** [comment]
Alright, it looks like this is probably a problem with SublimeLinter-eslint not supporting the "parser" config option: https://github.com/roadhump/SublimeLinter-eslint/issues/31

**Comment by felixfbecker** [comment]
Same problem with VS Code.

**Comment by sebmck** [comment]
@felixfbecker Not an issue with babel or babel-eslint. VS Code doesn't support async await. I'd recommend taking it up with them.

**Comment by felixfbecker** [comment]
"Same problem" referred to CrabDude's last comment. VS Code supports eslint, but apparently not the parser setting.
