### ISSUE TITLE
TypeError `no-shadow-restricted-names`

### ISSUE THREAD

**Issue by pascalduez** [babel/babel-eslint#47]
```
[...]/node_modules/eslint/lib/rules/no-shadow-restricted-names.js:17
        if (RESTRICTED.indexOf(id.name) > -1) {
                                 ^
TypeError: Cannot read property 'name' of null
    at checkForViolation ([...]/node_modules/eslint/lib/rules/no-shadow-restricted-names.js:17:34)
    at EventEmitter.FunctionDeclaration ([...]/node_modules/eslint/lib/rules/no-shadow-restricted-names.js:39:13)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter ([...]/node_modules/eslint/lib/eslint.js:735:25)
    at Controller.__execute ([...]/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse ([...]/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify ([...]/node_modules/eslint/lib/eslint.js:728:24)
    at processFile ([...]/node_modules/eslint/lib/cli-engine.js:193:27)
    at [...]/node_modules/eslint/lib/cli-engine.js:293:26
    at [...]/node_modules/eslint/lib/util/traverse.js:61:17
```

Linted code: [index.js](https://github.com/pascalduez/postcss-quantity-queries/blob/pseudo-api/lib/index.js)

Chocking on the `export default function ()`.

**Comment by sebmck** [comment]
Can you confirm that this bug is not present in ESLint and that you're
using ESLint 0.16.0 and babel-eslint 2.x?

On Thursday, 12 March 2015, Pascal Duez <notifications@github.com> wrote:

> [...]/node_modules/eslint/lib/rules/no-shadow-restricted-names.js:17
>         if (RESTRICTED.indexOf(id.name) > -1) {
>                                  ^
> TypeError: Cannot read property 'name' of null
>     at checkForViolation ([...]/node_modules/eslint/lib/rules/no-shadow-restricted-names.js:17:34)
>     at EventEmitter.FunctionDeclaration ([...]/node_modules/eslint/lib/rules/no-shadow-restricted-names.js:39:13)
>     at EventEmitter.emit (events.js:129:20)
>     at Controller.controller.traverse.enter ([...]/node_modules/eslint/lib/eslint.js:735:25)
>     at Controller.__execute ([...]/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
>     at Controller.traverse ([...]/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
>     at EventEmitter.module.exports.api.verify ([...]/node_modules/eslint/lib/eslint.js:728:24)
>     at processFile ([...]/node_modules/eslint/lib/cli-engine.js:193:27)
>     at [...]/node_modules/eslint/lib/cli-engine.js:293:26
>     at [...]/node_modules/eslint/lib/util/traverse.js:61:17
>
> Linted code: index.js
> <https://github.com/pascalduez/postcss-quantity-queries/blob/pseudo-api/lib/index.js>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel-eslint/issues/47>.
>


-- 
Sebastian McKenzie

**Comment by pascalduez** [comment]
```
├── babel@4.7.8
├── babel-eslint@2.0.0
├── eslint@0.16.2
```
Not having this issue when I switch to ESlint.

**Comment by pascalduez** [comment]
`export default function foo()` is fine.
