### ISSUE TITLE
linter crash from :: bind operator in JSX

### ISSUE THREAD

**Issue by tsheaff** [babel/babel-eslint#472]
I'm using [this syntax](https://github.com/tc39/proposal-bind-operator):

`::this.foo()`

However, eslint crashes in this case:

```
The prop value with an expression type of BindExpression could not be resolved.
  Please file issue to get this fixed immediately.
Error: The prop value with an expression type of BindExpression could not be resolved.
  Please file issue to get this fixed immediately.
    at Object.extract [as JSXExpressionContainer] (/Users/tsheaff/Code/private/calm/www/node_modules/jsx-ast-utils/lib/values/expressions/index.js:173:11)
    at getValue (/Users/tsheaff/Code/private/calm/www/node_modules/jsx-ast-utils/lib/values/index.js:48:27)
    at extractValue (/Users/tsheaff/Code/private/calm/www/node_modules/jsx-ast-utils/lib/getPropValue.js:24:12)
    at getPropValue (/Users/tsheaff/Code/private/calm/www/node_modules/jsx-ast-utils/lib/getPropValue.js:41:10)
    at /Users/tsheaff/Code/private/calm/www/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js:76:95
    at Array.some (native)
    at EventEmitter.JSXOpeningElement (/Users/tsheaff/Code/private/calm/www/node_modules/eslint-plugin-jsx-a11y/lib/rules/no-static-element-interactions.js:75:52)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/Users/tsheaff/Code/private/calm/www/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/tsheaff/Code/private/calm/www/node_modules/eslint/lib/util/node-event-generator.js:294:22)
```

Here is my `.eslintrc`:

```
module.exports = {
  'env': {
    'browser': true,
    'node': true,
  },
  'plugins': [ 'react' ],
  'parser': 'babel-eslint',
  'extends': 'airbnb', /* see https://github.com/airbnb/javascript */
  'rules': {
    /* override a few airbnb rules */
    'strict': 0,
    'space-before-function-paren': ['error', 'never'],
    'func-names': 'off',
    'no-console': 'error',
    'max-len': 'off',
    'global-require': 'error',
    'consistent-return': 'off',
    'class-methods-use-this': 'off',
    'object-shorthand': ['error', 'never'],
    'no-param-reassign': ['error', {
      'props': false
    }],
    'brace-style': ['error', '1tbs', { allowSingleLine: false }],
    'arrow-parens': ['error', 'always'],
    'arrow-body-style': 'off',
    'import/prefer-default-export': 'off',
    'import/extensions': ['error', {
      'js': 'never',
      'json': 'always'
    }],
  },
}
```

Here are my dependencies:

```
    "babel-eslint": "^7.2.3",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
```

When I remove the `'parser': 'babel-eslint',` line from the config, this crash goes away.  However in that case native eslint doesn't recognize the `::` and says `Parsing error: Unexpected token : (Fatal)` It also goes away if the file I'm linting does not use the `::` syntax

**Comment by kentcdodds** [comment]
I'm still unfamiliar with `babel-eslint` (working on it). But this appears to be an issue `eslint-plugin-jsx-a11y` (at least, that's where the stacktrace is coming from). Could you make a minimal reproduction of this issue in a separate repo? Thanks!

**Comment by tsheaff** [comment]
Thanks for the fast reply @kentcdodds 

This mini-repo recreates the error: https://gist.github.com/tsheaff/003685ca6a163fb467a29fb7c70fbf10

The `::` operator on line [this line](https://gist.github.com/tsheaff/003685ca6a163fb467a29fb7c70fbf10#file-index-js-L16) is the offending one. If I remove that or switch to `.bind(this)` syntax I don't get the error.  I also don't get the error if the `::` is not in JSX

**Comment by hzoo** [comment]
Looks like it doesn't have to do with babel-eslint? Based on the stack trace it's `jsx-ast-utils` which doesn't use babylon (acorn-jsx)

**Comment by tsheaff** [comment]
@hzoo removing `'parser': 'babel-eslint',` from .eslintrc removes error entirely.  It's possible this is just because the `::this.` syntax causes the whole file to look invalid to the parser without eslint, and that `babel-eslint` is thus simply exposing the underlying issue in `jsx-ast-utils`. However, it seems likely that it's the relationship between airbnb (which imports `jsx-ast-utils`) and `babel-eslint` that's causing this.

**Comment by hzoo** [comment]
yeah `eslint` without babel-eslint won't recognize `::`. The reason it's failing is because that rule/plugin is using it's own parsing library that doesn't understand `BindExpression`

**Comment by tsheaff** [comment]
Any possible workaround?  Feels like it should "call out to" the external javascript linter (in this case airbnb + babel-eslint) for the js within jsx...

I'll move the issue to `jsx-ast-utils`

**Comment by hzoo** [comment]
The issue with using new syntax is that all other libraries need to account for it as well (thus babylon/babel-eslint usage in all the other libraries).

The only workarounds are basically what you mentioned: ask them to use babylon as the parser instead (they might say no because they don't want to support that syntax), don't use `::`, or don't use that rule/plugin, or fork

**Comment by tsheaff** [comment]
https://github.com/evcohen/jsx-ast-utils/issues/39

**Comment by hzoo** [comment]
You should mention the reason is that it doesn't account for `::` because it's using acorn-jsx instead of babylon but would need to switch those out if they are willing, and then the rule would need to update it's version of that util

**Comment by tsheaff** [comment]
For posterity: I removed the bind syntax within JSX in my codebase with this hacky regex-replace in Atom:

```
{::this\.([a-zA-Z0-9]+\(?([a-zA-Z0-9']+(,\s))*[a-zA-Z0-9']*\)?)}
{this.$1.bind(this)}
```

This won't work for everyone (for example if you have different bracket spacing or you use snake-case, or other cases I can't think of) but it solved it for my ~350 cases of this across a large repo.

**Comment by hzoo** [comment]
Can make a codemod for this instead, would be safer 😄

**Comment by hzoo** [comment]
And for this one I believe you can just simply use the transform itself as the codemod

https://github.com/square/babel-codemod
