### ISSUE TITLE
RegExpLiteral node needs to have RegExp Object value

### ISSUE THREAD

**Issue by soda0289** [babel/babel-eslint#477]
Currently babel-eslint converts the `RegExpLiteral` to a estree `Literal` with a value of `{}`.
https://github.com/babel/babel-eslint/blob/master/babylon-to-espree/toAST.js#L97

ESLint expects the value to be a RegExp object. This allows it to be casted to a string correctly. It should be `null` when the flags u or y are unsupported.
https://github.com/estree/estree/blob/master/es5.md#regexpliteral

I worked on a fix recently for `typescript-eslint-parser` and can make a fix for this parser as well. It causes the rule `no-dupe-keys` to fail.
https://github.com/eslint/eslint/issues/8655

**Comment by hzoo** [comment]
Sounds good to me, thanks for the report!

Doing https://github.com/babel/babel-eslint/issues/440 should cover it as well
