### ISSUE TITLE
0:0  error  Cannot read property '0' of null on multiple exports

### ISSUE THREAD

**Issue by dshook** [babel/babel-eslint#48]
Geting the error in the title when exporting multiple things from one file:

```
export const c = 'c';

export class Store{
}
```

**Comment by UltCombo** [comment]
The error is reproducible when exporting a single declaration as well:

```js
export let x = 'x';
```

**Comment by UltCombo** [comment]
Looks like the problem is with [this line](https://github.com/babel/babel-eslint/blob/271536d42cb7b3e63831e51f551262966a660eb1/acorn-to-esprima.js#L88), `node.specifiers` is `null`.
