### ISSUE TITLE
arrow-parens ("as-needed") doesn't take async into account

### ISSUE THREAD

**Issue by jlsjonas** [babel/babel-eslint#480]
![image](https://cloud.githubusercontent.com/assets/932193/26732507/1a4d95d8-47b8-11e7-998d-0de2fc050866.png)
automatically gets "fixed" to
![image](https://cloud.githubusercontent.com/assets/932193/26732524/2b339366-47b8-11e7-92b9-b4826d26e02a.png)
which is obviously an error, and causes (during the same fix run) a parsing error on the await keyword further down the code

**Comment by hzoo** [comment]
This is only with babel-eslint? Looks like an ESLint issue (or something is out of date) - check that you are using the latest ESLint/Babel-eslint

**Comment by jlsjonas** [comment]
I checked that I'm using the latest, and how would I use arrow functions with native eslint? (sanity-checked myself... just giving unexpected token =>; so yes, only with babel-eslint)

**Comment by hzoo** [comment]
Oh right it doesn't handle async arrow functions - would need to check if the rule needs to be changed or if babel-eslint needs to change (most likely the former)

**Comment by jlsjonas** [comment]
as it's likely related to the actual rule: [eslint/eslint#8682](https://github.com/eslint/eslint/issues/8682)

**Comment by jlsjonas** [comment]
After some more investigation it is noted that a space between `async` and `(` mitigates the issue, so the rule would have to specifically check for `async`; might be something babel-eslint should/could handle (at least until eslint supports async arrow functions)

**Comment by soda0289** [comment]
I think this is fixed in ESLint v4

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
