### ISSUE TITLE
Update to use Babylon 7 (alpha)

### ISSUE THREAD

**Issue by hzoo** [babel/babel-eslint#481]
Ref https://github.com/babel/babel-eslint/pull/463

This will help us lint the newer proposals only on Babel 7

- [ ] Comment below you are going to do this (for others to know) - we can have multiple people reviewing
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babel-eslint/blob/master/CONTRIBUTING.md) (make sure you have yarn, and are on at least node 4)
- [ ] Join [slack community](https://slack.babeljs.io/) for more immediate help (if people are available)
- [ ] Update the babel packages to 7.0.0-alpha.12 https://github.com/babel/babel-eslint/blob/54ed517d2ecb3afb93ac338c019f8dff224918c2/package.json#L15-L18
- [ ] make tests pass (most likely the node types are different)
  - [ ] if it makes the diffs easier to read we can switch to jest too
- [ ] possibly add new test for new syntax (I can help with this when we get to it)

**Comment by soda0289** [comment]
I can give this a shot.

**Comment by rosskevin** [comment]
I'm desperate for this, it would close #473 and https://github.com/babel/babel/issues/5812
