### ISSUE TITLE
no-unused-vars for jsx

### ISSUE THREAD

**Issue by gpbl** [babel/babel-eslint#5]
First, thank you for babel-eslint: it's like a dream :+1: 

The following code warns for `Router is defined but never used (no-unused-vars)`:

```jsx
import Router from 'react-router';
export default (
  <Router.Route name="app" path="/" />
);
```

It seems happening when using JSX outside a `React.createClass()`. Is there a way to make eslint recognizing the use of the var?

**Comment by gaearon** [comment]
+1, I also have this.

**Comment by sebmck** [comment]
Most of these are easy fixes my laptop shit itself so I won't be able to
fix these for a couple of hours while I get a charger...

On Saturday, 28 February 2015, Dan Abramov <notifications@github.com> wrote:

> +1, I also have this.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel-eslint/issues/5#issuecomment-76455272>.
>


-- 
Sebastian McKenzie

**Comment by sebmck** [comment]
Fixed as of 1.0.8.

**Comment by esnunes** [comment]
sorry but version 1.0.8 of what package?

**Comment by cesarandreu** [comment]
I think I'm having this problem as well.

**.eslintrc**
```json
{
  "parser": "babel-eslint",
  "rules": {
    "strict": false,
    "no-console": false,
    "no-multiple-empty-lines": false
  },
  "env": {
    "mocha": true,
    "browser": true,
    "node": true
  }
}
```

**problem-example.jsx**
```jsx
var Foo = require('./Foo.jsx')
module.exports = <Foo></Foo>

```

**Sublime Text console**
```
SublimeLinter: eslint output:
<text>: line 1, col 4, Error - Foo is defined but never used (no-unused-vars)
<text>: line 2, col 18, Error - 'Foo' is not defined. (no-undef)
```

**terminal**
```sh
$ npm ls -g babel-eslint eslint
/Users/cesarandreu/.nvm/versions/io.js/v1.6.1/lib
├── babel-eslint@2.0.2
└── eslint@0.17.1
```


As part of the Sublime Text console output it also shows it's using the correct eslint binary.

**Comment by frankychung** [comment]
I also had issues with this after eslint 0.17. It seems we should install `eslint-plugin-react` as explained in https://github.com/eslint/eslint/issues/2147. 
With the following:
```
$ npm -g ls eslint eslint-plugin-react babel-eslint
/usr/local/lib
├── babel-eslint@2.0.2
├── eslint@0.17.1
└── eslint-plugin-react@1.6.1
```
And adding the following to my `.eslintrc`
```
{
  ...
  "plugins": [
    "react"
  ],
  ...
  "rules": {
    ...
    "react/jsx-uses-vars": 1
  }
}
```
I no longer get the false warning

**Comment by justin808** [comment]
I've got a similar config and I'm seeing the issue of all the JSX used vars show as not used.

Main difference is eslint@0.18.0.

```
➜  ~/github/react-starter-kit (master u=) npm -g ls eslint eslint-plugin-react babel-eslint
/usr/local/lib
├── babel-eslint@2.0.2
├── eslint@0.18.0
├── eslint-plugin-react@1.6.1
└─┬ standard@3.3.0 (git://github.com/feross/standard#4a2d51eb527bec1a987af9dae57ec8d1d61decaa)
  ├── eslint@0.17.1  (git://github.com/eslint/eslint.git#06927eeacba776c29a40bc0a191f9d9fc9575ba6)
  └── eslint-plugin-react@1.6.1
```

**Comment by garthk** [comment]
Working `.eslintrc` from the subdirectory containing my JSX:

```
{
  "rules": {
    "no-extra-parens": 0,
    "react/jsx-uses-vars": 1
  },
  "ecmaFeatures": {
    "jsx": true,
  },
  "env": {
    "node": false,
    "browser": true,
    "es6": true,
  },
  "parser": "babel-eslint",
  "plugins": [
      "eslint-plugin-react"
  ]
}
```

@sebmck, if you keep getting hassled about JSX e.g. #74, might be worth including some extra notes in the `README`.

**Comment by leongaban** [comment]
Hi all, I'm still getting this error, would anyone mind a look here? https://stackoverflow.com/questions/45085584/how-to-remove-eslint-parsing-error-on-es6-export-statement?noredirect=1#comment77144342_45085584

npm `v3.10.10` node `v6.11.0` eslint `v4.2.0`

**Comment by leongaban** [comment]
A figured it out, it was the last comment here : https://github.com/babel/babel-eslint/issues/6

**Comment by hzoo** [comment]
https://github.com/babel/babel-eslint#known-issues
