### ISSUE TITLE
Parsing error: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by JundongHuangScau** [babel/babel-eslint#510]
import(`./xxx/index.js`).then(component => {
          cb(null, component.default)
        }).catch(err => {
          console.log(`page load error........... ${err}`)
        });

**Comment by ananddodia** [comment]
getting same error in when i add it in route.js file inside getComponent function

**Comment by hzoo** [comment]
babel-eslint handles dynamic import https://github.com/babel/babel-eslint/blob/bf27f6021e3a3661589bfa1e314f45876edeb20b/lib/parse.js#L35 so i would try again on latest version
