### ISSUE TITLE
no-used-before-define fails on destructuring assignment in 8.0.0 

### ISSUE THREAD

**Issue by sybrendotinga** [babel/babel-eslint#517]
After trying to upgrade to 8.0.0 I came across some new errors that never occurred before:

![schermafbeelding 2017-09-15 om 09 50 16](https://user-images.githubusercontent.com/14016492/30472051-512d7344-99fb-11e7-8bd8-96d968768a7a.png)

The code where this happens is:

![schermafbeelding 2017-09-15 om 09 51 19](https://user-images.githubusercontent.com/14016492/30472091-75a02e56-99fb-11e7-9e38-7821a6866e4e.png)

This seems to be related to #249 and https://github.com/eslint/eslint/issues/5135 but the are really old issues, and I couldn't find a solution for this in those topics.

**Versions**
```
eslint version: 4.6.1
babel-eslint version: 8.0.0
```

**.eslintrc**

```
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  env: {
    browser: true,
    node: true,
    es6: true
  },
  extends: [
    'standard',
    'plugin:vue/recommended',
  ],
  plugins: [
    'vue'
  ]
}
```

**Comment by beeplin** [comment]
+1. I got this error too at 8.0.0

**Comment by hzoo** [comment]
Can you try 8.0.2?

**Comment by deltragon** [comment]
8.0.2 works for me.

**Comment by sybrendotinga** [comment]
It is not working for me, but maybe it is related to Vue Single File Components. 

![schermafbeelding 2017-11-07 om 11 58 00](https://user-images.githubusercontent.com/14016492/32490342-1999cb6c-c3b3-11e7-9982-05794772252d.png)

Current versions:

```
    "babel-eslint": "^8.0.2",
    "eslint": "^4.10.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-config-vue": "^2.0.2",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-node": "^5.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "3.13.1",
````

**Comment by beeplin** [comment]
it doesn't work for me either. Still the same error as @sybrendotinga shows above.

**Comment by Bartheleway** [comment]
I have a similar package.json version and have done the same test than you. For me it's working.
Stupid question, sorry to ask, have you ran a `yarn` (or equivalent) after updating your package.json ?

**Comment by beeplin** [comment]
sure I have upgraded it by `yarn`. this error only happens in vue component file, as @sybrendotinga has pointed out.

**Comment by hzoo** [comment]
Yeah it must be only in vue files, which I'm pretty confused about (never had an issue with that before, and definetely haven't thought of a unit test for that yet)

**Comment by throskam** [comment]
https://github.com/vuejs/eslint-plugin-vue/issues/208 solved it for me.

**Comment by hzoo** [comment]
Hmm ok looks like `vue-eslint-parser@2.0.1-beta.2` solves it? Thanks @mysticatea! dono if babel-eslint should have it's own change though

**Comment by beeplin** [comment]
yes it works.
