### ISSUE TITLE
babel-eslintv8.0.0 doesnt support flow types "no-undef" error

### ISSUE THREAD

**Issue by dhanala89** [babel/babel-eslint#520]
Trying to use babel-eslint@8.0.0 with eslint@4.7.1 and for all the flow types I get the above error.  Is there a way I can the latest version of babel-eslint and add support for flow types?

**Comment by hzoo** [comment]
I see this is the same report as https://github.com/babel/babel-eslint/issues/532

Going to close in favor of that, and you need to provide more information (like a code snippet, or better a repo that produces the error for someone to be able to help)
