### ISSUE TITLE
execute babel-macros

### ISSUE THREAD

**Issue by graingert** [babel/babel-eslint#528]
```js
import eval from 'eval.macro'
const foo = 3; // eslint thinks this is unused!
const val = eval('foo * 6')

export default val;
```

what would be better is if babel-eslint were to run the babel-macros transform, and wrap with eslint disable/enable:

```js
import eval from 'eval.macro'
const foo = 3; // eslint thinks this is used!
const val = /* eslint-disable */foo * 6/*eslint-enable*/;

export default val;
```

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
