### ISSUE TITLE
Would you please update the README.md

### ISSUE THREAD

**Issue by dongmei761** [babel/babel-eslint#545]
Just recovered from a problem caused by `babel-eslint not being compatible with eslint` similar to this one https://github.com/babel/babel-eslint/issues/275 and my little suggestion is maybe your `Supported ESLint versions table` in README.md can be updated since ESLint already released ^V4.

**Comment by xtuc** [comment]
Yes, would you mind doing a PR for that?

**Comment by dongmei761** [comment]
@xtuc I'd love to and I encountered the `decorators masked as unused` issue and `undefined static class property` issue on ESLint 4.x/babel-eslint 7.x and everything worked well after I upgraded babel-eslint to 8.x. Will it seem not so strict if I update the `Supported ESLint versions table` and declare that ESLint 4.x should be compatible with babel-eslint >= 8.x?

**Comment by techieshark** [comment]
+1 for making it clear that this is the way to go for using ESLint 4.x (update command as well as table):

`yarn add -D eslint@4.x babel-eslint@8`

**Comment by Rachomir** [comment]
how about standardjs - is there any way to avoid this annoying warning - decorators are marked as unused variables

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
