### ISSUE TITLE
0:0  error  Parsing error: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by Darper** [babel/babel-eslint#546]
Using version ^8.0.1 and started getting this error on every run of eslint after updating node_modules.

`0:0  error  Parsing error: Cannot set property '0' of undefined`

Seems similar to https://github.com/babel/babel-eslint/issues/155

**Comment by mvelebit** [comment]
+1

**Comment by mvelebit** [comment]
+1, thought these were exterminated a while back..

**Comment by jackjwilliams** [comment]
Same here, also getting this error :(

**Comment by VinceBT** [comment]
+1

**Comment by xaphod** [comment]
+1

**Comment by xaphod** [comment]
... and not sure if related:
```
$ yarn install
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["babylon@7.0.0-beta.40"] is trying to unpack in the same destination "/Users/Tim/Library/Caches/Yarn/v1/npm-babylon7-7.0.0-beta.40-91fc8cd56d5eb98b28e6fde41045f2957779940a" as pattern ["babylon@^7.0.0-beta.40"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["babylon7@npm:babylon@^7.0.0-beta"] is trying to unpack in the same destination "/Users/Tim/Library/Caches/Yarn/v1/npm-babylon7-7.0.0-beta.40-91fc8cd56d5eb98b28e6fde41045f2957779940a" as pattern ["babylon@^7.0.0-beta.40"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning "react-native > metro > @babel/plugin-check-constants@7.0.0-beta.38" has incorrect peer dependency "@babel/core@7.0.0-beta.38".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 2.68s.
```

**Comment by ThePeach** [comment]
Having the same problem, as suggested by @xaphod if I remove `"parser": "babel-eslint"` from `.eslintrc` no more errors
I'm not using ES7 feature _yet_ so this is acceptable for the time being, nonetheless this should be addressed somehow

**Comment by ThePeach** [comment]
managed to fix the issue, by starting to use the following in `.eslint`
```
{
  "parser": "babel-eslint",
  "extends": [ "airbnb", "plugin:react/recommended", "prettier", "prettier/react", "prettier/standard" ],
  "plugins": [ "react", "import", "promise", "compat", "prettier" ],
  ...
}

I'm now scared of touching it :P

@xaphod are you able to take a look yourself and validate?

**Comment by xaphod** [comment]
Apologies, i'm in a totally different universe now :(

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
