### ISSUE TITLE
Install babel-eslint as dev-dependency

### ISSUE THREAD

**Issue by saebekassebil** [babel/babel-eslint#55]
In the spirit of keeping all my dependencies in my `package.json` I'd much rather have `babel-eslint` in my `package.json` as a dev-dependency than having to install it `-g`. Reading [eslint's guide](http://eslint.org/docs/user-guide/configuring#specifying-parser) this seems to be possible, but I cannot make it work, and the README instructs to install globally - why?

Cheers

**Comment by Cellule** [comment]
Mostly, it depends on how you run ESlint.
If it is launched from the command line with `$ eslint src` then it will use the one installed globally, which will in turn need the parser to be installed globally.
If you have both `eslint` and `babel-eslint` installed locally then you can make a npm script like
```js
{
  "scripts": { "lint": "eslint src" }
}
```
and then run `$ npm run lint`
This will use the local version of eslint and also it will look locally for your parser.

**Comment by sebmck** [comment]
> the README instructs to install globally - why?

Because most people use eslint via the CLI and it's the easiest way to guarantee that it will work.
