### ISSUE TITLE
wrong no-undef Error

### ISSUE THREAD

**Issue by amgadserry** [babel/babel-eslint#551]
In the following example 
`members.filter(isAdmin = (member) => true)`
eslint fires the following error http://eslint.org/docs/rules/no-undef  'isAdmin' is not defined 
which is a named arrow function not an undefined variable

**Comment by nicolo-ribaudo** [comment]
"Named arrow function" do not exist. You can define the name of an arrow function by assigning it to a variable, so `isAdmin` *is* a variable.

**Comment by amgadserry** [comment]
@nicolo-ribaudo didn't realize that compiler turns this into isAdmin variable missing the var keywork which hoists the variable to the global scope totally my fault thanks for the explanation
