### ISSUE TITLE
Error state is not reset properly in loop

### ISSUE THREAD

**Issue by yeerkkiller1** [babel/babel-eslint#552]
I ran into a specific case where the babel emitted code throws an error repeatedly.

```ts
var failFirst = true;
function flip() {
    return new Promise((resolve, reject) => {
        if(failFirst) {
            failFirst = false;
            reject("first fails");
        } else {
            resolve();
        }
    });
}

async function test() {
    for(var tries = 0; tries < 2; tries++) {
        try {
            try {
                await flip();
            } finally { }
        }
        catch(e) { console.log(e); }
    }
}
test();
```

Expect result (and the result if run directly in chrome):
```
first fails
```

Result from the Babel emitted code (compiled via https://babeljs.io/repl, version 6.26.0, no defaults changed):
```
first fails
first fails
```

It appears that babel is caching the error state, and rethrowing it on subsequent calls of flip, even though only the first call fails.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
