### ISSUE TITLE
v8.2.0 introduces a breaking change

### ISSUE THREAD

**Issue by eddiemonge** [babel/babel-eslint#570]
This version introduced a breaking change that results in this:
```
  1:8  error  Parsing error: This experimental syntax requires enabling the parser plugin: 'exportDefaultFrom'
```

**Comment by hzoo** [comment]
Ah, normally I would ask you to provide more info but I believe we split the plugins so I know the fix. https://github.com/babel/babel/tree/master/packages/babylon#plugins
