### ISSUE TITLE
8.1.2 shows "x is not defined" for Class fields (resolves w/ revert to 8.0.3)

### ISSUE THREAD

**Issue by TamikoT** [babel/babel-eslint#575]
The issue is also described here: https://www.bountysource.com/issues/53126927-parsing-error-couldn-t-resolve-eslint-babel-eslint-8-1-2

**Comment by mysticatea** [comment]
Would you provide a repro step with eslint and babel-eslint?
We have some test cases for `no-undef` rule and class fields:

- https://github.com/babel/babel-eslint/blob/bf27f6021e3a3661589bfa1e314f45876edeb20b/test/non-regression.js#L1736
- https://github.com/babel/babel-eslint/blob/bf27f6021e3a3661589bfa1e314f45876edeb20b/test/non-regression.js#L1766

**Comment by u3u** [comment]
I also encountered the same problem.

```js
export default class Tabs extends React.Component {
  state = { // 'state' is not defined. (no-undef)
    activeKey: null
  }
}
```

```json
"xo": {
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "extends": [
    "rem",
    "xo-react/space"
  ],
  "envs": [
    "node",
    "browser"
  ],
  "rules": {
    "react/react-in-jsx-scope": 0,
    "react/jsx-tag-spacing": 0,
    "react/jsx-one-expression-per-line": 0,
    "react/prop-types": 0,
    "react/no-danger": 0,
    "import/no-extraneous-dependencies": 0,
    "import/no-unresolved": 0
  }
}
```

Use version 8.0.3 is correct.

**Comment by TamikoT** [comment]
Closing since unable to reproduce from scratch.
