### ISSUE TITLE
incorrect token type for negated regexp

### ISSUE THREAD

**Issue by KaelWD** [babel/babel-eslint#576]
See https://github.com/vuejs/eslint-plugin-vue/issues/349

**Original code:**
```js
return (
  // it's inside node_modules
  /node_modules/.test(module.context) &&
  // and not a CSS file (due to extract-text-webpack-plugin limitation)
  !/\.css$/.test(module.request)
)
```

**The token passed into `isComment`:** (it's the `!` before the regexp)
```json
{
  "type": {
    "label": "!",
    "beforeExpr": true,
    "startsExpr": true,
    "rightAssociative": false,
    "isLoop": false,
    "isAssign": false,
    "prefix": true,
    "postfix": false,
    "binop": null,
    "updateContext": null
  },
  "value": "!",
  "start": 963,
  "end": 964,
  "loc": {
    "start": {
      "line": 26,
      "column": 10
    },
    "end": {
      "line": 26,
      "column": 11
    }
  },
  "range": [
    963,
    964
  ]
}
```

> As ESLint AST spec, the type must be a string
&mdash; mysticatea

**Comment by mysticatea** [comment]
Hi, thank you for the report.

I confirmed that I can reproduce it. I'll investigate this.

**Comment by KaelWD** [comment]
Oh, you're actually a member of both. Nice.

**Comment by mysticatea** [comment]
Hmm, I'm suspecting a bug of Babylon (the upstream of `babel-eslint`). It expected `require("babylon").tokTypes.prefix` to match `!` and `~` tokens but not in fact.
