### ISSUE TITLE
is eslint 4 + babel 6 officially supported?

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel-eslint#578]
Seems like `babel-eslint` 8 is only designed to support `eslint` 4 + `babel` 7 beta, but I just wanted to check...

**Comment by swernerx** [comment]
That is probably also related to the bug I experience in mixed babel environments. https://github.com/babel/babel-eslint/issues/585

**Comment by jsg2021** [comment]
its working well for me. my projects are still babel 6.  running eslint 4.19.0 & babel-eslint 8.2.2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by innerdaze** [comment]
This has broken my project as it depends on packages that have been pulled from npm. By you, babel. You pulled them.

**Comment by jsg2021** [comment]
what was pulled?

**Comment by sibelius** [comment]
9 works with babel 7, we can close this

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
