### ISSUE TITLE
Cannot install babel-eslint

### ISSUE THREAD

**Issue by Pfeifenjoy** [babel/babel-eslint#583]
When I try to install babel-eslint I get:

npm ERR! code E404
npm ERR! 404 Not Found: @babel/code-frame@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[name]/.npm/_logs/2018-01-18T18_38_01_464Z-debug.log

**Comment by schoenwaldnils** [comment]
Similar here. I get this line on each file I try to lint:
```
Parsing error: Cannot find module '@babel/code-frame'
```
eslint@4.17.0
babel-eslint@8.2.1

**Comment by nicolo-ribaudo** [comment]
Are you running npm behind a proxy? If yes, can you clear its cache?
Also, can you run `npm cache clean`?

**Comment by Pfeifenjoy** [comment]
I am not running npm behind a proxy. And npm cache clean does not help.
However the error message has changed:

npm ERR! code E404
npm ERR! 404 Not Found: @babel/traverse@7.0.0-beta.36

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-02-05T23_07_09_017Z-debug.log

**Comment by DenRedsky** [comment]
@Pfeifenjoy, i have same issue. 
You can try to use babel-eslint@8.0.0 for now.

**Comment by Pfeifenjoy** [comment]
@DenRedsky Removing data from .npmrc worked.
Thanks 👍
