### ISSUE TITLE
Object spread fails in jsx: "Cannot read property 'expression' of undefined."

### ISSUE THREAD

**Issue by caub** [babel/babel-eslint#587]
`ESLint: Cannot read property 'expression' of undefined. Please see the 'ESLint' output channel for details.`

is outputted by ESLint with for this code:
```jsx
const a = {};
const foo = () => (
	<Link
		to={{
			pathname: '/bar',
			query: { ...a },
		}}
	/>
);
```

config:

```json
{
  "parser": "babel-eslint",
  "extends": [
    "plugin:import/errors",
    "plugin:import/warnings",
    "airbnb"
  ],
  "plugins": [ "babel", "react", "jest" ],
  //...
}
```

versions: (all are latest)
```
"babel-eslint": "^8.2.1",
"eslint": "^4.17.0",
"eslint-plugin-babel": "^4.1.2",
"eslint-plugin-react": "^7.6.1",
```

copy of https://github.com/eslint/eslint/issues/9960 I'm not sure where it belongs yet

**Comment by kafkahw** [comment]
I got exact the same error. The object spread syntax works outside JSX but fails inside it. It seems not solely related to `eslint`. I tried to run `babel` commands to transpile my code and it failed too on the same error.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
