### ISSUE TITLE
Decorators conflicts with no-unused-vars

### ISSUE THREAD

**Issue by hejiaji** [babel/babel-eslint#589]
- 'xxx' is defined but never used(no-unused-var)

The error messages above shows up when i import my decorator and used it in the file.

ESlint version: 3.19.0
babel-eslint version: 4.14.0

Could you give me a hint on this one?

**Comment by artalar** [comment]
Same problem
"eslint": "3.19.0",
"babel-eslint": "8.2.2",

**Comment by Carduelis** [comment]
Same,
eslint@4.18.1,
babel-eslint@8.2.2


 `
 "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 7,
    "sourceType": "module",
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
        "experimentalDecorators": true,
        "jsx": true
    }
  },
"env": {
    "browser": true,
    "node": true,
    "es6": true
  }
}
`

**Comment by hejiaji** [comment]
Don't know why this has been closed without any solution?

**Comment by devlato** [comment]
👍

**Comment by daqo** [comment]
Same problem here:

"babel-eslint": "7.2.3",
"eslint": "^3.19.0"

**Comment by NicholasMiller** [comment]
Seeing with babel-eslint 8.2.2

**Comment by Fridus** [comment]
Hi ! It works for me with `babel-eslint` v8.0.x

```
npm i babel-eslint@8.0
```

**Comment by mstruensee** [comment]
same here, I am getting this error using 8.2.2 
Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead

switching back to 8.0.0 the error goes away ...

**Comment by MicroBenz** [comment]
Same here, even I'm using `babel-eslint` v8.0

**Comment by sercangurbuz** [comment]
Still getting no-unused-vars error/warning for decorators.
`"eslint": "^5.6.0",
"babel-eslint": "^10.0.1", `

**Comment by ganxunzou** [comment]
i have the same problem.
```
"eslint":"5.7.0",
"babel-eslint":"10.0.1"
```

**Comment by Tsury** [comment]
Me too
```
"eslint": "5.9.0",
"babel-eslint": "10.0.1"
```

**Comment by kotgakapainor** [comment]
for me its working now with

```
"babel-eslint": "10.0.1",
"eslint": "5.13.0"
```

**Comment by hardikpthv** [comment]
I also have the same problem.
 
```
"babel-eslint": "^10.0.2",
"eslint": "^5.16.0"
```

**Comment by JosefJezek** [comment]
same issue
```
"babel-eslint": "^10.0.2",
"eslint": "^6.0.1",
```

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
