### ISSUE TITLE
`space-infix-ops` is broken

### ISSUE THREAD

**Issue by Morhaus** [babel/babel-eslint#59]
```
var i = 0, a = 1, b = 2;
console.log(i-a);
console.log(i+a);
console.log(i>a);
console.log(i<a);
console.log(i<=a);
console.log(i>=a);
console.log(i>=a);
console.log(i^a);
console.log(i?a:b);
```

This produces no warnings when using babel-eslint as a parser and the `space-infix-ops` rule.
However, the rule will still produce warnings with operators such as `*`, `=`, `+=`, etc.

**Comment by sebmck** [comment]
Can you please verify that this is still an issue with `babel-eslint` 3.0.0?

**Comment by lukekarrys** [comment]
I was seeing this previous to 3.0.0 and I'm still seeing it with 3.0.1 (and `eslint` 0.19.0. I put together a [quick gist to demonstrate](https://gist.github.com/lukekarrys/1481fc71d78ad2c4ca6f#file-readme-md) if that helps.

**Comment by hzoo** [comment]
Ok I think I figured out the cause for this - will do a PR soon.

Looks like it is because the operators above aren't being set to `Punctuator` as their type. So just got to add some more checks in the `toToken` method - ex: `type === tt.plusMin` for `a+b` and `a-b`.
