### ISSUE TITLE
Support for comments

### ISSUE THREAD

**Issue by Cellule** [babel/babel-eslint#60]
I wanted to use the rule `no-warning-comments`, however the ast doesn't have the comment node when passed to ESLint.
Is there any plan to support comments?
I wanted to try it out myself, but I don't know well enough the ast structure to add node to it. I saw that all the comments are available on `ast.comments`, but are not used in `acornToEsprima`

**Comment by necolas** [comment]
This issue I experienced - https://github.com/eslint/eslint/issues/2211#issue-65785822 - might also be due to babel-eslint altering the comments in the ast.

**Comment by globexdesigns** [comment]
+1

**Comment by globexdesigns** [comment]
Thank you for this!
