### ISSUE TITLE
babel-eslint@8.2.2 / 404 Not Found: babylon@^7.0.0-beta.40

### ISSUE THREAD

**Issue by martinoppitz** [babel/babel-eslint#600]

**Comment by existentialism** [comment]
@martinoppitz thanks for the issue! do you have your own npm cache/registry? It's definitely published:

https://unpkg.com/babylon@7.0.0-beta.40/

**Comment by m1n0s** [comment]
I faced this issue too.

**Comment by thecodejack** [comment]
I am also facing similar issue. Downgrading to 8.0.1 resolved the issue. I am also having internal registry with `nexus`
