### ISSUE TITLE
Use of Nullish Coalescing crashes ESLINT (stops linting completely in VS Code)

### ISSUE THREAD

**Issue by babakness** [babel/babel-eslint#611]
If I use `??` anywhere in a file, babel-eslint gives an obscure "unreachable" error and stops working. Removing the Nullish Coalescing from the file brings it back to life. 

Using babel-eslint 8.2.3

**Comment by aplb** [comment]
Same for me
code
```js
const object = {
  foo: null,
};

console.log('----------', object.foo ?? 'default');
```
deps
```js
"devDependencies": {
    "@babel/cli": "^7.0.0-beta.46",
    "@babel/core": "^7.0.0-beta.46",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0-beta.46",
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1"
  }
```
.babelrc
```js
{
  "plugins": ["@babel/plugin-proposal-nullish-coalescing-operator"]
}
```
.eslintrc
```js
{
  "parser": "babel-eslint",
  "root": true,

  "plugins": [],
  "rules": {
    "comma-dangle": 2
  }
}
```

**Comment by lehni** [comment]
I am seeing the same problem. The problem is not linked to VScode, it also happens when running the linter in the command line:

```sh
$ eslint --ext .js,.vue src
unreachable
Error: unreachable
    at CodePathState.popChoiceContext (…/node_modules/eslint/lib/code-path-analysis/code-path-state.js:444:23)
    at processCodePathToExit (…/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:434:19)
    at CodePathAnalyzer.leaveNode (…/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:9)
    at CodePathAnalyzer.overrideLeaveNode (…/node_modules/eslint-plugin-node/lib/rules/process-exit-as-throw.js:130:27)
    at Traverser.leave [as _leave] (…/node_modules/eslint/lib/linter.js:868:28)
    at Traverser._traverse (…/node_modules/eslint/lib/util/traverser.js:155:18)
    at Traverser._traverse (…/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (…/node_modules/eslint/lib/util/traverser.js:144:34)
    at Traverser._traverse (…/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (…/node_modules/eslint/lib/util/traverser.js:147:30)
error Command failed with exit code 1.
```

**Comment by lehni** [comment]
BTW, if I modify this line:

### `node_modules/eslint/lib/code-path-analysis/code-path-state.js:444:23`: 
```js
        switch (context.kind) {
            case "&&":
            case "||":
```
to:
```js
        switch (context.kind) {
            case "&&":
            case "||":
            case "??":
```

then it works.

**Comment by lehni** [comment]
Some good news:

I upgraded to `"eslint": "^5.0.0-alpha.3"` in my `package.json` file, and this issue went away!

🎉

**Comment by lehni** [comment]
I created a fork with this fix and a couple of others for nullish coalescing:

https://github.com/lehni/eslint-nullish-coalescing
https://github.com/lehni/eslint-nullish-coalescing/commit/ab24b4ba4a7daee71ae7bffc2be7f66355803caf

It's available on NPM as `eslint-nullish-coalescing`.

To prevent peerDependency error messages, it's best to install it alongside the normal `eslint`:

```json
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-nullish-coalescing": "^4.19.1"
  }
```

**Comment by lehni** [comment]
Another update:

The VSCode JS grammar package (`ms-vscode.typescript-javascript-grammar`) struggles with these operators, but `ms-vscode.js-atom-grammar` works well with it. So a temporary fix is to install that package.

**Comment by lehni** [comment]
Update: I'm having the best success with the `mgmcdermott.vscode-language-babel` package for syntax highlighting. The ones mentioned above all had various issues with incorrect parsing of ES7 with stage-1 additions: https://github.com/michaelgmcd/vscode-language-babel

**Comment by Hypnosphi** [comment]
@lehni can you please open a pull request from your fork to eslint repo?

**Comment by lehni** [comment]
@Hypnosphi I didn't do that so far because I was under the impression that this is just a quick fix, not the proper way to go about it... What do you think?

**Comment by lehni** [comment]
What's keeping me from doing so is all the requirements for a PR, see: https://raw.githubusercontent.com/eslint/eslint/master/.github/PULL_REQUEST_TEMPLATE.md

I don't have time for it.

But here's the branch that could be used as a base:

https://github.com/lehni/eslint-nullish-coalescing/tree/nullish-coalescing

The actual changes are tiny:

https://github.com/lehni/eslint-nullish-coalescing/commit/345033232f9f6940c055ef561009c7d1716d3a09

**Comment by lehni** [comment]
Also, my changes are against the `v4.19.1` version, not against `master`, which is heading towards `v5` as we speak.

**Comment by Hypnosphi** [comment]
@lehni Can you please at least sign their CLA so that your changes could be used in [my PR](https://github.com/eslint/eslint/pull/10399)?

https://cla.js.foundation/eslint/eslint?pullRequest=10399

**Comment by lehni** [comment]
@Hypnosphi done! thanks for taking your time to do this.

**Comment by charleschenster** [comment]
for anyone else running into this issue, I was running an older version of eslint (4.19.1). upgrading to the latest version 6.1.0 unblocked me

**Comment by lehni** [comment]
Should this issue be closed then?

**Comment by volaix** [comment]
Is anyone else still having this issue? I've upgraded to `6.1.0` and also the latest of `6.4.0`. Both get the same 'unreachable' error.
```[Error - 9:57:20 am] ESLint stack trace:
[Error - 9:57:20 am] Error: unreachable
    at CodePathState.popChoiceContext (./node_modules/eslint/lib/code-path-analysis/code-path-state.js:444:23)```

**Comment by Haaxor1689** [comment]
I'm having slightly different issue with the same exact problem. I'm running eslint v`6.5.1` and when `??` is used in a file vscode extension reports a crash with different error:

```
[Error - 6:58:03 PM] TypeError: Cannot read property 'range' of null
```

**Comment by lerayne** [comment]
I'm using eslint 6.6.0 and babel-eslint 10.0.3, here's my config:

```
{
  "parser": "babel-eslint",
  "extends": ["standard", "standard-jsx"],
  "rules": {
    "comma-dangle": "off",
    "spaced-comment": "off",
    "react/jsx-boolean-value": "off",
    "react/jsx-closing-bracket-location": [1, "line-aligned"],
    "react/jsx-closing-tag-location": "warn"
  }
}
```

I'm getting error 'Parsing error: Unexpected token, expected ":"' on string
```
return response?.content?.list?[0] ?? false
```

**Comment by Haaxor1689** [comment]
@lerayne this looks like an error related to optional chaining operator which I was getting before installing the `@babel/plugin-proposal-optional-chaining` package. Are you using that package?
