### ISSUE TITLE
Key missing from ObjectTypeProperty ast node

### ISSUE THREAD

**Issue by TheSavior** [babel/babel-eslint#619]
With this input program:
```
type Props = {
  foo1: string
};
```

The `ObjectTypeProperty` which is `foo1: string` is getting parsed into this AST node (with location information removed for brevity):
```
{
  "type": "ObjectTypeProperty",
  "value": {
    "type": "StringTypeAnnotation",
    "_babelType": "StringTypeAnnotation"
  },
  "optional": false,
  "static": false,
  "variance": null,
  "_babelType": "ObjectTypeProperty"
}
```

The key for this node, which should include the name `foo1` is missing. 

With current babylon I get this AST node:
```
{
  "type": "ObjectTypeProperty",
  "key": {
    "type": "Identifier",
    "loc": {
      "identifierName": "foo1"
    },
    "name": "foo1"
  },
  "static": false,
  "kind": "init",
  "value": {
    "type": "StringTypeAnnotation",
  },
  "variance": null,
  "optional": false
}
```

Note that babylon is including the `key` (as well as `kind`).

With current babel-eslint, it appears that there is no way to get `foo1` from the input program. 

cc @yungsters

**Comment by existentialism** [comment]
IIRC this is related to: https://github.com/babel/babel-eslint/issues/307

**Comment by TheSavior** [comment]
Oh no! Old issue!
