### ISSUE TITLE
eslint errors on 'interface' keyword even when using this parser

### ISSUE THREAD

**Issue by jamesqo** [babel/babel-eslint#620]
I have Babel, ESLint, and Flow all being used in my React Native project. My `.eslintrc` looks like this:

```json
{
    "parser": "babel-eslint",
    "env": {
        "browser": false,
        "commonjs": true,
        "es6": true,
        "node": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:flowtype/recommended"
    ],
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "sourceType": "module"
    },
    "plugins": [
        "flowtype",
        "react"
    ],
    "rules": {
        "indent": [
            "error",
            4
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}
```

For some reason, I'm getting an error when I try to declare an interface type in my code:

```js
// [eslint] Parsing error: interface is a reserved word in strict mode
export default interface ApiClient { ... }
```

Not sure why. Could I have setup something wrong?

**Comment by Bundas** [comment]
@AntonioTsai @jamesqo Did you find out?

**Comment by AntonioTsai** [comment]
@Bundas yeah, it is not a bug. `interface` is one of the future reserved keywords according to MDN & ECMA's spec.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Future_reserved_keywords
https://www.ecma-international.org/ecma-262/6.0/#sec-future-reserved-words

**Comment by kaicataldo** [comment]
I think this is expected behavior. It doesn't look like Flow supports default exports of types or interfaces. See [the bottom of this page](https://flow.org/blog/2015/02/18/Import-Types/) for more details. 

You can still export the interface, it just has to be named.

**Comment by kushalmahajan** [comment]
It is a reserved keyword, but one who uses Typescript. What's the solution esp. when eslint runs on pre-commit.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
