### ISSUE TITLE
Parsing error on async generator

### ISSUE THREAD

**Issue by aabfred** [babel/babel-eslint#622]
PLEASE IGNORE: it's eslint related, not babel-eslint

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
