### ISSUE TITLE
Typescript casting error

### ISSUE THREAD

**Issue by blaadje** [babel/babel-eslint#623]
Hi,

as typescript added the `as` casting operator in 1.6 https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#jsx-support

linter is currently throwing 
```js
/home/alex/labs/movieRate/src/containers/ErrorManager/index.tsx
  64:28  error  Parsing error: Unexpected token, expected ","
  62 |
  63 | export default flow(
> 64 |   connect(mapStateToProps) as any     
     |                            ^
  65 | )(ErrorManager)
  66 |
```

Is there anything known about that?

here my .eslintrc conf 

```json
{
  "env": {
    "jest": true
  },
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "standard"
  ]
}
```

**Comment by kaicataldo** [comment]
babel-eslint doesn't currently support TypeScript - see https://github.com/babel/babel-eslint/issues/505

**Comment by blaadje** [comment]
Im using typescript atm and thats the only error i got from the linter with my config :disappointed: (without using decorators)
