### ISSUE TITLE
Monkey patching has compatibility issue

### ISSUE THREAD

**Issue by ishitatsuyuki** [babel/babel-eslint#626]
This line:

https://github.com/babel/babel-eslint/blob/e4bed5a4d5757b44d145d683a2f5aaa28a4f96ef/lib/patch-eslint-scope.js#L36

attempts to require estraverse on eslint's behalf, but estraverse is not a direct dependency of eslint. This causes issues with pnpm, which uses the tree-style node_modules tree.

Possible solution: correctly traverse the dependency tree (eslint -> eslint-scope -> estraverse).

**Comment by nwalters512** [comment]
This broke for me as well. In my case, another dependency was requiring a much older version of `estraverse`, which is what got resolved here. `babel-eslint` then attempted to monkey-path a property that didn't exist, which caused a lot of linting errors. This dependency was removed from `eslint` in 4.14.0, so downgrading to 4.13.1 has temporarily fixed this issue for us.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
