### ISSUE TITLE
Cannot read property 'local' of undefined

### ISSUE THREAD

**Issue by daviddelusenet** [babel/babel-eslint#628]
Please check out this issue (and the issues mentioned in the threat): https://github.com/eslint/eslint/issues/10443

This might be a babel-eslint bug (based on what I read in the other similar issue).

**Comment by daviddelusenet** [comment]
This looks like a similar issue: https://github.com/eslint/eslint/issues/9872

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
