### ISSUE TITLE
There is no way to enable Babel's decoratorsBeforeExport option (see babel-plugin-proposal-decorators)

### ISSUE THREAD

**Issue by jjinux** [babel/babel-eslint#635]
As far as I can tell, there's no way to enable the decoratorsBeforeExport option from babel-plugin-proposal-decorators. Furthermore, since the library is currently using babylon 7.0.0-beta.44, it won't work because we need to switch to a newer version of the Babel parser. My understanding is that we need @babel/parser 7.0.0-beta.48 which adds support for decoratorsBeforeExport. As far as I can tell looking at the code, there's also no way to pass any options to the Babel parser.

**Comment by jjinux** [comment]
Hmm, perhaps I can pass the option via parserOptions. I still think that we need a newer version of the parser.

**Comment by existentialism** [comment]
@jjinux there's currently a PR that bumps it to latest over at https://github.com/babel/babel-eslint/pull/627

**Comment by jjinux** [comment]
This issue is resolved thanks to #627.

**Comment by jjinux** [comment]
> Hmm, perhaps I can pass the option via parserOptions. I still think that we need a newer version of the parser.

It works without any additional configuration.

**Comment by h4emp3** [comment]
I can't really tell if this actually worked after the above mentioned issue was fixed, but in 45938d9a280186ea0eb9571e5797a13fb624b375 this option was harcoded to false, I would very much like it to be configurable.
