### ISSUE TITLE
Regression in v8.2.4+ / v9.0.0.beta: optional chaining without assignments trigger no-unused-expressions

### ISSUE THREAD

**Issue by lehni** [babel/babel-eslint#643]
Unfortunately, #595 didn't solve all issues with optional chaining for me, or new ones got introduced in the meantime. While some uses of optional chaining seem to work now, others are causing new linting errors with v8.2.4 and v8.2.5:

```
error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
```

The statement in question is:

```js
this.element?.destroy()
```

v8.2.1 is still the last version that I am able to use for optional chaining

**Comment by lehni** [comment]
The same problem also occurs in 9.0.0-beta.2

**Comment by lehni** [comment]
This is also still happening in v8.2.6

**Comment by lehni** [comment]
@existentialism may I point out this issue here that's still happening with optional chaining? I believe this only happens when optional chaining is used outside of an assignment. As soon as I turn the above statement into an assignment, optional chaining works:

```js
const res = this.element?.destroy()
```

**Comment by macrozone** [comment]
even with assigments i get this error:

<img width="277" alt="bildschirmfoto 2018-08-30 um 13 12 08" src="https://user-images.githubusercontent.com/1972353/44848252-564f4280-ac56-11e8-9994-ab676f508920.png">

**Comment by lehni** [comment]
I guess assignments without `=` do this?

**Comment by lehni** [comment]
It's a shame that this made it into 9.0.0 without a fix... @rubennorte since you knew how to fix #595 / #630, perhaps you could take a look at this issue?

**Comment by MrCreeper1008** [comment]
```no-unused-expressions``` is also triggered when chaining promises with ```.then?.()```.

**Comment by MrCreeper1008** [comment]
**Here is a test snippet:**
![snippet](https://user-images.githubusercontent.com/19359984/44907183-b07d0000-ad49-11e8-94c3-50e84a7889d7.png)

**The error:**
![snippet with error](https://user-images.githubusercontent.com/19359984/44907184-b07d0000-ad49-11e8-8f46-d60c06be696c.png)

**Comment by MrCreeper1008** [comment]
Sorry for the syntax error, but the error appears in either case.
![new spinnet](https://user-images.githubusercontent.com/19359984/44907705-6e54be00-ad4b-11e8-9e2b-a9e76d63a850.png)

**Comment by kaicataldo** [comment]
The fix for this is most likely in the forked version of `no-unused-expressions` in [https://github.com/babel/eslint-plugin-babel](esling-plugin-babel).

**Comment by remhume** [comment]
Not sure what you mean with forked version @kaicataldo. The link href is broken, but the actual eslint-plugin-babel repo (link text) also does not seem to use a forked version of babel-eslint.
It actually uses 8.2.2 on master, which was of course before the regression happened.

**Comment by lehni** [comment]
It's this file here: https://github.com/babel/eslint-plugin-babel/blob/master/rules/no-unused-expressions.js

**Comment by kaicataldo** [comment]
Sorry for the typo in the link. @lehni has the correct one!

**Comment by lehni** [comment]
@kaicataldo but what's this file forked from?

**Comment by lehni** [comment]
Looking at this more closely, it looks like it's not so much forking code. It's extending the rules contained in this:

https://github.com/eslint/eslint/blob/master/lib/rules/no-unused-expressions.js

**Comment by lehni** [comment]
Ok, I think I've figured this out now:

1. By default `babel-eslint` doesn't support such language editions. There is the plugin `eslint-plugin-babel`, which provides rules that replace the default ones, but those aren't loaded by default. You have to add the plugin as outlined [here](https://github.com/babel/eslint-plugin-babel#install), and then you need to replace the default rules with these `babel/*` versions.

2. When not doing so, the default rules from eslint are used, as linked to above, which definitely do not support `OptionalCallExpression`.

3. Even when doing so, this currently still fails. 

4. Solution: https://github.com/babel/eslint-plugin-babel/pull/158

Fingers crossed for this getting merged soon.

**Comment by lehni** [comment]
If you can't wait for the release, you can already use it now:

### `package.json`
```js
  "devDependencies": {
    ...
    "eslint-plugin-babel": "github:lehni/eslint-plugin-babel#d0f79527a2b282fe9d05f6f0398b5c869d6077e8",
    ...
  }
```

### `.eslintrc.js`
```js
module.exports = {
  plugins: [
    'babel'
  ],
  rules: {
    ...
    // https://github.com/babel/eslint-plugin-babel/pull/158
    'no-unused-expressions': 'off',
    'babel/no-unused-expressions': 'error',
    ...
  }
}
```

**Comment by lehni** [comment]
Update: eslint-plugin-babel v5.2.0 is out now, with the above fix merged in. 🎉
