### ISSUE TITLE
can not recognize JSX syntax with babel-core 5.0

### ISSUE THREAD

**Issue by airwin** [babel/babel-eslint#65]
I updated babel to 5.0 then found babel-eslint report the JSX syntax such as '<div' as an error ‘Unexpected token’, is there a solution now? Thank you!

**Comment by sebmck** [comment]
babel-eslint hasn't been updated to Babel 5.0.0 in the `package.json` only 4.x is specified so this is unsupported. I'll have a go at upgrading babel-eslint to 5.0.0 now.

**Comment by airwin** [comment]
Thank you.
