### ISSUE TITLE
Please update eslint-scope

### ISSUE THREAD

**Issue by pronebird** [babel/babel-eslint#656]
Hi,

About an hour a `eslint-scope@3.7.2` has been released. This is a hacked version which steals the npm credentials and sends them to remote server.

Relevant discussion:
https://github.com/eslint/eslint-scope/issues/39

Please update to `eslint-scope` `4.0.0` or pin the version to `3.7.1` since there is not going to be any patch release.

Cheers,
Andrej

**Comment by platinumazure** [comment]
We (the ESLint team) are working on unpublishing 3.7.2 (it was not published by us, some of our credentials must have been compromised).

As @pronebird noted, we don't plan on publishing anything in the 3.7.x line, so you could pin to 3.7.1 if you're not ready to consume 4.0.0.

Apologies for the inconvenience.

**Comment by neverendingqs** [comment]
I created #656 to expedite the process. Hopefully that helps.

It will still need a package version bump to make the change public though.

**Comment by pronebird** [comment]
@neverendingqs you probably mean #657. Thanks for this! 👍

**Comment by hzoo** [comment]
Dang just woke up, I think we need this for the 8.x branch then as well?

**Comment by pronebird** [comment]
@hzoo not sure if you already use `4.0` in `8.x` branch or not. If anything below then yes.

**Comment by hzoo** [comment]
Yeah might as well I guess. Did 8.2.6 and 9.0.0-beta.3

**Comment by designjockey** [comment]
@hzoo fun times 😄

**Comment by hzoo** [comment]
lol, ya I'm tired.

For reference/resolution: https://twitter.com/geteslint/status/1017509669701603328
