### ISSUE TITLE
Allow deduplication of eslint-scope

### ISSUE THREAD

**Issue by billyjanitsch** [babel/babel-eslint#658]
Now that the eslint-scope worm has been resolved, can babel-eslint be updated to depend on `^3.7.3` rather than `3.7.1`, so that the package can be deduped again?

(For instance, webpack depends on `^3.7.1`, so a project containing both webpack and babel-eslint will have both 3.7.1 and 3.7.3 installed.)

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
