### ISSUE TITLE
Official ESLint 5.x support?

### ISSUE THREAD

**Issue by dabrowne** [babel/babel-eslint#664]
Can anyone tell me if there are any issues when using with ESLint 5.x? The readme only mentions 4.x
https://github.com/babel/babel-eslint#supported-eslint-versions

**Comment by Jaace** [comment]
I too would like to know this, looks like the answer is currently "no" but being worked on?

**Comment by krave1986** [comment]
Me too. I have installed eslint for vscode whose version is 5.9.0 . Just when I was going to use class property and checking babel-eslint, I found it eslint 5.x is not on the support list. Any plan about this?

**Comment by jaydenseric** [comment]
For what it's worth `babel-eslint` itself uses `babel-eslint` with `eslint` v5:

https://github.com/babel/babel-eslint/blob/v10.0.1/package.json#L45

**Comment by hzoo** [comment]
v9/v10 should both work fine with it and yeah testing with v5 ^

We'll be removing that chart in v11, https://github.com/babel/babel-eslint/pull/711 - there weren't any changes necessary to support v5
