### ISSUE TITLE
why optional chaining  error

### ISSUE THREAD

**Issue by hms181231** [babel/babel-eslint#666]
optional chaining in stage 1
Babel-eslint install to version 8.2.1

![image](https://user-images.githubusercontent.com/15353926/43988521-2a7c7c72-9d6a-11e8-92c1-7bea074829ea.png)
![image](https://user-images.githubusercontent.com/15353926/43988560-1ed28ca8-9d6b-11e8-8891-72fd26642b2d.png)

**Comment by borela** [comment]
Try the beta version.

**Comment by srghma** [comment]
it's something with my tooling, because making `./node_modules/.bin/eslint .` in project dir doenst throw error

**Comment by yotamberk** [comment]
Any update on this? I'm getting the same behavior as @srghma

**Comment by srghma** [comment]
@yotamberk in my case it's something with neomake, didnt fix

**Comment by yotamberk** [comment]
What's neomake? I can use chaining but it screws up any other js code styling after it... Not gonna work for me as long as I can't fix this issue 😢

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
