### ISSUE TITLE
babel-eslint last version pipelineOperator resolved

### ISSUE THREAD

**Issue by simonjoom** [babel/babel-eslint#671]
Running with the last babel 7 (rc)
There is on error with "pipelineOperator"

I found on google to resolve we need to pass proposal at "minimal"

So changing in ./lib/parse.js
"pipelineOperator" line 46
to
 ['@babel/plugin-proposal-pipeline-operator', { 'proposal': 'minimal' }],

resolved my problem.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
