### ISSUE TITLE
legacyDecorators option not in documentation

### ISSUE THREAD

**Issue by jer-sen** [babel/babel-eslint#679]
`legacyDecorators` parser option should be documented.

**Comment by nicolo-ribaudo** [comment]
Do you want to open a PR?

**Comment by lidoravitan** [comment]
@nicolo-ribaudo Can I help with that :) ?

**Comment by nicolo-ribaudo** [comment]
This option has been removed in v11, but we can document it for v10 users (in [this branch](https://github.com/babel/babel-eslint/tree/10.x))

**Comment by lidoravitan** [comment]
Sounds ok for me.  could you give me some directions about where to start, I mean what file?

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
