### ISSUE TITLE
Cannot read property 'range' of null

### ISSUE THREAD

**Issue by ldwqh0** [babel/babel-eslint#681]
In my index.js
```javascript
export module1  from './module1'
export module2 from './module2'
```
with the error
```
Cannot read property 'range' of null
```
and I use Decorator before export like this 
```javascript

@Decorator
export default Class A {
 ...
}
```
the error 
```
Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.
```

How do I solve these two problems?

**Comment by craigbeck** [comment]
```
$ npx eslint .
Cannot read property 'range' of null
(node:44758) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "node_modules/eslint-config-airbnb-base/index.js")
```

```
> eslint . --cache --cache-file eslint-cache/eslintcache

Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/craigbeck/dev/premise-frontend-v3/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
```
 Also seeing similar error although we don't use decorators

**Comment by krousseau-cs** [comment]
I have the same issue. I'm not going to remove all template literals just for this upgrade since everything seems to still work with 8.2.6.

**Comment by ZackKnopp** [comment]
See: #530

**Comment by ljqx** [comment]
I encountered similar problem, finally I found that it's because of existence of 2 `@babel/types`.

`babel-eslint` changes data in `@babel/types` and assumes `@babel/traverse` would consume it. But as npm/yarn may create different `@babel/types` to avoid conflict, the change on `@babel/types` may not take affect on `@babel/traverse`.

So
```
- node_modules
  - @babel
    - traverse
    - types
  - babel-eslint
```
Would work. But
```
- node_modules
  - @babel
    - traverse
      - node_modules
        - @babel
          - types
  - babel-eslint
    - node_modules
      - @babel
        - types
```
won't work.

@hzoo , I think here it's better to pass in the `@babel/types` instead of implicitly depending on same dependency which may not be true.

**Comment by ldwqh0** [comment]
I have resolved this
```bash
Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.
```

add this config in my .eslintrc.js file
```javascript
  parserOptions: {
    ecmaFeatures: {
      legacyDecorators: true
    },
    parser: 'babel-eslint'
  }
```

but the "Cannot read property 'range' of null" error can not be resolved
wait online

**Comment by joepvl** [comment]
FWIW, I'm getting the same error, with eslint 5.11.1 and npm 6.5.0. Switching to yarn fixes it, so from that perspective it seems like a dependency/determinicness issue. However, I want to keep using npm, and I also don't want to downgrade.

In my case at least the error is generated during handling of template literals within the `indent` rule. I can live with not checking indentation for template literals, so I've fixed it for now using the `ignoredNodes` option for the `indent` rule, roughly as follows:

```javascript
"indent": ["error", 2, {
  "ignoredNodes": ["TemplateLiteral"]
}]
```

Not sure how else I can be of help, except maybe reiterate @ljqx's suggestion of trying to normalize the `@babel/types` dep across `babel` and `babel-eslint`. I can't tell if npm is doing something wrong here or if yarn's more deterministic algorithm is hiding a flaw in the code.

**Comment by aarongeorge** [comment]
I was having this issue myself using:

- eslint v5.12.0
- babel-eslint v10.0.1.

Using the following code words:
```
const foo = 'bar';
console.log('We\'re going for drinks at the ' + foo);
```

However if I change it to use a template literal with a placeholder:
```
const foo = 'bar';
console.log(`We're going for drinks at the ${foo}`);
```

I get the error: Cannot read property 'range' of null.

It seems to be an issue with using template literals that contain a placeholder as using:
``
console.log(`We're going for drinks at the bar`);
```

I upgraded babel-eslint's package.json to the following and it fixes the issue:
```
{
  "name": "babel-eslint",
  "version": "10.0.1",
  "description": "Custom parser for ESLint",
  "main": "lib/index.js",
  "files": [
    "lib"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/babel/babel-eslint.git"
  },
  "dependencies": {
    "@babel/code-frame": "^7.0.0",
    "@babel/parser": "^7.0.0",
    "@babel/traverse": "^7.0.0",
    "@babel/types": "^7.0.0",
    "eslint-scope": "4.0.0",
    "eslint-visitor-keys": "^1.0.0"
  },
  "scripts": {
    "test": "npm run lint && npm run test-only",
    "test-only": "mocha && mocha --require test/fixtures/preprocess-to-patch.js",
    "lint": "eslint lib test",
    "fix": "eslint lib test --fix",
    "precommit": "lint-staged",
    "preversion": "npm test",
    "changelog": "git log `git describe --tags --abbrev=0`..HEAD --pretty=format:' * %s (%an)' | grep -v 'Merge pull request'"
  },
  "author": "Sebastian McKenzie <sebmck@gmail.com>",
  "license": "MIT",
  "engines": {
    "node": ">=6"
  },
  "bugs": {
    "url": "https://github.com/babel/babel-eslint/issues"
  },
  "homepage": "https://github.com/babel/babel-eslint",
  "peerDependencies": {
    "eslint": ">= 4.12.1"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "dedent": "^0.7.0",
    "eslint": "^5.6.0",
    "eslint-config-babel": "^8.0.2",
    "eslint-plugin-flowtype": "^3.2.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-prettier": "^3.0.1",
    "espree": "^5.0.0",
    "husky": "^1.0.0-rc.13",
    "lint-staged": "^8.1.0",
    "mocha": "^5.0.1",
    "prettier": "^1.4.4"
  },
  "lint-staged": {
    "*.js": [
      "eslint --format=codeframe --fix",
      "git add"
    ]
  }
}
```

Also @hzoo is there any reason as to why babel-eslint has babel-eslint as a devDependency?

**Comment by lizuncong** [comment]
> I have the same issue. I'm not going to remove all template literals just for this upgrade since everything seems to still work with 8.2.6.
Have you resolved this question

**Comment by l443018** [comment]
@ldwqh0 could you attach complete error log in output channel? 

In my case, I encountered similar log as @dsizomin 
I solved it by remove `yarn.lock` `node_modules` and run `yarn install` again: https://github.com/babel/babel-eslint/issues/530#issuecomment-438635426

```
[Error - 11:55:33 AM] TypeError: Cannot read property 'range' of null
    at OffsetStorage.setDesiredOffset (/home/laura/Documents/project/kid-guard-api/node_modules/eslint/lib/rules/indent.js:335:45)
    at TemplateLiteral.node.expressions.forEach (/home/laura/Documents/project/kid-guard-api/node_modules/eslint/lib/rules/indent.js:1335:29)
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (/home/laura/Documents/project/kid-guard-api/node_modules/eslint/lib/rules/indent.js:1327:34)
    at Program:exit.listenerCallQueue.filter.forEach.nodeInfo (/home/laura/Documents/project/kid-guard-api/node_modules/eslint/lib/rules/indent.js:1537:55)
    at Array.forEach (<anonymous>)
    at Program:exit (/home/laura/Documents/project/kid-guard-api/node_modules/eslint/lib/rules/indent.js:1537:26)
    at listeners.(anonymous function).forEach.listener (/home/laura/Documents/project/kid-guard-api/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/laura/Documents/project/kid-guard-api/node_modules/eslint/lib/util/safe-emitter.js:45:38)
```

**Comment by dallashall-procore** [comment]
This problem popped up for me after running `npm audit fix` to clear some npm vulnerability warnings, which bumped my version of eslint from v5.8.0 to v5.13.0

Removing my `package-lock.json` and `node_modules` folder and running `npm install` worked to resolve this in my case.

eslint: v5.13.0
babel-eslint: v10.0.1

**Comment by aramk** [comment]
I fixed this issue by making sure I only have the one version of @babel/types:
```
npm list @babel/types
```
I targeted version 7.3.4 and some packages were using the newer 7.4.4. For those packages I reverted to an older version which used @babel/types@7.3.4. I did this without adding the dependency to `package.json`. An `npm install` is sufficient to update the `package-lock.json`.

Then I ran the dedupe command to ensure I had no duplicates of `@babel/types`, since having multiple copies of the same version will still cause issues.
```
npm dedupe @babel/types
```
You should then see that the npm list command shows a single `@babel/types` without "dedupe" and all others with it, indicating they're references. After this the linter ran just fine.

**Comment by minhna** [comment]
> Removing my `package-lock.json` and `node_modules` folder and running `npm install` worked to resolve this in my case.

It works. Thank you.

**Comment by wojtekmaj** [comment]
For those of you running yarn, Running [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate) and then re-installing your modules by running `yarn` will fix the issue.

**Comment by wichopy** [comment]
I wish we could push top voted answers to the top. THE accepted answer should be to dedupe and reinstall. In my case, I just deleted package.json and reinstalled

**Comment by AncoraYhls** [comment]
@aramk I have been troubled for a few hours. Thanks a lot. It works for me.

**Comment by houchaowei** [comment]
> See: #530
> What worked for me in .eslintrc:
> 
> ```
> // TODO: Remove when is https://github.com/babel/babel-eslint/issues/530 fixed
>   rules : {
>     "template-curly-spacing" : "off",
>     indent : "off"
>   }
> ```

it worked for me! thx :)

**Comment by sdemjanenko** [comment]
dedupe worked for me. I unfortunately didn't track the diff to the yarn.lock file. If we knew what the diff was we could update the dependency range for the module that is being required which would make running dedupe unnecessary.

**Comment by raspy8766** [comment]
If you're using yarn, you can add a resolutions field in your `package.json` to force yarn to resolve to a single version for that package: 
```
  "resolutions": {
    "@babel/types": "7.7.2"
  },
```
With that in there you can run `yarn install` and remove the resolutions field afterwards (since you can install from the `yarn.lock` file going forward).

**Comment by Excalibaard** [comment]
I initially tried with defining a resolution for @babel/types and completely re-installing the modules, but the error persisted. This solution worked however: 

> FWIW, I'm getting the same error, with eslint 5.11.1 and npm 6.5.0. Switching to yarn fixes it, so from that perspective it seems like a dependency/determinicness issue. However, I want to keep using npm, and I also don't want to downgrade.
> 
> In my case at least the error is generated during handling of template literals within the `indent` rule. I can live with not checking indentation for template literals, so I've fixed it for now using the `ignoredNodes` option for the `indent` rule, roughly as follows:
> 
> ```js
> "indent": ["error", 2, {
>   "ignoredNodes": ["TemplateLiteral"]
> }]
> ```
> 
> Not sure how else I can be of help, except maybe reiterate @ljqx's suggestion of trying to normalize the `@babel/types` dep across `babel` and `babel-eslint`. I can't tell if npm is doing something wrong here or if yarn's more deterministic algorithm is hiding a flaw in the code.

Interestingly, I removed the specific indent rule afterwards to test whether it works (resolutions still in place), and eslint kept working.

**Comment by 1um** [comment]
Thanks, dedupe AND reinstall worked for me!
```
npm dedupe @babel/types
rm -rf node_modules package-lock.json
npm install
`

**Comment by hyalen** [comment]
> See: #530
> What worked for me in .eslintrc:
> 
> ```
> // TODO: Remove when is https://github.com/babel/babel-eslint/issues/530 fixed
>   rules : {
>     "template-curly-spacing" : "off",
>     indent : "off"
>   }
> ```

This solution worked for me. Thanks!

**Comment by lolmaus** [comment]
`yarn upgrade` resolved this issue for me.

**Comment by ligne13** [comment]
> This problem popped up for me after running `npm audit fix` to clear some npm vulnerability warnings, which bumped my version of eslint from v5.8.0 to v5.13.0
> 
> Removing my `package-lock.json` and `node_modules` folder and running `npm install` worked to resolve this in my case.
> 
> eslint: v5.13.0
> babel-eslint: v10.0.1

This fixed the issue

**Comment by bernardodomingues-hotmart** [comment]
This issue keeps happening to me. Tried everything above (`npm dedupe`, removing `package-lock` and `node_modules`, etc). The only solution that works for me is freezing the `@babel/parser` version to `7.7.5`. Any newer version breaks eslint with the same error.

eslint: v6.8.0
babel-eslint: 10.0.3

**Comment by SterlingVix** [comment]
For anyone coming back to this issue: @raspy8766 's solution of adding a `resolution` to my `package.json` worked for me. If you're facing this issue, this should be your first attempt to fix it, IMO.

In our repo we use `yarn`. After updating deps and following several ideas here (with no progress), I looked for the versions of `@babel/types` using `npm list @babel/types`. I standardized resolutions on v7.6.1:

```
"resolutions": {
  "@babel/types": "7.6.1",
  ...
},
```

This is the result of `npm list @babel/types` before adding the `resolutions` entry:
```
npm list @babel/types
+-- @babel/core@7.6.2
| +-- @babel/generator@7.6.2
| | `-- @babel/types@7.6.1  deduped
| +-- @babel/helpers@7.6.2
| | `-- @babel/types@7.6.1  deduped
| +-- @babel/template@7.6.0
| | `-- @babel/types@7.6.1  deduped
| +-- @babel/traverse@7.6.2
| | +-- @babel/helper-function-name@7.1.0
| | | `-- @babel/types@7.6.1  deduped
| | +-- @babel/helper-split-export-declaration@7.4.4
| | | `-- @babel/types@7.6.1  deduped
| | `-- @babel/types@7.6.1  deduped
| `-- @babel/types@7.6.1 
+-- @babel/plugin-proposal-class-properties@7.5.5
| `-- @babel/helper-create-class-features-plugin@7.5.5
|   +-- @babel/helper-member-expression-to-functions@7.5.5
|   | `-- @babel/types@7.6.1  deduped
|   +-- @babel/helper-optimise-call-expression@7.0.0
|   | `-- @babel/types@7.6.1  deduped
|   `-- @babel/helper-replace-supers@7.5.5
|     `-- @babel/types@7.6.1  deduped
+-- @babel/preset-env@7.6.2
| +-- @babel/helper-module-imports@7.0.0
| | `-- @babel/types@7.6.1  deduped
| +-- @babel/plugin-proposal-async-generator-functions@7.2.0
| | `-- @babel/helper-remap-async-to-generator@7.1.0
| |   +-- @babel/helper-wrap-function@7.2.0
| |   | `-- @babel/types@7.6.1  deduped
| |   `-- @babel/types@7.6.1  deduped
| +-- @babel/plugin-transform-classes@7.5.5
| | +-- @babel/helper-annotate-as-pure@7.0.0
| | | `-- @babel/types@7.6.1  deduped
| | `-- @babel/helper-define-map@7.5.5
| |   `-- @babel/types@7.6.1  deduped
| +-- @babel/plugin-transform-exponentiation-operator@7.2.0
| | `-- @babel/helper-builder-binary-assignment-operator-visitor@7.1.0
| |   +-- @babel/helper-explode-assignable-expression@7.1.0
| |   | `-- @babel/types@7.6.1  deduped
| |   `-- @babel/types@7.6.1  deduped
| +-- @babel/plugin-transform-modules-amd@7.5.0
| | `-- @babel/helper-module-transforms@7.5.5
| |   `-- @babel/types@7.6.1  deduped
| +-- @babel/plugin-transform-modules-commonjs@7.6.0
| | `-- @babel/helper-simple-access@7.1.0
| |   `-- @babel/types@7.6.1  deduped
| +-- @babel/plugin-transform-modules-systemjs@7.5.0
| | `-- @babel/helper-hoist-variables@7.4.4
| |   `-- @babel/types@7.6.1  deduped
| +-- @babel/plugin-transform-parameters@7.4.4
| | +-- @babel/helper-call-delegate@7.4.4
| | | `-- @babel/types@7.6.1  deduped
| | `-- @babel/helper-get-function-arity@7.0.0
| |   `-- @babel/types@7.6.1  deduped
| `-- @babel/types@7.6.1  deduped
+-- @babel/preset-react@7.0.0
| `-- @babel/plugin-transform-react-jsx@7.3.0
|   `-- @babel/helper-builder-react-jsx@7.3.0
|     `-- @babel/types@7.5.5 
+-- babel-eslint@10.0.3
| +-- @babel/traverse@7.1.4
| | +-- @babel/generator@7.1.3
| | | `-- @babel/types@7.1.3 
| | +-- @babel/helper-split-export-declaration@7.0.0
| | | `-- @babel/types@7.6.1  deduped
| | `-- @babel/types@7.1.3 
| `-- @babel/types@7.6.1  deduped
`-- regenerator@0.14.2
  `-- @babel/types@7.6.1  deduped
```

**Comment by antoniandre** [comment]
Hi everybody, This is still happening for me with the very latest version:

```json
    "@vue/cli-plugin-babel": "^4.2.3",
    "@vue/cli-plugin-eslint": "^4.2.3",
    "@vue/cli-plugin-router": "^4.2.3",
    "@vue/cli-service": "^4.2.3",
    "@vue/eslint-config-standard": "^5.1.2",
    "babel-eslint": "^10.1.0",
    "core-js": "^3.6.4",
    "eslint": "^6.8.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-vue": "^6.2.1",
```

The compiling fails on this line, because of the template literal:
```js
import(/* webpackInclude: /\.json$/, webpackChunkName: "i18n/[request]" */ `./i18n/${locale}`)
```

Probably a month ago when I faced it I could fix it with: https://github.com/babel/babel-eslint/issues/681#issuecomment-464163266, now the error is back after upgrade and the trick does not work anymore.

As @joepvl mentioned I could disable template literal checking with:

```json
"indent": ["error", 2, {
  "ignoredNodes": ["TemplateLiteral"]
}]
```

But I don't think it is a solution.
Am I the only one left having this issue?

**Comment by antoniandre** [comment]
Good news here, after updating `eslint-plugin-vue` to the new version 6.2.2 this is fixed!

```
npm i --D eslint-plugin-vue
npm audit fix
```

**Comment by everyonesdesign** [comment]
Should this issue be reopened? I have the same problem with `babel-eslint` v.10.1.0

**Comment by theKashey** [comment]
One of possible solutions - delete any information about `@babel/*` from `package/yarn.lock` and reinstall.
In case of `yarn` you might try [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate)

**Comment by richardvanbergen** [comment]
This error can also be triggered by using backticks in import statements. For me the issue was in the following:

    import(`intersection-observer`)

I've encountered similar issues with template literals and imports before so I changed it to a single quote and it worked!

**Comment by simonc** [comment]
It doesn't seem to be limited to import statements.

After updating my dependencies the `@babel/types` entry was changed this way

```diff

-"@babel/types@^7.1.6", "@babel/types@^7.3.2", "@babel/types@^7.3.4", "@babel/types@^7.4.4", "@babel/types@^7.7.0", "@babel/types@^7.7.2", "@babel/types@^7.8.3", "@babel/types@^7
+"@babel/types@^7.1.6", "@babel/types@^7.3.2", "@babel/types@^7.3.4", "@babel/types@^7.4.4", "@babel/types@^7.8.3", "@babel/types@^7.8.6", "@babel/types@^7.9.0", "@babel/types@^7
+  version "7.9.5"
+  resolved "https://registry.yarnpkg.com/@babel/types/-/types-7.9.5.tgz#89231f82915a8a566a703b3b20133f73da6b9444"
+  integrity sha512-XjnvNqenk818r5zMaba+sLQjnbda31UfUURv3ei0qPQw4u+j2jMyJ5b11y8ZHYTRSI3NnInQkkkRT4fLqqPdHg==
+  dependencies:
+    "@babel/helper-validator-identifier" "^7.9.5"
+    lodash "^4.17.13"
+    to-fast-properties "^2.0.0"
+
+"@babel/types@^7.7.0", "@babel/types@^7.7.2":
   version "7.9.0"
   resolved "https://registry.yarnpkg.com/@babel/types/-/types-7.9.0.tgz#00b064c3df83ad32b2dbf5ff07312b15c7f1efb5"
   integrity sha512-BS9JKfXkzzJl8RluW4JGknzpiUV7ZrvTayM6yfqLTVBEnFtyowVIOu6rqxRd5cVO6yGoWf4T8u8dgK9oB+GCng==
```

And now eslint breaks on a file because of this line:

```js
headers.Authorization = `Bearer ${this.session.data.authenticated.auth_token}`;
```

**Comment by imagoiq** [comment]
I'm getting the same issue as @antoniandre with [the lazy-load Vue-i18n config](https://kazupon.github.io/vue-i18n/guide/lazy-loading.html).

The following line using Webpack dynamic import is wrongly transpiled.

```
return import(/* webpackChunkName: "lang-[request]" */ `@/locales/${lang}.json`)
```
With babel-eslint 10.0.3, it is working with:

```
return Promise.resolve().then(function () {
 return _interopRequireWildcard(__webpack_require__("./src/locales sync recursive ^\\.\\/.*\\.json$")("./".concat(lang, ".json")));
…
```
But with babel-eslint 10.1.0, I'm getting:
```
  return Promise.resolve("@/locales/".concat(lang, ".json")).then(function (s) {
    return _interopRequireWildcard(__webpack_require__("./src/plugins sync recursive")(s));
```

The tricks mentionned by @joepvl and @raspy8766 work to ignore the `Cannot read property 'range' of null` error but the import are broken.

**Comment by NicholasIoanJones** [comment]
This is really frustrating. Appeared out of nowhere.
Solution for me was to delete node_modules and yarn.lock and rerun yarn
Hope it helps somebody else

**Comment by elhaouari-mohammed** [comment]
For any one reading this, here is how I solved this issue : 
I added the following snippet to my `.eslintrc` under the rules directive : 

```json
  "rules": {
    "template-curly-spacing": "off",
    "indent": [
      "warn",
      2,
      {
        "ignoredNodes": ["TemplateLiteral"],
        "SwitchCase": 1
      }
    ]
}
```

**Comment by lolmaus** [comment]
Tried @elhaouari-mohammed 's suggestion. Unfortunately, did not help me.

My error happens at build time, so ESLint does not seem to be involved.

**Comment by elhaouari-mohammed** [comment]
@lolmaus  Actually for me it's the gitlab pipelines that fails because of eslint, everything works on local environment and on deploy server, so it's really weird , as @NicholasIoanJones said : Appeared out of nowhere.

**Comment by lolmaus** [comment]
I've noticed that the error message has changed for me.

Instead of `Cannot read property 'range' of null` it's now saying `Debug failure`.

**Comment by lolmaus** [comment]
Both error messages are very generic.

Multiple unrelated issues might lead to them.

**Comment by agm1984** [comment]
I started reproducing this earlier today while pasting code into my project. It seemed like ES Lint got overwhelmed by hundreds of infractions.

At the moment, I am seeing this:
```
[Info  - 10:31:45 PM] Cannot read property 'range' of null Occurred while linting .../resources/js/router/routes.js:2
[Info  - 10:31:46 PM] Cannot read property 'range' of null Occurred while linting .../resources/js/router/routes.js:2
[Info  - 10:31:47 PM] Cannot read property 'range' of null Occurred while linting .../resources/js/router/routes.js:2
```

That piece of code is:

``` javascript
function page (path) {
    return () => import(/* webpackChunkName: '' */ `~/pages/${path}`).then(m => m.default || m);
}
```

In my opinion, it's deceptively complex, because that line of code implicates `@babel/plugin-syntax-dynamic-import` for the **import** keyword, and also Webpack code related to **aliases**:

``` javascript
// webpack.mix.js
    resolve: {
        extensions: ['.js', '.json', '.vue'],
        alias: {
            '@': `${__dirname}/resources`,
            '~': path.join(__dirname, './resources/js'),
        },
    },

// .eslintrc.json
    "settings": {
        "import/resolver": {
            "alias": {
                "map": [
                    ["@", "./resources"],
                    ["~", "./resources/js"]
                ],
                "extensions": [".vue"]
            }
        }
    }
```

**Comment by packetstracer** [comment]
i'm using CRA (react-scripts@3.4.1), yarn and react-app-rewired@2.1.6  and this issue happens to me only transpiling the tests (yarn test) with import sentences using template literals such as this one:

```js
import(`${path}`)
```

Neither of the commented solutions worked for me but using the patch of disabling the corresponding eslint rules. To me this is not a valid solution, but by the moment will use it.

> > See: #530
> > What worked for me in .eslintrc:
> > ```
> > // TODO: Remove when is https://github.com/babel/babel-eslint/issues/530 fixed
> >   rules : {
> >     "template-curly-spacing" : "off",
> >     indent : "off"
> >   }
> > ```
> 
> This solution worked for me. Thanks!

**Comment by cdll** [comment]
same issue here with ``"babel-eslint": "^10.0.1"`` in @vue/cli.

**Comment by paschalidi** [comment]
adding to the package.json would solve the issue for me
```
{
    "resolutions": {
        "@babel/parser": "7.7.5"
    }
}
```
Also run 
```
git clean -fdx 
``` 
to clean all history of npm modules in your project and then reinstall them using 
```
npm i or yarn
```

**Comment by KrishnaPG** [comment]
Facing the same problem with below code:
````
return import(/* webpackChunkName: "lang-[request]" */ `./lang/${lang}`)
````
Following the @richardvanbergen suggestion above, removed the template string and instead used as below and the warning went away. 
````
return import(/* webpackChunkName: "lang-[request]" */ "./lang/"+lang)
````
Hope to see this fixed soon.

**Comment by romulof** [comment]
> I encountered similar problem, finally I found that it's because of existence of 2 `@babel/types`.
> 
> `babel-eslint` changes data in `@babel/types` and assumes `@babel/traverse` would consume it. But as npm/yarn may create different `@babel/types` to avoid conflict, the change on `@babel/types` may not take affect on `@babel/traverse`.
> 
> So
> 
> ```
> - node_modules
>   - @babel
>     - traverse
>     - types
>   - babel-eslint
> ```
> 
> Would work. But
> 
> ```
> - node_modules
>   - @babel
>     - traverse
>       - node_modules
>         - @babel
>           - types
>   - babel-eslint
>     - node_modules
>       - @babel
>         - types
> ```
> 
> won't work.
> 
> @hzoo , I think here it's better to pass in the `@babel/types` instead of implicitly depending on same dependency which may not be true.

I'm getting this error with `template-curly-spacing` and `indent` rules with this `node_modules` layout:

- `@babel`
  - `traverse@7.10.1`
    - `node_modules`
      - `debug` (non related, i guess)
      - `msty` (non related, i guess)
  - `types@7.10.1`
    - ~~`node_modules`~~
- `babel-eslint@10.1.0`
    - ~~`node_modules`~~

Adjusting both rules like this works:
```json
"rules": {
    "indent": ["error", 4, { "ignoredNodes": ["TemplateLiteral"] }],
    "template-curly-spacing" : "off"
}
```

Does anyone knows the cause of issue?

**Comment by Powersource** [comment]
I believe (although not sure) I started getting this when updating from babel-eslint 10.0.3 to 10.1.0
