### ISSUE TITLE
importing .ts from .js doesn't seem to work. Known issue?

### ISSUE THREAD

**Issue by jon-lp** [babel/babel-eslint#687]
We're using babel 7.0 and babel-eslint 9.0.0 and are in the process of converting all js files to typescript. It seems that in babel+webpack imports of any of the 4 permutations (JS -> JS, TS -> TS, TS -> JS, JS -> TS) work fine, but when running eslint, it errors on import/no-unresolved when a typescript file is imported from a javascript file. Is this expected behavior?

**Comment by kaicataldo** [comment]
I don't think this is an issue with babel-eslint, but rather that the `import/no-unresolved` rule doesn't know how to resolve files with the `*.ts` extension.  Might be worth making an issue on the [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) repo.

**Comment by jon-lp** [comment]
@kaicataldo - I think you're exactly right :-)

**Comment by willdady** [comment]
Did find a solution to this @jon-lp ?
