### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by damianobarbati** [babel/babel-eslint#700]
On Node 10 the following: `pg.types.setTypeParser(20, value => BigInt(value));`
Results into error: `'BigInt' is not defined`

How to solve this?

**Comment by bradennapier** [comment]
Both Chrome and Node have now supported BigInt for some time.  Would be nice if babel-eslint could parse them.

https://developers.google.com/web/updates/2018/05/bigint
https://v8.dev/blog/bigint

Node implemented in LTS version without flags as of version `10.4`

**Comment by hzoo** [comment]
Via #711 this should be fixed by reading from Babel config, in the next release
