### ISSUE TITLE
How do we tell babel-eslint to allow export after @decos?

### ISSUE THREAD

**Issue by trusktr** [babel/babel-eslint#701]
I have a project using Prettier, and Prettier puts the `export`s after `@decos`.

How can I tell babel-eslint to allow export after decos?

---

I just installed babel-eslint today.

My babelrc looks like this:

```js
module.exports = {
	extends: ['prettier'],
	parser: 'babel-eslint',
	parserOptions: {
		ecmaFeatures: {
			legacyDecotators: true,
		},
	},
}

```

**Comment by georgeelliottelement** [comment]
You've got a typo in your config: `legacyDecotators` => `legacyDecorators`. Aside from that, using this config fixed the problem for me.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
