### ISSUE TITLE
Can we disable type support (flow) in JavaScript files, so that we get syntax errors instead?

### ISSUE THREAD

**Issue by trusktr** [babel/babel-eslint#702]
How can we do that?

I'm trying to write plain JavaScript and my editor tells me that I don't have syntax errors when there are type annotations, which is unexpected.

![example2](https://user-images.githubusercontent.com/297678/46909124-50e64880-cee2-11e8-995e-ae8315a78e2b.gif)

eslintrc:

```js
module.exports = {
	parser: 'babel-eslint',
}
```

Is this babel-eslint's concern?

**Comment by trusktr** [comment]
To achieve this for now, I went back to using plain ESLint, which is less convenient without experimental features, but it get the job done (show errors on type annotations).

```js
module.exports = {
	parserOptions: {
		sourceType: 'module',
		ecmaVersion: 2018,
		ecmaFeatures: {
			jsx: true,
			impliedStrict: true,
		},
	},
}
```

**Comment by kaicataldo** [comment]
This should be solved by https://github.com/babel/babel-eslint/pull/711

**Comment by hzoo** [comment]
Closing, should be fixed in next release since it should read from your config now
