### ISSUE TITLE
Moving to "@babel/eslint"?

### ISSUE THREAD

**Issue by simlu** [babel/babel-eslint#710]
Is there a reason that this is not moved to "@babel/eslint" (yet)?

**Comment by kaicataldo** [comment]
I don't know if it needs to be moved, but if it is it should probably be called something like `@babel/eslint-parser`. Another repo to consider is https://github.com/babel/eslint-plugin-babel - seems like it should also be moved into the org if this one is.

**Comment by jhpratt** [comment]
`@babel/eslint-parser` and `@babel/eslint-plugin` would make sense.

**Comment by kaicataldo** [comment]
This is done!
