### ISSUE TITLE
Babel 6 explicit function parameter type support?

### ISSUE THREAD

**Issue by jedwards1211** [babel/babel-eslint#730]
Unfortunately, I am stuck on Babel 6 until `babel-plugin-flow-runtime` supports Babel 7.
This means I am unable to use Flow >= 0.85.0, which requires explicit function type parameter annotations in some cases, because Babel 6 doesn't support them:

```js
$ babel src/universal/redux/sidebar.js 
SyntaxError: src/universal/redux/sidebar.js: Unexpected token (53:66)
  51 | }
  52 | 
> 53 | export const sidebarReducer = combineReducers<SidebarState, Action>({
     |                                                                   ^
  54 |   open: createReducer(null, {
  55 |     [SET_SIDEBAR_OPEN]: (state: State, action: SetSidebarOpenAction) => action.payload,
  56 |   }),
```

I am suffering :cry:
Is there any plugin for Babel 6 that makes it handle this syntax?

**Comment by loganfsmyth** [comment]
Unfortunately I think you'll have to wait for it to support Babel 7.
