### ISSUE TITLE
Parsing errors with Flow explicit inexact type syntax

### ISSUE THREAD

**Issue by langri-sha** [babel/babel-eslint#734]
I'm receiving an ESLint parsing error "Unexpected token" when using the following syntax for [explicit inexact types](https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf):

```
type Foo = {
  bar: string,
  ...
}
```

**Comment by mj12albert** [comment]
I’m also experiencing the same issue, using:

node 10.15.0
babel 7.2.2
babel-eslint 10.0.1
eslint 5.12.0

**Comment by mj12albert** [comment]
Just noticed (from comments in the the blog post about the new inexact syntax) that this isn't supposed to work yet (as of Jan'18) https://medium.com/@jordanbrown215/they-havent-been-released-yet-but-will-be-soon-67249c219895

However, using `babel-eslint@11.0.0-beta.0` no longer causes the ESLint parsing error, but flow itself isn't recognising the new syntax

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
