### ISSUE TITLE
11.0.0-beta.0 - Private class methods no-undef error

### ISSUE THREAD

**Issue by Ateiri** [babel/babel-eslint#746]
I tried using of private class methods, but stuck with `no-undef` error.

`@babel/core@^7.2.0`, also added as peer dependency.
`babel-eslint@^11.0.0-beta.0`.

![image](https://user-images.githubusercontent.com/10453124/51801952-d0571800-2244-11e9-8f1e-8a4c9b7fedaf.png)

Anybody have any suggestions?

**Comment by gverni** [comment]
Hi @Ateiri I had a similar problem with a class defined like that: 

```javascript
class foo {
  ...
  #myPrivateMethod(arg) {
    ...
  }
  ...
  publicMethod() {
    ...
    this.#myPrivateMethod(arg)
    ...
  }
}
```

This would trigger the following eslint error: 

`  error  'myPrivateMethod' is not defined  no-undef
`

Not sure this is your same problem. If it is, I solved replacing the definition of the private method with: 

```javascript
  #myPrivateMethod = function (arg) {
    ...
  }
```

Hope it helps

**Comment by gverni** [comment]
Good point @Ateiri. To help investigate this issue, I created a repo [here](https://github.com/gverni/private-instance-methods-playground) with the sample private instance method from [Babel 7.2.0 release note](https://babeljs.io/blog/2018/12/03/7.2.0). The file transpile and execute correctly but the lint causes the `no-undef` error.

**Comment by Ateiri** [comment]
@gverni as @kaicataldo mentioned, we need to take a look at `eslint-plugin-babel` first.
For now I'm going to take a look to babel issue first, I had some comments about missed aliases for babel/types.

**Comment by kaicataldo** [comment]
On second look, given that this error is coming from `@babel/core` and the original author confirmed that this isn't compiled by Babel either, this doesn't look like an issue with `babel-eslint`. If you're still experiencing this, feel free to make an issue in https://github.com/babel/babel.
