### ISSUE TITLE
it makes /*global some_unused_var*/ doesn't work anymore 

### ISSUE THREAD

**Issue by zzzgit** [babel/babel-eslint#758]
`/*global some_unused_var*/`

This directive won't work if I use `babel-eslint` as the parser.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
