### ISSUE TITLE
Node type of JSXText is different from espree

### ISSUE THREAD

**Issue by golopot** [babel/babel-eslint#759]
For jsx texts like foo in `<>foo</>`, espress has type `JSXText`, while babel-eslint has type `Literal`.

```javascript
require("espree").parse("<>foo</>", { ecmaFeatures: { jsx: true } })
  .body[0].expression.children[0].type; // JSXText


require("babel-eslint").parse("<>foo</>")
  .body[0].expression.children[0].type; // Literal
```

Is this working as intended?

**Comment by kaicataldo** [comment]
Can you share what version of babel-eslint you're using?

**Comment by golopot** [comment]
@kaicataldo  It was 10.0.1

**Comment by kaicataldo** [comment]
Can you confirm this is still an issue with the latest release?

**Comment by golopot** [comment]
Yes the issue still holds in 11.0.0-beta.0 .

`require('babel-eslint').parse('<div>foo</div>', {babelOptions: {configFile: "./.babelrc"}} ).body[0].expression.children[0].type`

With `.babel` `{"plugins": ["@babel/plugin-syntax-jsx"]}` .

**Comment by golopot** [comment]
@kaicataldo I think the bug is caused by

https://github.com/babel/babel-eslint/blob/5102c31835bdd4ec78d9f32b68a4d94a5c78678d/lib/babylon-to-espree/convertAST.js#L50-L52
