### ISSUE TITLE
Support for absolute paths

### ISSUE THREAD

**Issue by sergiulucaci** [babel/babel-eslint#763]
Hey guys,

is there a way to bypass absolute imports? 

my .eslint looks like:

```
...
"parser": "babel-eslint"
"settings": {
  "import/resolver": {
    "node": {
      "extensions": [ ".js" ]
    }
  }
}
...
```

but using babel-eslint the import/resolver rule is ignored.

Thank you in advance.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
