### ISSUE TITLE
11.0.0-beta.0 how to setup with react-native?

### ISSUE THREAD

**Issue by sibelius** [babel/babel-eslint#764]
react-native can have trouble if you provide a custom babel config

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
