### ISSUE TITLE
Parsing error on smart pipeline

### ISSUE THREAD

**Issue by jhpratt** [babel/babel-eslint#765]
When passing in a value with the placeholder (`#`), a syntax error is thrown.

Example:
```js
header_elem |> assign_defined(#, { display_name, t0 });
```

It doesn't seem like there's any way around this, so I currently have to ignore the entire file.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
