### ISSUE TITLE
Using TypeScript Lookup Types results in a Parsing error

### ISSUE THREAD

**Issue by jay-almaraz** [babel/babel-eslint#766]
I _think_ I've narrowed down the issue to `babel-eslint`.

I've built out a (reasonably) minimal example and pushed it to [a repo](https://github.com/jay-almaraz/mvce-eslint-typescript-bug) but the crux of it is this:

* React
* Webpack + Babel
* TypeScript
* ESLint + `babel-eslint` + `@typescript-eslint`

Within `App.tsx` I have:

```js
// App.tsx
// ...

interface Foo {
  bar: string;
}

type Greeting = Foo["bar"];

// ...
```

And when trying to build eslint gives me the following error:

```js
ERROR in ./src/App.tsx
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/jay/dev/mvce-eslint-typescript-issue/src/App.tsx
  7:21  error  Parsing error: Unexpected token, expected "]"

   5 | }
   6 | 
>  7 | type Greeting = Foo["bar"];
     |                     ^
   8 | 
   9 | export const App = (): ReactElement => {
  10 |   const helloWorld: Greeting = "Hello, World!";

✖ 1 problem (1 error, 0 warnings)
```

Removing `parser: "babel-eslint"` from `.eslintrc.js` and removing `enforce: "pre"` from the `eslint-loader` block in `webpack.config.js` have so far been the only ways that I've found to suppress the error.

If you have any recommendations on where else I should post this issue then please recommend away.

I'm not that confident in my conclusion that the issue is in `babel-eslint` but it's a start 🤷‍♀️ 

# Appendix

```js
// webpack.config.js
// ...
  module: {
    rules: [
      { test: /\.tsx?$/, loader: "awesome-typescript-loader" },
      { enforce: "pre", test: /\.js$/, loader: "source-map-loader" },
      {
        enforce: "pre",
        test: /\.(js|mjs|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        loader: "eslint-loader",
        options: {
          configFile: "./.eslintrc.js"
        }
      },
      {
        test: /\.(js|mjs|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader"
          }
        ]
      }
    ]
  },
// ...
```

```json
// .babelrc
{
  "presets": ["@babel/preset-env", "@babel/preset-react", "@babel/typescript"],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
```

```js
// .eslintrc.js
module.exports = {
  env: {
    browser: true,
    es6: true
  },
  globals: {
    Atomics: "readonly",
    SharedArrayBuffer: "readonly"
  },
  parser: "babel-eslint",
  plugins: ["@typescript-eslint", "react"],
  parserOptions: {
    ecmaFeatures: {
      jsx: true
    },
    ecmaVersion: 2018,
    sourceType: "module"
  },
  rules: {
    "max-len": [2, { code: 120, tabWidth: 2 }]
  }
};
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "target": "es6",
    "jsx": "react",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
  },
  "include": ["./src/**/*"]
}
```

**Comment by merisbahti** [comment]
I've got the same issue, did you figure out a solution?

**Comment by lukejagodzinski** [comment]
I have the same issue, any ideas how to solve it? I'm trying to switch from `@typescript-eslint` to `babel-eslint`

**Comment by golopot** [comment]
Babel-eslint@10 does not support Typescript. Can you change eslint parser to `@typescript-eslint/parser`?

```jsonc
// eslintrc.json
{
  "parser": "@typescript-eslint/parser"
}
```

**Comment by leereichardt** [comment]
I'm a bit late to the party, but are there any downsides swapping out the parser here if we're using babel for everything?

**Comment by nicolo-ribaudo** [comment]
You can upgrade to `babel-eslint@11` (which is still in beta): it reads your Babel config, so it will parse TS if you are already using it with Babel.

**Comment by kaicataldo** [comment]
As long as you're only using syntax supported by TypeScript, this should be just fine.

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
