### ISSUE TITLE
how to do that can babel-eslint support @babel/plugin-proposal-optional-chaining

### ISSUE THREAD

**Issue by pandaCure** [babel/babel-eslint#767]
```
    "@babel/plugin-proposal-optional-chaining": "^7.2.0",
    "@vue/cli-plugin-babel": "^3.6.0",
    "@vue/cli-plugin-eslint": "^3.6.0",
    "@vue/cli-service": "^3.6.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "axios": "^0.18.0",
    "babel-eslint": "^10.0.1",
    "babel-plugin-component": "^1.1.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
```
error 
```
Parsing error: Invalid left-hand side in assignment expression
  25 |       return false
  26 |     }
> 27 |     config?.headers?.Authorization = [localStorage.getItem('Authorization') || '']
     |     ^
  28 |     return config
  29 |   },
  30 |   function (error) {esl
```
i use vs code, i want to use babel new feature but eslint always show errors

**Comment by NukaPunk** [comment]
I'm having issues with optional chaining syntax highlighting myself. 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/6144177/57738683-1f9b4a00-7676-11e9-8a79-2882c94ae053.png">

**Comment by RickMeijer** [comment]
@pandaCure:  could you post your eslint & babel config?

![image](https://user-images.githubusercontent.com/1837945/58003046-37445980-7ae0-11e9-8bf5-e399729ed69e.png)

hear hear.

.eslintrc.js:
```
module.exports = {
  root: true,
  env: {
    node: true,
  },
  parserOptions: {
    parser: 'babel-eslint'
  }
}
```
babel.config.js:
```
module.exports = {
  presets: ['@vue/app'],
  plugins: ['@babel/plugin-proposal-optional-chaining']
}
```

**Comment by gnext-andrese03** [comment]
Hello, any updates?

**Comment by card-b** [comment]
Same issue here, any updates?

**Comment by dabiil** [comment]
any updates?

**Comment by andrese03** [comment]
I have fixed by disabling the Typescript checking that VS Code performs. Apparently (for me) this causes the issue.

This is my VS Code configuration in the file `.vscode/settings.json`

```
{
     "javascript.validate.enable": false
}
```

Hope it helps!

**Comment by 1014156094** [comment]
`.vscode/settings.json`

```
"javascript.validate.enable": false,
"vetur.validation.script": false
```

**Comment by JJBocanegra** [comment]
@andrese03 @1014156094 your settings work, but what do we lose deactivating those options?

Also I want to comment that the error only happens in JS files, in Vue files it works correctly :confused:

**Comment by nicholascm** [comment]
@JJBocanegra  It seems that when [Typescript officially supports this operator](https://github.com/Microsoft/TypeScript/issues/16) targeted in milestone 3.7.0, the error should definitely go away. Until then, `"javascript.validate.enable": false` turns off the [default Typescript validations](https://vscode.readthedocs.io/en/latest/languages/javascript/) for your _javascript_ code.

For my team which is using ESLint already for validation, this hack/fix doesn't cause too much of an issue. If you are relying on that default validation and do not have ESLint or some equivalent setup, then I think it will be a problem.

**Comment by ben-turner** [comment]
Hrm I'm seeing this issue in Neovim which doesn't have any built-in validation. Is there something that needed to be set up before these options?

**Comment by VimLeSai** [comment]
@bhardy thanks for details solution.

**Comment by r8rsfans75** [comment]
So this happened: https://github.com/microsoft/TypeScript/pull/33294

When will babel-eslint be updated to support it?

**Comment by nicholascm** [comment]
@r8rsfans75 I don’t think there’s anything to do here -  The typescript error mentioned in this issue will disappear as soon as the TS version is released with this change and your local VSCode is using it for validations.

**Comment by sunny-mittal** [comment]
To my knowledge, optional chaining with assignment is not yet (and may never be) supported: https://github.com/tc39/proposal-optional-chaining/issues/18

**Comment by olegskripko** [comment]
This issue has nothing to do with VSCode. I have the same issue in WebStorm and I don't have any settings for VSCode in the project.

**Comment by JeffGuKang** [comment]
The version of VSCode's typescript can be changed through command + shift + p and `Select typescript version`. and I am using optional chaining without validation error. 

![image](https://user-images.githubusercontent.com/216363/70891234-31890500-202a-11ea-9e92-c731ff4e31a8.png)

**Comment by felipecaparelli** [comment]
> The version of VSCode's typescript can be changed through command + shift + p and `Select typescript version`.
> 
> I am using optional chaining without validation error on VSCode with typescript v3.7.x .
> 
> ![image](https://user-images.githubusercontent.com/216363/70891234-31890500-202a-11ea-9e92-c731ff4e31a8.png)

If the Typescript file is open, you can change it by selecting the option on the **bottom blue bar** (you can find the VS Code version number on the right-side).

![vs-code-change-ts-compiler-version](https://user-images.githubusercontent.com/1261351/71725015-bb124280-2e32-11ea-9820-91a8569cd803.PNG)

**Comment by felipecaparelli** [comment]
> The version of VSCode's typescript can be changed through command + shift + p and `Select typescript version`.
> 
> I am using optional chaining without validation error on VSCode with typescript v3.7.x .
> 
> ![image](https://user-images.githubusercontent.com/216363/70891234-31890500-202a-11ea-9e92-c731ff4e31a8.png)

If the Typescript file is open, you can change it by selecting the option on the bottom blue bar (you can find the VS Code version number on the right-side).

![vs-code-change-ts-compiler-version](https://user-images.githubusercontent.com/1261351/71725104-104e5400-2e33-11ea-8bcd-2f66d78c5a09.PNG)

**Comment by shakhbulatgaz** [comment]
So, as of today, babel-eslint still yells at you if you use optional chaining?

**Comment by kaicataldo** [comment]
This will be supported in ESLint core soon and we will be working on updating the new `@babel/eslint-parser` now that we're unblocked. Please follow along at https://github.com/babel/babel/issues/11711.

**Comment by matheushf** [comment]
While it isn't on ESLint core yet, you should add `'parser': 'babel-eslint'` on `.eslintrc` and the plugin `'@babel/plugin-proposal-optional-chaining'` on `babel.config

https://dev.to/ismail9k/use-javascript-optional-chaining-today-2ech

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
