### ISSUE TITLE
Orphaned 'patch-eslint-scope.js' reference

### ISSUE THREAD

**Issue by lbogdan** [babel/babel-eslint#772]
In `babel-eslint@10.0.1` there's an orphaned reference to `patch-eslint-scope.js`, which was removed in #689:
https://github.com/babel/babel-eslint/blob/4cf0a21a4b12e64ce4012bbfcc62d0d969053f8b/lib/analyze-scope.js#L331

As we use `babel-eslint` in CodeSandbox, and version 11 has a breaking change, we had to fork and fix this in https://github.com/codesandbox/babel-eslint/commit/eea3bac70f7f9773201f3f27ec58ddc519aa0bd2 . Is there a way to fix that and publish a new `10.0.2` version? Thanks!

**Comment by hzoo** [comment]
Fine with me! Would accept a PR too but I'll just do it now

**Comment by hzoo** [comment]
https://github.com/babel/babel-eslint/pull/773 for 10.0.2
