### ISSUE TITLE
Does it support latest eslint?

### ISSUE THREAD

**Issue by yeongjet** [babel/babel-eslint#778]
These noted in document
```
ESLint | babel-eslint
-- | --
4.x | >= 6.x
3.x | >= 6.x
2.x | >= 6.x
1.x | >= 5.x
```
```
npm install eslint@4.x babel-eslint@8 --save-dev
```
Can I use latest eslint by running:
`npm install eslint babel-eslint --save-dev`?

**Comment by danez** [comment]
Yes just install the latest version for eslint 6.x
Or if you want you can also install the current beta version with 
```
npm install babel-eslint@next --save-dev
```
