### ISSUE TITLE
Error when use typescript Pick, keyof

### ISSUE THREAD

**Issue by leezng** [babel/babel-eslint#782]
```ts
interface Test {
  test: string;
  books: object[];
  roles: object[];
  createTime: number;
}

interface ProjectDescProps extends Pick<Test, Exclude<keyof Test, 'test'>> {}
```

Got error:

![image](https://user-images.githubusercontent.com/13777294/61272217-30348180-a7d9-11e9-82a2-9b41bfb54d0d.png)

**Comment by paztis** [comment]
I also have this error. Any news about this problem

**Comment by fatso83** [comment]
Another simple example:
```typescript
export interface IClientConfiguration {
  production: boolean;
  groupChat: boolean;
}

type ConfigKeys = keyof IClientConfiguration;
```

[configs.zip](https://github.com/babel/babel-eslint/files/3985723/configs.zip)

**Comment by kaicataldo** [comment]
Thank you for the issue. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
