### ISSUE TITLE
Doesn't work with custom parser through `parserOverride`

### ISSUE THREAD

**Issue by nfantone** [babel/babel-eslint#786]
On latest `11.0.0-beta.0`, using a custom parser through [`parserOverride`](https://babeljs.io/docs/en/babel-parser#faq), breaks token conversion logic defined in [`convertToken.js`](https://github.com/babel/babel-eslint/blob/master/lib/babylon-to-espree/convertToken.js#L3).

This is due to the `tt` instance (i.e.: babel types) being [_required from `@babel/core`_](https://github.com/babel/babel-eslint/blob/master/lib/parse.js#L6), which, in turn, extracts token definitions from `@babel/parser` - which is later overridden by plugin options. Because `tokTypes` (a.k.a. `tt`) is a parser-dependant exported field, this has the undesired side-effect of **making all token type strict comparisons fail**.

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
