### ISSUE TITLE
Release babel-eslint@11

### ISSUE THREAD

**Issue by kentcdodds** [babel/babel-eslint#787]
I created [a milestone for tracking the progress on this](https://github.com/babel/babel-eslint/milestone/1). I'm not certain whether I added all of the relevant PRs and issues though. I'm hoping that by tracking this we can get a better sense of what needs to happen and what blockers there are for this. I personally have been having a great experience with the alpha and would love to have an official release :)

**Comment by mskelton** [comment]
This issue was created 8 months ago and very little has happened since then.  I too would like to see v11 get released, but with issues that are over a year old still pending, most would assume this project is dead and move on.  Is there any plan to continue development on v11 and if not, where does that leave current users of babel-eslint?

**Comment by existentialism** [comment]
@mskelton curious, is there a specific issue you're needing fixed? is there something in `11.0.0-beta.2` that isn't working?

We absolutely plan on continuing development: we've already spent a bit of effort moving and consolidating all the [babel/eslint-related packages](https://github.com/babel/babel/tree/master/eslint) into our monorepo, and are committed to supporting them all (keep in mind we're a small team of volunteers)!

**Comment by kaicataldo** [comment]
As @existentialism said, we've continued working on this project in the babel/babel repo (please see the relevant issue [here](https://github.com/babel/babel/issues/10752) if you want to follow along).

**Comment by mskelton** [comment]
Thanks for the info!  I wasn't aware that this was being moved to the main repo.  Thanks for all the work you do in maintaining Babel!

**Comment by existentialism** [comment]
👍 are you using v11 beta? We definitely want to make sure we fix any issues you (or others) are having!

**Comment by mskelton** [comment]
@existentialism No, the v11 beta is working well, I was just concerned if I needed to look for a different tool if this was no longer going to be maintained, but you answered that question, so I'm all good now 👍   Thanks again!

**Comment by rjgotten** [comment]
> @existentialism 
> Is there something in `11.0.0-beta.2` that isn't working?

Yes; there is actually. 

Specifically https://github.com/babel/babel/issues/10904, which apparantly was fixed in `@babel/eslint-parser` with https://github.com/babel/babel/pull/10828 but was perhaps not back-ported to `babel-eslint` yet.
