### ISSUE TITLE
Custom JSX (deku) - variable is defined but never used

### ISSUE THREAD

**Issue by voronianski** [babel/babel-eslint#79]
In such [deku](https://github.com/segmentio/deku) code ESLint throws warnings:

```javascript
/** @jsx dom */

//  dom is defined but never used
import deku, { dom } from 'deku';

//  Button is defined but never used
let Button = {
    handleClick() {
        console.log('Button clicked!');
    },

    render(component) {
        const { props } = component;
        return (
            <button onClick={this.handleClick}>{props.text}</button>
        );
    }
};

let app = deku.scene();
app.mount(
    <Button text="Click me!" />
);

deku.render(app, document.getElementById('deku-app'));
```

Is there a workaround without disabling `no-unused-vars`?

**Comment by sebmck** [comment]
Can you please provide the errors that are being thrown

On Monday, 27 April 2015, Dmitri Voronianski <notifications@github.com>
wrote:

> In such deku code eslint throws warnings:
>
> /** @jsx dom */
> //  dom is defined but never usedimport deku, { dom } from 'deku';
> //  Button is defined but never usedlet Button = {
>     handleClick() {
>         console.log('Button clicked!');
>     },
>
>     render(component) {
>         const { props } = component;
>         return (
>             <button onClick={this.handleClick}>{props.text}</button>
>         );
>     }
> };
> let app = deku.scene();
> app.mount(
>     <Button text="Click me!" />
> );
>
> deku.render(app, document.getElementById('deku-app'));
>
> Is there a workaround without disabling no-unused-vars?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel-eslint/issues/79>.
>


-- 
Sebastian McKenzie

**Comment by voronianski** [comment]
@sebmck `Button is defined but never used`

**Comment by sebmck** [comment]
Use the rules in [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react).

**Comment by voronianski** [comment]
@sebmck thanks!
