### ISSUE TITLE
Function expression generics shadow

### ISSUE THREAD

**Issue by amiralies** [babel/babel-eslint#790]
It seems `no-shadow` does not behave correctly with generic function expressions ,

```js
const identity = function identity<T>(x: T): T {
  return x;
};
```

```
  18:27  error  'identity' is already declared in the upper scope  no-shadow
```

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
