### ISSUE TITLE
Bump lodash version to avoid security alerts from yarn and github

### ISSUE THREAD

**Issue by damianobarbati** [babel/babel-eslint#798]
It's time to bump `lodash` version!

<img width="649" alt="Screenshot 2019-08-30 at 12 57 31" src="https://user-images.githubusercontent.com/2225869/64015864-c45a6e00-cb25-11e9-8ae5-88692ea3b916.png">

**Comment by kaicataldo** [comment]
It doesn’t look like `babel-eslint`uses `lodash` directly, so this would need to be updated in the respective package that does.

**Comment by existentialism** [comment]
@damianobarbati may have to update your babel deps (maybe even manually remove entries from lockfile), as latest versions should all use `lodash@4.17.13`

**Comment by JLHwung** [comment]
There is a handy tool called [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate#usage) which should help you in this cases
```
yarn-deduplicate --packages lodash yarn.lock
```

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
