### ISSUE TITLE
Failed to load parser 'babel-eslint' declared in 'CLIOptions': Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by qianzhangsheng** [babel/babel-eslint#808]
* Node version 
```
v10.16.3
```
* npm/yarn version 
```
npm 6.12.0
```
* ESLint version (actual version, not the semver range) 
```
6.6.0
```
* babel-eslint version (actual version, not the semver range) 
```
10.0.3
```
* The config you're using when you run into this issue
```
const linter = new CLIEngine({
    fix: program.fix,
    ignorePattern: [],
    useEslintrc: false,
    parser: 'babel-eslint',
    parserOptions: {
        sourceType: 'module'
    },
    cwd: process.cwd(),
    env: ['browser'],
    plugins: [
        'html'
    ],
    rules,
});
```
.eslintrc.js
```
module.exports = {
    root: true,
    parser: 'babel-eslint',
    parserOptions: {
        sourceType: 'module'
    },
    env: {
        browser: true,
    },
    plugins: [
        'html'
    ],
    'rules': {}
};
```
* How you're running ESLint (command line, editor plugin, etc.)
```
Run your own frame to run
```

### Question
```
Failed to load parser 'babel-eslint' declared in 'CLIOptions': Cannot find module 'babel-eslint'
```

Sorry, English is not good.

**Comment by kaicataldo** [comment]
It's hard to triage what's going on with the limited information we have here. Could you also include the following (and any other info you think would be helpful!):
* Node version
* npm/yarn version
* ESLint version (actual version, not the semver range)
* babel-eslint version (actual version, not the semver range)
* The config you're using when you run into this issue
* How you're running ESLint (command line, editor plugin, etc.)

Thanks!

**Comment by dr-dimitru** [comment]
@qianzhangsheng solved on my end with downgrading `eslint` to `v4.x`:

```shell
npm -g i eslint@4
```

**Comment by aeciolevy** [comment]
Thanks @dr-dimitru the same here I had to downgrade eslint.

**Comment by dr-dimitru** [comment]
@aeciolevy I'm still on `eslint@4.19.1`, while latest is v7 
Wonder why they won't make it compatible 🤔

**Comment by aeciolevy** [comment]
@dr-dimitru that's super weird. This has been pointed out 6 months ago. :(

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
