### ISSUE TITLE
shorthand deconstructing AST problem

### ISSUE THREAD

**Issue by fisker** [babel/babel-eslint#809]
Issue found in https://github.com/sindresorhus/eslint-plugin-unicorn/issues/443 , and I located the problem is because `Identifier` node is not a reference of identifier.parent.key

Not sure what cause the problem, `eslint` ? `babel` ? or `babel-eslint`?

temporary workaround https://github.com/sindresorhus/eslint-plugin-unicorn/pull/444

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
