### ISSUE TITLE
no-use-before-define error with optional chaining

### ISSUE THREAD

**Issue by joker-777** [babel/babel-eslint#817]
Hello, I'm getting a `no-use-before-define` error with this line of code

```js
const test = {
  player: "player
}
cosnt player = test?.player
```

**Comment by kaicataldo** [comment]
Thanks for reporting this. ESLint will be supporting this in core now that this syntax has reached stage 4.

**Comment by joker-777** [comment]
Thanks for letting me now. I guess this is still something to be implemented?

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
