### ISSUE TITLE
Latest Babel + flow generates "is not defined" errors on star imports

### ISSUE THREAD

**Issue by lukeapage** [babel/babel-eslint#819]
code:
```
// @flow
import * as types from './types';

export default class X {
    Y(z: types.A) {
        return z;
    }
}
```
this code used to not generate errors and now generates:
```
5:16  error  'A' is not defined                          no-undef
```
I get the error when upgrading to the latest babel-eslint as I believe it forces babel-eslint to use the latest babel versions instead of old versions.

**Comment by lukeapage** [comment]
I spent a loooong time investigating this.

It turns out yarn was installing `@babel/types` both in the root and under `@babel/core` (the same version) and so the babel types monkey patching was applying to the wrong types package.

**Comment by lukeapage** [comment]
If you wanted to be safe, you could resolve the location of babel traverse, then from there the location of babel types rather than requiring core and using types off it..

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
