### ISSUE TITLE
npm WARN babel-eslint@11.0.0-beta.2 requires a peer of @babel/core@>=7.2.0 but none is installed

### ISSUE THREAD

**Issue by aladdin-add** [babel/babel-eslint#820]
I'm using babel-eslint v11 and setting [requireConfigFile to `false`](https://github.com/babel/babel-eslint#additional-parser-configuration), but got:

```bash
npm WARN babel-eslint@11.0.0-beta.2 requires a peer of @babel/core@>=7.2.0 but none is installed. You must install peer dependencies yourself.
```

is `@babel/core` should be listed in `optionalDependencies` in this case?

**Comment by ogonkov** [comment]
What is `npm ls --depth=0` outputs? @aladdin-add

**Comment by kaicataldo** [comment]
v11 still uses `@babel/core` to parse even when `requireConfigFile` is set to `false`, so I don't think so.

**Comment by aladdin-add** [comment]
thanks for clarification!!
