### ISSUE TITLE
How to use babel-eslint in a non-node JS environment (such as client environment, browser)

### ISSUE THREAD

**Issue by liuliangsir** [babel/babel-eslint#829]
As the above title says,  I would like to use babel-eslint to support experimental (such as top level await) syntax used in [CodeMirror](https://codemirror.net/). Up to now, Linting Client-Side JavaScript code with ESLint is perfect. In addition, Is there any workaround to solve the issue above? I am looking forward to your reply.

**Comment by kaicataldo** [comment]
We don't officially support browser targets in `babel-eslint` (note that neither does ESLint!). Can you share more information about what issues you're running into? Note that the latest prerelease version of `babel-eslint` reads your Babel config file.

**Comment by liuliangsir** [comment]
> We don't officially support browser targets in babel-eslint (note that neither does ESLint!)

It appears to be incorrect? After checking out the demo [here](https://eslint.org/demo), I manage to copy lint feature from eslint to browser target environment. But in fact, I only use `verifyAndFix` api exposed by `eslint/lib/linter/linter` under the hood.

As I mentioned earlier, I need to enable experimental syntax(such as top level await) lint for javascript code inside [CodeMirror](https://codemirror.net/). So as you can see, There are all my own issues.

**Comment by kaicataldo** [comment]
We bundle ESLint for the demo, but it's not a use-case we officially support for 3rd parties. You are definitely free to use it in the browser, but please know that we can't guarantee that it will continue working in future versions.

**Comment by cruzdanilo** [comment]
any workaround for `top-level-await`?

**Comment by liuliangsir** [comment]
@cruzdanilo [Here](https://github.com/standard-things/esm/issues/814) is a workaround.

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
