### ISSUE TITLE
Breaking change in Node 13.13

### ISSUE THREAD

**Issue by rakusan2** [babel/babel-eslint#831]
Node v13.13 has made a breaking change to `exports`

To fix this babel/core needs to be upgraded to v7.9.0 

This issue is detailed in issue nodejs/node#32852

**Comment by nicolo-ribaudo** [comment]
`babel-eslint` doesn't depend on `@babel/core`. Also, it use `^` for its dependencies so you can automatically update them.

**Comment by rakusan2** [comment]
Sorry, I must have missed that
