### ISSUE TITLE
Typescript: parsing error when using "readonly" in interface

### ISSUE THREAD

**Issue by mtjn** [babel/babel-eslint#832]
```typescript
/* example.ts */

// error: Parsing error: Unexpeced token, expected ":"
interface example {
  readonly id: string;
//         ^
}
```

```
/* .eslintrc */
{
  "root": true,
  "env": {
    "es6": true,
    "node": true,
    "jest/globals": true
  },
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended",
    "plugin:prettier/recommended",
    "plugin:jest/recommended"
  ],
  "plugins": [
    "prettier",
    "jest"
  ]
}
```

```javascript
/* babel.config.js */
module.exports = {
  presets: [
    ["@babel/preset-env", { targets: { node: "current" } }],
    "@babel/preset-typescript",
  ],
};
```

```json
/* package.json */
"@babel/core": "^7.8.3",
"@babel/preset-typescript": "^7.8.3",
"babel-eslint": "^10.1.0",
"babel-jest": "^25.1.0",
"eslint": "^6.1.0",
"eslint-config-prettier": "^6.0.0",
"eslint-plugin-jest": "^23.6.0",
"eslint-plugin-prettier": "^3.1.0",
"jest": "^25.1.0",
"prettier": "^2.0.5",
"typescript": "^3.8.3"
```

**Comment by kaicataldo** [comment]
Can you see if this is still an issue with the latest version of `babel-eslint` (11.0.0-beta.2
)? Also please note that [active development has been moved to the `babel/babel` repository](https://github.com/babel/babel-eslint/#note-babel-eslint-is-being-moved-into-the-babel-monorepo-please-follow-along-here-to-track-our-progress).

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
