### ISSUE TITLE
Expected indentation is forced for comments as well

### ISSUE THREAD

**Issue by literakl** [babel/babel-eslint#833]
WebStorm places comment characters at start of the line:

```
/*
    some code
*/
```
but Eslint hates it and I need to manually indent these comments as well. Version 10.1.0.

```
Module Error (from ./node_modules/eslint-loader/index.js):
error: Expected indentation of 6 spaces but found 0 (indent) at src\components\molecules\SeriesBarChart.vue:19:1:
> 19 | /*
```

Expected behaviour:

indentation is not checked for comments

**Comment by kaicataldo** [comment]
This is not an issue with `babel-eslint`. Please use the [`ignoreComments` configuration option[(https://eslint.org/docs/rules/indent#ignorecomments) for the `indent` rule.
