### ISSUE TITLE
`RegExpLiteral` is not converted to `Literal` in an edge case

### ISSUE THREAD

**Issue by futpib** [babel/babel-eslint#838]
Broken example:

```js
> require('babel-eslint').parse('1 * /a/').body[0].expression.right.type
'RegExpLiteral'
```

Changing `*` to `+` makes `babel-eslint` behave properly:

```js
> require('babel-eslint').parse('1 + /a/').body[0].expression.right.type
'Literal'
```

Version:

```console
$ npm list babel-eslint
eslint-template-visitor@2.1.1 /home/futpib/code/eslint-template-visitor
└── babel-eslint@10.1.0
```

Of course no one writes `x * /a/`, but this bug breaks my fuzzing test.

**Comment by kaicataldo** [comment]
Thanks for the bug report. `babel-eslint` is currently being moved into the babel/babel monorepo. You can follow along on [this issue](https://github.com/babel/babel/issues/10752). I'll be adding this to the list in that issue and take a look at it.

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [`@babel/eslint-parser` has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).
