### ISSUE TITLE
Template-literal rule attempting to run on nullish coalescing operations, and then crashing eslint

### ISSUE THREAD

**Issue by GeorgeWL** [babel/babel-eslint#839]
I'm having this rule erroneously triggering on the new ?? (nullish coalescing) operator

https://gist.github.com/GeorgeWL/0a7ce21622259e84d39a929b8cd72c81 for the full logs and details

lint command in my package json is

"lint": "eslint . -c .eslintrc.js --ext js,jsx --fix"

https://gist.github.com/GeorgeWL/0a7ce21622259e84d39a929b8cd72c81#file-error-reports-from-here-js-L4 is the source of the error

there seems to be a workaround here:
https://github.com/babel/babel-eslint/issues/799#issuecomment-651954838

**Comment by JLHwung** [comment]
Fixed in `@babel/eslint-parser` 7.11.0, see https://babel.dev/blog/2020/07/13/the-state-of-babel-eslint#the-future for the renaming guide.
