### ISSUE TITLE
error transform is not defined when using babel-core 5.2.7 as babel-eslint dependency

### ISSUE THREAD

**Issue by aruberto** [babel/babel-eslint#84]
Linting any java script file with babel-core 5.2.7 producing the following error: 

λ .\node_modules\\.bin\eslint config.js

config.js
  0:0  error  transform is not defined

✖ 1 problem (1 error, 0 warnings)

.eslintrc file used:
```
{
  "parser": "babel-eslint",
  "rules": {
    "strict": 0,
    "no-underscore-dangle": 0,
    "no-unused-vars": 0,
    "curly": 0,
    "no-multi-spaces": 0,
    "key-spacing": 0,
    "no-return-assign": 0,
    "consistent-return": 0,
    "no-shadow": 0,
    "no-comma-dangle": 0,
    "no-use-before-define": 0,
    "no-empty": 0,
    "new-parens": 0,
    "no-cond-assign": 0
  },
  "env": {
    "node": true
  }
}
```

When using babel-core 5.2.6 linting works correctly.

**Comment by aruberto** [comment]
Seems like babel 5.2.9 was just released 15 minutes ago and fixes the issue.

**Comment by sebmck** [comment]
Yep, duplicate of #83.
