### ISSUE TITLE
Looking for more maintainers

### ISSUE THREAD

**Issue by sebmck** [babel/babel-eslint#88]
I don't have time to maintain babel core and babel-eslint so I'm looking for someone(s) to take over maintenance. This would include triaging issues, fixing bugs, reviewing pull requests and releasing new versions. Ideally they'd have experience with AST-based tooling as well as how to write ESLint rules. Familiarity with ESLint internals would be most preferable too so bugs can be identified as residing in the babel-eslint compatibility layer or ESLint itself.

**Comment by metagen** [comment]
To be clear, babel-core is not in need of a maintainer?

**Comment by sebmck** [comment]
Correct, this is only for `babel-eslint`.

**Comment by hzoo** [comment]
I'l be working on supporting jscs with babel with https://github.com/jscs-dev/babel-jscs once I figure out the issues there. If so, some of the issues will probably be the same (esprima/espree) so I maybe of some help although I'm just starting to work with ASTs and eslint.

**Comment by sebmck** [comment]
@hzoo Awesome! Some of the stuff, notably [acorn-to-esprima](https://github.com/babel/babel-eslint/blob/master/acorn-to-esprima.js) could likely be abstracted into a different library (as suggested in #24) that both could use.

**Comment by bendrucker** [comment]
I haven't spent a ton of time with ESLint but I'm willing to step up and take the lead on project management (issues, PRs, releases) and get up to speed on ESLint internals along the way. I'm a big proponent of https://github.com/feross/standard. I'm hoping that if we can get babel-eslint rock solid and demonstrate popular interest I can convince Feross to support custom parsers.

**Comment by gyandeeps** [comment]
@sebmck I would be able to help as I understand eslint.
Do let me know.
Thanks

**Comment by hzoo** [comment]
I think we're good now :smile:

**Comment by hzoo** [comment]
You don't have to be a maintainer, but we're at least looking for some more contributors!

**Comment by marudor** [comment]
I would be willing to contribute as good as I can (I'm probably not familiar enough with eslint/babel to maintain it myself)

**Comment by hzoo** [comment]
Right the issue with this project in particular is that it sort of requires you to have to know about both projects and to fix issues when there might be a minor version change like what happened with https://github.com/babel/babel-eslint/issues/267. Hopefully that doesn't happen again.

**Comment by vtambourine** [comment]
I would love to contribute to this project, since I use it a lot in different places. However I haven't spent much time hacking ESLint core, I am familiar with linters, JSCS and, of course, Babel.

**Comment by sstern6** [comment]
@hzoo been contributing quite a bit to ESLINT.  Would love to get more into babel, havent contributed yet.  I have the band with, if you would like me to help out on babel-eslint please let me know.  If you think i need more experience with babel, I completely understand but wanted to let you know i was available and interested.

Thanks!!!!!

**Comment by reznord** [comment]
Hey @hzoo, sorry for dropping on here after a really long time.

I haven't really contributed much to babel before except for this one [issue](https://github.com/babel/babel/issues/6108). Right now I'm spending my time contributing to [preact-cli](https://github.com/developit/preact-cli).

It would be my pleasure to help with this project if you are interested.

**Comment by ferrao** [comment]
@hzoo, I have some (limited) experience with AST tooling, but I would be keen on helping if the project is still looking for additional manpower.
