### ISSUE TITLE
Variable of array comprehension not defined

### ISSUE THREAD

**Issue by AluisioASG** [babel/babel-eslint#9]
```js
let a = [], b = [for (e of a) String(e)];
```
results in:
```
  1:12  error  b is defined but never used  no-unused-vars
  1:22  error  'e' is not defined           no-undef
  1:37  error  'e' is not defined           no-undef
```

**Comment by jeroencranendonk-wf** [comment]
Same for generator comprehensions.

**Comment by zdychacek** [comment]
Is there any plan to implement support for array/generator comprehensions?

It would be great ;)

Thanks for reply.

**Comment by sebmck** [comment]
Not sure if it's possible because it'd require patching too much of escope
and I'm not sure if it'd be possible. Patches are welcome :)

On Tuesday, 14 April 2015, Ondřej Ždych <notifications@github.com> wrote:

> Is there any plan to implement support for array/generator comprehensions?
>
> It would be great ;)
>
> Thanks for reply.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel-eslint/issues/9#issuecomment-93001895>.
>


-- 
Sebastian McKenzie

**Comment by hzoo** [comment]
I guess this won't be too different from #72

**Comment by KylePDavis** [comment]
For what it's worth, I've used this as a hack to work around this for now:

```javascript
/*global cVar*///NOTE: "fix" linter errs for comprehension vars
```

**Comment by callumlocke** [comment]
@KylePDavis that helps, thanks

**Comment by hzoo** [comment]
Hey everyone, does #114 fix your issues?

**Comment by KylePDavis** [comment]
Thanks, @hzoo, that does seem to fix the `no-undef` rule complaints but it also seems to trigger `block-scoped-var` complaints.

Example:
```javascript
"use strict";
export default [for (i of global) String(i)];
//OR: (for (i of global) String(i));
```

Errors:

```console
  2:21  error  "i" used outside of binding context  block-scoped-var
  2:41  error  "i" used outside of binding context  block-scoped-var
```

**Comment by hzoo** [comment]
Ah dang I added the variable in the wrong scope.. (most likely just need to move it up a level)

**Comment by hzoo** [comment]
@KylePDavis yeah I'm not sure at the moment =/. I guess this is besides the point but if you are using babel  (with let/const) which are already block scope then you wouldn't need the rule (`block-scoped-var`) anymore right? Or is there something else that it catches?

**Comment by gaearon** [comment]
f921efa6fbe06d2f379e6b8b0a3177ff260b6b82 works great for me, only `no-unused-vars` false-triggering now in my comprehensions code.

**Comment by hzoo** [comment]
@gaearon Can you give me a code snippet that is failing for you? I can add `no-unused-vars` to the tests now.

**Comment by gaearon** [comment]
```js
function getFirstAtom(stores) {
  return new Map([
    for (store of stores)
      [store, undefined]
  ]);
}

getFirstAtom();
```

`stores` parameter is reported to be unused.

Thanks a lot for the effort! Your work saved me a lot of headache in the past few weeks.

**Comment by hzoo** [comment]
Ah ok I didn't visit the `node.right` (stores in your case). Shouldn't be too hard to fix.

Awesome! It's be fun contributing and learning all this stuff (btw `react-hot-loader` is great)

**Comment by hzoo** [comment]
@gaearon See if the next commit fixes it https://github.com/hzoo/babel-eslint/commit/8e254b7db1b6b4b0a373972f2bea634de7e2504f.

**Comment by gaearon** [comment]
@hzoo Works great. Thanks again.

**Comment by declandewet** [comment]
Still getting this issue with the below snippet

```
function entries(obj) {
  return (for (key of Object.keys(obj)) [key, obj[key]])
}
```

**Comment by callumlocke** [comment]
Are you sure you're on the latest version? I don't get this problem any
more.

**Comment by declandewet** [comment]
@callumlocke yep:

![](https://infinit.io/_/3mQxXzH.png)

**Comment by hzoo** [comment]
@declandewet can you make a seperate issue for this? The original issue was for `no-undef` and this is for `block-scoped-var`/

**Comment by declandewet** [comment]
@hzoo #148 :smile:
